### ISSUE TITLE
OCaml opam

### ISSUE THREAD

**Issue by skyzh** [sjtug/mirror-requests#108]
镜像名: opam

上游路径: http://opam.ocaml.org/packages/

镜像简介: OCaml 包管理器

国内其他镜像源同步情况: https://github.com/tuna/issues/issues/767

同步方法: git 同步 opam-repository (https://github.com/ocaml/opam-repository.git) + 反代 opam cache (https://opam.ocaml.org/cache)

镜像大小:

状态追踪:

- [x] 同意同步
- [x] 同步脚本
- [x] 部署到镜像源 (git)
- [x] 部署到镜像源 (reverse proxy)
- [x] 首次同步成功
- [x] 测试脚本
- [x] 使用文档 https://github.com/sjtug/portal/pull/31
- [ ] 添加到官方源

**Comment by skyzh** [comment]
cc @peterzheng98

**Comment by liyishuai** [comment]
Not so usable: #287
