### ISSUE TITLE
新增google-fonts反代

### ISSUE THREAD

**Issue by htfy96** [sjtug/mirror-requests#11]
**类别**：新增镜像

**镜像名**：google-fonts

**上游路径**：
```
ajax.googleapis.com => ajax.lug.ustc.edu.cn
fonts.googleapis.com => fonts.lug.ustc.edu.cn
themes.googleusercontent.com => google-themes.lug.ustc.edu.cn
```

**Comment by hebingchang** [comment]
准备用 nginx 反代嘛？

**Comment by htfy96** [comment]
@hebingchang 目前整个技术栈是基于Caddy的，但是问题是Caddy缺少nginx的`subs_filter`来改写上游相应中的`foo.googlecontents.com`到我们的代理中，所以我们需要先实现一个Caddy的`subs_filter`插件，可能会咕咕咕一段时间（

**Comment by SkyZH** [comment]
- [ ] Install Caddy with `http.filter` and `http.cache`
- [ ] Deploy

另外为啥要 proxy `ajax.googleapis.com` 和 `themes.googleusercontent.com` ?

**Comment by SkyZH** [comment]
-> https://github.com/abiosoft/caddy-docker

```bash
docker build --build-arg \
    plugins=git,linode \
    github.com/abiosoft/caddy-docker.git
```
