### ISSUE TITLE
请求添加opkg镜像

### ISSUE THREAD

**Issue by dzx-dzx** [sjtug/mirror-requests#113]
镜像名: opkg

上游路径: https://downloads.openwrt.org/

镜像简介: opkg（英語：Open PacKaGe management）是一款基于ipkg的轻量级包管理器，由C语言编写，使用的时候类似高级包装工具和dpkg。用于嵌入式GNU/Linux设备，并在OpenEmbedded和OpenWrt等项目中使用。

国内其他镜像源同步情况:

同步方法:

镜像大小:

状态追踪:

- [x] 同意同步
- [x] 同步脚本
- [x] 部署到镜像源
- [x] 首次同步成功
- [x] 测试脚本
- [ ] 使用文档
- [ ] 添加到官方源

**Comment by skyzh** [comment]
opkg 大约要 500GB，目前镜像站空间有限，考虑之后添加。

**Comment by skyzh** [comment]
已经在新镜像服务器上添加，预计下个月上线。
