### ISSUE TITLE
flutter not working

### ISSUE THREAD

**Issue by wzc11227** [sjtug/mirror-requests#124]
when i access to the folder of flutter, it never work

**Comment by skyzh** [comment]
We'll try to fix this. Meanwhile, you may use other mirror sites (e.g. TUNA)

**Comment by skyzh** [comment]
It seems to be a temporarily upstream issue. We restarted related service and it just works fine. You may reopen this issue if you need further assistance.

**Comment by skyzh** [comment]
Flutter 镜像源已切换为全量同步，服务质量应当有显著提升。欢迎使用。
