### ISSUE TITLE
New mirror request: popular Git repos

### ISSUE THREAD

**Issue by PragmaTwice** [sjtug/mirror-requests#129]
镜像名: 热门 Git 仓库，列表可参考 [Gitee Mirrors](https://gitee.com/mirrors) ，建议额外加入 [LLVM](https://github.com/llvm/llvm-project)

大胆的想法：对 GitHub 的全部仓库提供反代服务

状态追踪:

- [ ] 同意同步
- [ ] 同步脚本
- [ ] 部署到镜像源
- [ ] 首次同步成功
- [ ] 测试脚本
- [ ] 使用文档
- [ ] 添加到官方源

**Comment by skyzh** [comment]
LLVM is available now at https://mirror.sjtu.edu.cn/git/llvm-project.git/ . For other git repos, we would prefer letting our users separately submitting a mirror request.
