### ISSUE TITLE
ubuntu 镜像的路径问题

### ISSUE THREAD

**Issue by clouduan** [sjtug/mirror-requests#13]
**类别**：Bug反馈

**镜像名**：Ubuntu

点击路径 https://mirrors.sjtug.sjtu.edu.cn/ubuntu/ 下的 Ubuntu 目录，结果如图。对镜像源维护不是很了解，不知道这是不是bug...
![default](https://user-images.githubusercontent.com/20282795/40157995-aa5fb6e0-59d4-11e8-8df8-eee9269f781b.PNG)

**Comment by htfy96** [comment]
并没有问题……这个ubuntu是指向自身的软链接。http://cn.archive.ubuntu.com/ubuntu/也是这样
