### ISSUE TITLE
增加 Linux Lite 镜像

### ISSUE THREAD

**Issue by hmsjy2017** [sjtug/mirror-requests#130]
镜像名:Linux Lite

上游路径: http://repo.linuxliteos.com/linuxlite/
rsync://repo.linuxliteos.com/repo

镜像简介: Linux Lite 是一个基于 Ubuntu 长期支持版本（LTS）的 Linux 发行版，搭载 Xfce 桌面环境。Linux Lite 的目的是将 Windows 用户引入 Linux，对新手比较友好。其旨在提供一套完整的应用程序来帮助用户满足用户日常的计算需求，这包括完整的办公套件、媒体播放器和其他基本的日常软件。

国内其他镜像源同步情况:中国大陆无镜像站

同步方法: 见 https://www.linuxliteos.com/mirrors.php
支持rsync 
rsync://repo.linuxliteos.com/repo

镜像大小:约40GB

状态追踪:

- [x] 同意同步
- [x] 同步脚本
- [x] 部署到镜像源
- [x] 首次同步成功
- [ ] 测试脚本
- [ ] 使用文档
- [ ] 添加到官方源

**Comment by skyzh** [comment]
已上线 https://mirrors.sjtug.sjtu.edu.cn/linuxliteos/ 。欢迎帮助我们完善使用文档。https://github.com/sjtug/portal/tree/master/content/post/mirror-help

**Comment by hmsjy2017** [comment]
> 已上线 https://mirrors.sjtug.sjtu.edu.cn/linuxliteos/ 。欢迎帮助我们完善使用文档。https://github.com/sjtug/portal/tree/master/content/post/mirror-help

文档已添加
