### ISSUE TITLE
Guix

### ISSUE THREAD

**Issue by skyzh** [sjtug/mirror-requests#131]
镜像名: GuixSD

上游路径: ci.guix.gnu.org

镜像简介:

国内其他镜像源同步情况: https://github.com/ustclug/mirrorrequest/issues/96 https://github.com/tuna/issues/issues/199

同步方法: mirror-intel + mirror-clone

镜像大小: unknown

状态追踪:

- [x] 同意同步
- [x] 同步脚本
- [x] 部署到镜像源
- [x] 首次同步成功
- [x] 测试脚本 https://github.com/sjtug/mirror-test-scripts/pull/14
- [x] 使用文档 https://github.com/sjtug/portal/pull/42
- [ ] 添加到官方源

**Comment by pmeiyu** [comment]
Guix客户端更新时需要下载Guix的源代码，希望把Git仓库 `https://git.savannah.gnu.org/cgit/guix.git` 也加到SJTUG的镜像列表里。

**Comment by skyzh** [comment]
> Guix客户端更新时需要下载Guix的源代码，希望把Git仓库 `https://git.savannah.gnu.org/cgit/guix.git` 也加到SJTUG的镜像列表里。

好的，之后会再添加。

**Comment by skyzh** [comment]
@pmeiyu 我们已经在主站上线了智能缓存 https://mirrors.sjtug.sjtu.edu.cn/guix/ 。可否帮忙测试一下？缓存的文件都会跳转到 s3.jcloud.sjtu.edu.cn 下载。

如果可以的话，也可以帮忙在这里 https://github.com/sjtug/portal/tree/master/content/post/mirror-help 更新使用文档，在 https://github.com/sjtug/mirror-test-scripts 提供测试脚本。

**Comment by skyzh** [comment]
由于 Guix 对 302 redirect 支持有问题，我们考虑采用 s3 后端的反向代理构建镜像。

**Comment by skyzh** [comment]
测试镜像已上线。建议反馈 guix 包管理器支持 301/302 重定向。

**Comment by skyzh** [comment]
guix git 镜像已上线，可以通过 https://git.sjtu.edu.cn/sjtug/guix.git clone，或者通过 HTTP 浏览文件。在正式上线后，我们将以 1h 的频率进行同步。

**Comment by skyzh** [comment]
Guix 镜像已经正式发布。https://sjtug.org/post/mirror-news/2020-12-21-release-guix/
