### ISSUE TITLE
pytorch-wheels

### ISSUE THREAD

**Issue by skyzh** [sjtug/mirror-requests#133]
镜像名: pytorch-wheels

上游路径: download.pytorch.org/whl

镜像简介:

国内其他镜像源同步情况: https://github.com/tuna/issues/issues/363 https://github.com/tuna/issues/issues/1050

同步方法: mirror-clone + mirror-intel

镜像大小:

状态追踪:

- [x] 同意同步
- [x] 同步脚本
- [x] 部署到镜像源
- [x] 首次同步成功
- [x] 测试脚本 (https://github.com/sjtug/mirror-test-scripts/pull/16)
- [x] 使用文档 (https://github.com/sjtug/portal/commit/af230aff5754fe5ab2fbe9307f20b2e8518eab29)
- [ ] 添加到官方源

**Comment by skyzh** [comment]
SJTU users may try `pip install torch==1.7.1+cu101 torchvision==0.8.2+cu101 torchaudio==0.7.2 -f https://siyuan.internal.sjtug.org/pytorch-wheels/torch_stable.html` inside SJTU. We will make this registry available along with new `ftp.sjtu.edu.cn`.

**Comment by skyzh** [comment]
```
pip install torch===1.7.1 torchvision===0.8.2 torchaudio===0.7.2 -f https://mirror.sjtu.edu.cn/pytorch-wheels/torch_stable.html
```

**Comment by arcosx** [comment]
thanks ! this mirror help me.
