### ISSUE TITLE
帮助页面代码块显示问题

### ISSUE THREAD

**Issue by hmsjy2017** [sjtug/mirror-requests#135]
![0c3eab9191fdfc204f5827cfcb426099.png](https://ppmm.org/images/2020/12/15/0c3eab9191fdfc204f5827cfcb426099.png)
无法移动，导致不能正常复制

**Comment by skyzh** [comment]
之前已经修复，但是由于各种原因不能上线。感谢反馈。另外 Ubuntu 的配置建议不要复制，而是使用 sed 等指令进行替换。

**Comment by skyzh** [comment]
问题已经修复。
