### ISSUE TITLE
新镜像请求: DragonFly BSD 系统 ISO 及软件包仓库

### ISSUE THREAD

**Issue by liweitianux** [sjtug/mirror-requests#137]
镜像名:
DragonFly BSD 系统 ISO 及软件包仓库

上游路径:
* 主页: https://avalon.dragonflybsd.org/
* 系统 ISO (已发布): https://avalon.dragonflybsd.org/iso-images/
* 系统 ISO (最近两月的每日编译): https://avalon.dragonflybsd.org/snapshots/
* 预编译软件包仓库: https://avalon.dragonflybsd.org/dports/

镜像简介:
[DragonFly BSD](https://www.dragonflybsd.org/) 是四大 BSD 系统中比较小众的一个，于 2003 年复刻自 FreeBSD 4.8，对 VM、SMP 等子系统做了大幅修改，拥有出色的性能，还有自己开发的 [HAMMER](https://en.wikipedia.org/wiki/HAMMER_(file_system)) 和 [HAMMER2](https://en.wikipedia.org/wiki/HAMMER2) 文件系统亦是其特色功能。DragonFly BSD 内核简洁小巧，使用简单直接，社区虽小但很友好（主要使用 IRC，本人已潜水多年 :smile:）。

国内其他镜像源同步情况:
目前国内仅[香港 KoDDoS](https://mirror-hk.koddos.net/dragonflybsd/) 一家镜像站点，内地无镜像站点。

同步方法:
rsync

镜像大小:
* 系统 ISO (已发布): 10 GB
* 系统 ISO (最近两月的每日编译): 8.2 GB
* 预编译软件包仓库: 165 GB

(注: 软件包仓库目前支持 5 个 DragonFly 版本，我可以联系项目精简空间。)

状态追踪:

- [x] 同意同步
- [x] 同步脚本 https://github.com/sjtug/mirror-docker-siyuan/pull/96/
- [x] 部署到镜像源
- [x] 首次同步成功
- [ ] 测试脚本 (无法使用 Docker；能否使用 KVM ???)
- [x] 使用文档 https://github.com/sjtug/portal/pull/47
- [ ] 添加到官方源

**Comment by liweitianux** [comment]
另外补充一点本人信息：本人在本科期间加入过交大开源协会（不过协会不怎么活跃），于 2018 年成为 DragonFly BSD 开发者，于 2019 年从交大物理系毕业，有多年 Linux 和 BSD 使用经验，目前工作的一部分内容也与 Linux DevOps 相关。如果可以，我也非常愿意加入帮忙。

**Comment by skyzh** [comment]
我们已经在服务器上开始了首次同步，预计周末可以上线。感谢你的支持！

**Comment by skyzh** [comment]
> 我们已经在服务器上开始了首次同步，预计周末可以上线。感谢你的支持！

已经在新服务器上同步完成。但我们希望能直接在新服务器上上线，而非在现在的服务器上做转发，因此可能需要一段时间才能上线。

您可以通过交大校园网访问 https://siyuan.internal.sjtug.org 先行体验。

**Comment by liweitianux** [comment]
赞赞赞。我等你们弄好就用起来，同时将项目官方镜像列表也更新。如果有什么需要帮忙，我很乐意。

我现在毕业工作了，不在校园网，暂时体验不了。

另外，这个域名解析到了内网 IP，现在我校校园网分配内网地址了、还是路由策略？我以前都没有留意过这种内网域名。

**Comment by skyzh** [comment]
交大云主机分配内网地址。

**Comment by liweitianux** [comment]
我利用实验室的一台服务器做了一个 Nginx 反向代理，效果还不错。以下是主要配置（方便给有兴趣的人一个参考）：

```nginx
# Proxy to internal SJTUG mirror
location /sjtug/ {
    proxy_pass        https://siyuan.internal.sjtug.org/;
    proxy_ssl_name    siyuan.internal.sjtug.org;
    proxy_ssl_server_name  on;
    proxy_set_header  Host               siyuan.internal.sjtug.org;
    proxy_set_header  X-Real-IP          $remote_addr;
    proxy_set_header  X-Forwarded-For    $proxy_add_x_forwarded_for;
    proxy_set_header  X-Forwarded-Proto  $scheme;
    proxy_set_header  Accept-Encoding    "";  # required to make following sub_filter work
    sub_filter        'href="/'  'href="/sjtug/';
    sub_filter        'href="/static/'  'href="/sjtug/static/';
    sub_filter        'src="/static/'   'src="/sjtug/static/';
    sub_filter_once   off;
}
```

坐等新服务器上线 :smile: 

@skyzh 我们应该还需要一个介绍/使用帮忙页面，我可以来做这个，请问我如何提供给你们？

**Comment by skyzh** [comment]
在这里创建一个文件就可以了 https://github.com/sjtug/portal/tree/master/content/post/mirror-help

**Comment by liweitianux** [comment]
我看测试脚本是基于 Docker 来测试的，但 BSD 因内核不同，无法使用 Docker 来做。不过考虑至 BSD 的用户群小，所以我认为暂时不做测试脚本也可以。

或者，如果刚好有 KVM 等虚拟机资源，可以搞一个 :smiley:

**Comment by skyzh** [comment]
> 我看测试脚本是基于 Docker 来测试的，但 BSD 因内核不同，无法使用 Docker 来做。不过考虑至 BSD 的用户群小，所以我认为暂时不做测试脚本也可以。
> 
> 或者，如果刚好有 KVM 等虚拟机资源，可以搞一个 😃

好的，这一部分我之后会用别的方法处理。感谢你的帮助。

**Comment by skyzh** [comment]
镜像已经正式上线。 https://mirror.sjtu.edu.cn/dragonflybsd/dports/

**Comment by liweitianux** [comment]
已更新到官方镜像列表页面，后面将会添加至包管理工具的配置文件

**Comment by liweitianux** [comment]
已添加至包管理工具的配置文件: https://github.com/DragonFlyBSD/DeltaPorts/pull/996
