### ISSUE TITLE
建议新增packagist.org

### ISSUE THREAD

**Issue by RobberPhex** [sjtug/mirror-requests#14]
**类别**：新增镜像

**镜像名**：packagist.org

**上游路径**：https://packagist.org

**镜像简介**：php的包管理网站。

**Comment by htfy96** [comment]
需要写额外的sync程序。同时还需要调查一下镜像空间大小

**Comment by RobberPhex** [comment]
我使用[pkgist](https://github.com/RobberPhex/pkgist)搭建了一个镜像，消耗如下：

redis：`used_memory_human:50.43M`
磁盘：`3.4G`

**Comment by htfy96** [comment]
@RobberPhex 这个应该只是metadata的大小吧？之包括了包信息的json而不包括包本身？还是包含了全部信息？

**Comment by RobberPhex** [comment]
* 所有的元信息都包含（zip压缩过的）
* 对于通过github、bitbucket等下载的软件包，我只在json文件中记录了反向代理的地址，并没有 在磁盘上存储包内容
* 对于自定义的git仓库，我在本地clone，并打包、保存在磁盘上
* 对于svn等，忽略，原样返回给用户

**Comment by htfy96** [comment]
等我写完毕设来搞（

**Comment by SkyZH** [comment]
I've been looking into the issue.

- [ ] testing on my server
- [ ] estimate disk IO and network IO
- [ ] PR
- [ ] frontend documentation

**Comment by SkyZH** [comment]
目前打算使用 https://github.com/Webysther/packagist-mirror 抓 Metadata。看起来 packagist 的包都是从 Github 上拉的，这个就比较难办了……

**Comment by SkyZH** [comment]
考虑折腾完 Metadata 以后再开个 issue 做全量同步。

**Comment by SkyZH** [comment]
https://packagist.mirrors.sjtug.sjtu.edu.cn 已上线，欢迎测试，不是全量同步（
