### ISSUE TITLE
请求添加Blackarch镜像

### ISSUE THREAD

**Issue by Alampdow** [sjtug/mirror-requests#146]
镜像名:Blackarch

上游路径:https://blackarch.org/blackarch/

镜像简介:
基于arch的渗透测试开发版，包含大量的渗透测试工具。与现有的arch兼容，可以充当arch的非官方用户存储库。

国内其他镜像源同步情况:

同步方法:

镜像大小:

状态追踪:

- [x] 同意同步
- [x] 同步脚本
- [x] 部署到镜像源 https://github.com/sjtug/mirror-docker-siyuan/pull/126
- [x] 首次同步成功
- [ ] 测试脚本
- [ ] 使用文档
- [x] 添加到官方源 https://github.com/BlackArch/blackarch/pull/2979

**Comment by skyzh** [comment]
已在服务器上开始首次同步。

**Comment by skyzh** [comment]
镜像已经可以在 `https://mirror.sjtu.edu.cn/blackarch/$repo/os/$arch` 访问。欢迎使用。

btw, 您可以帮助我们完善相关使用文档。 https://github.com/sjtug/portal/tree/master/content/post/mirror-help
