### ISSUE TITLE
请求添加NixOS镜像

### ISSUE THREAD

**Issue by c4dr01d** [sjtug/mirror-requests#149]
镜像名:
nix-channels

上游路径:
https://cache.nixos.org

镜像简介:
NixOS是一个函数式发行版，它使用nix包管理器，通过声明式配置文件来安装和更新，并且可以随时回滚到任意版本。
Nix旨在解决同一软件包的不同版本时间的问题，也可以使同一个软件包的多个版本共存。
[GNU Guix System](https://guix.gnu.org)的灵感来源于此。

国内其他镜像源同步情况:
[TUNA](https://mirrors.tuna.tsinghua.edu.cn/nix-channels/store)：时不时链接中断
[USTCLUG](https://mirrors.ustc.edu.can/nix-channels/store)：同TUNA

同步方法:
未知

镜像大小:
未知

状态追踪:

- [x] 同意同步
- [x] 同步脚本 https://github.com/sjtug/mirror-intel/pull/49
- [x] 部署到镜像源 https://github.com/sjtug/mirror-docker-siyuan/pull/137
- [x] 首次同步成功
- [x] 测试脚本 https://github.com/sjtug/mirror-test-scripts/pull/17
- [ ] 使用文档
- [ ] 添加到官方源

**Comment by skyzh** [comment]
由于 NixOS 的文件多而小，我们可能会先通过 mirror-intel 建立一个智能缓存，而后再尝试全量同步。

**Comment by skyzh** [comment]
我们暂时先只做 nix 的 binary cache。通过智能缓存实现，上游为 TUNA（从交大通过 IPv6 访问，链路质量比直接访问好一些）。等到该镜像足够成熟后，我们会考虑全量同步。

**Comment by skyzh** [comment]
```
nix-env -i vim -i python3 --substituters https://mirror.sjtu.edu.cn/nix-channels/store
```

欢迎大家测试使用。

**Comment by c4dr01d** [comment]
谢谢大佬，后续我会提供镜像使用方法
