### ISSUE TITLE
建议新增 MacPorts 镜像

### ISSUE THREAD

**Issue by l2dy** [sjtug/mirror-requests#15]
**类别**：新增镜像

**镜像名**：macports

**上游路径**：`rsync://rsync-origin.macports.org/macports/`，具体见<https://trac.macports.org/wiki/Mirroring>。首次同步使用pek.cn.rsync.macports.org应该会更快。

**镜像简介**：[MacPorts](https://www.macports.org/)是一个macOS上的包管理软件。镜像需要至少1.5 TB磁盘空间。

**Comment by htfy96** [comment]
我注意到上面的链接中提到MacPorts要求服务端提供rsync服务，这一点我们目前还需要一些时间考虑如何完善，因为[rsync本身的一些问题可能会导致磁盘负载较大](https://github.com/ustclug/discussions/issues/37)，我们正在考虑如何实现

**Comment by specter119** [comment]
@l2dy 岔开个话题，为啥不用brew呢？虽然brew有些激进，但是MacPorts略臃肿。

**Comment by l2dy** [comment]
@specter119 MacPorts 的包数量更多（16345，brew只有4607个），包安装到 `/opt/local` 更加独立，不会和我自己或其他软件安装到 `/usr/local` 的文件混在一起。我个人更偏向于使用需要 root 权限的包管理软件，这样更加安全也可以多用户共用。

**Comment by l2dy** [comment]
@htfy96 我邮件询问了 MacPorts 管理组，他们回复说镜像可以不提供 rsync 服务，只有 distfiles 和 packages 部分的 HTTP(S) 镜像是必需的。

**Comment by htfy96** [comment]
@l2dy 好的，这几天我会实现一下

**Comment by l2dy** [comment]
@htfy96 请问有计划增加该镜像吗？

**Comment by htfy96** [comment]
@l2dy 最近磁盘空间有点紧张，我们可能需要重新考虑下这边的情况。另外我注意到上海地区已经有了https://sha.cn.packages.macports.org/macports/ 这个镜像，不知道这个镜像是否有什么缺陷呢？

**Comment by l2dy** [comment]
mirrors.shu.edu.cn 镜像多次出现[限时访问](https://mirrors.shu.edu.cn/news/p/9103195a.html)问题，而且似乎有工作日对 IPv4 [限速](https://mirrors.shu.edu.cn/news/p/35f68b5d.html)的规定。除 IPv6 服务不太稳定外我个人倒是没有遇到太多问题。

> 接学校通知，将在2018年10月23日至2018年11月12日之间进行校园网的限时开放，开放时间为每天早上7:00至晚上22:00，在此期间仅内网可以访问。本镜像站也将受到影响，请需要在非开放时间使用的用户切换到其他镜像站，学校教职工和同学可通过VPN访问镜像站。由此给您造成的不便，我们深表歉意！

> 对校外IPv4用户进行时段限速，在正常工作日的8:00~22:00时段限速2Mb/s，其余时段不限速 [...]

**Comment by l2dy** [comment]
mirrors.shu.edu.cn 镜像目前无法访问，再次请求添加 MacPorts 镜像。

**Comment by SkyZH** [comment]
考虑这个月折腾一下（

**Comment by l2dy** [comment]
> 考虑这个月折腾一下（

ping @SkyZH

**Comment by SkyZH** [comment]
我咕了。。。

**Comment by l2dy** [comment]
Any update? @skyzh

**Comment by skyzh** [comment]
Nope... Deadlines every week, just tired getting over them :( Perhaps this winter holiday? Or you may send pull request to lug repo if you want. 👍  @l2dy

**Comment by l2dy** [comment]
> Nope... Deadlines every week, just tired getting over them :( Perhaps this winter holiday? Or you may send pull request to lug repo if you want. 👍 @l2dy

I don't see any production configuration in https://github.com/sjtug/lug. Did you mean a PR for this file? https://github.com/sjtug/mirror-docker/blob/v2/lug/config.example.yaml

**Comment by skyzh** [comment]
@l2dy You should write a script for synchronization in `lug/worker-scripts` folder, and add `shell_script` type of job with script path in config.yml . https://github.com/sjtug/mirror-docker is the repo for PR. Thank you for your contribution (in advance)!

**Comment by l2dy** [comment]
@skyzh Sorry for the delay. I have made a PR with rsync arguments suggested by the demo script from the MacPorts wiki. https://github.com/sjtug/mirror-docker/pull/36

**Comment by skyzh** [comment]
我们正在将 MacPorts 直接同步到 SJTU s3 上，预计在本月可以完成测试和上线。

**Comment by l2dy** [comment]
赞！另外建议申请成为官方镜像，这样能快速吸引用户不至于浪费存储空间。 https://trac.macports.org/wiki/Mirroring#Contactus

按上面链接的要求发送邮件到 macports-mgr 邮件列表即可（无需订阅），一般情况下 portmgr 团队会分配一个 xxx.cn.packages.macports.org 域名 CNAME 到镜像站的域名，用户通过这个 macports.org 下的域名访问。如有特殊情况可以申请直接使用镜像站域名。

**Comment by skyzh** [comment]
已经可以在 https://mirror.sjtu.edu.cn/macports 使用，欢迎测试。

> xxx.cn.packages.macports.org 域名 CNAME 到镜像站的域名

由于学校这边的限制，不太好操作。可能的方式是 macports 官方开一台服务器，专门用来 301 到 SJTUG 镜像站。

**Comment by l2dy** [comment]
> 由于学校这边的限制，不太好操作。可能的方式是 macports 官方开一台服务器，专门用来 301 到 SJTUG 镜像站。

也可以直接使用镜像站域名，之前 shu 的镜像就这样改过，只是后来下线了。

**Comment by l2dy** [comment]
参考 https://github.com/macports/macports-ports/commit/f4ce2ffb9e7c12f493ce61bf1821705d3e98658e

**Comment by PhotonQuantum** [comment]
上游很久没有回复我们的邮件。鉴于镜像本身已经工作很久，先关闭 issue 了。

**Comment by l2dy** [comment]
@PhotonQuantum 邮件可以加上抄送 l2dy [at] macports.org，我来尝试推动一下。

**Comment by PhotonQuantum** [comment]
@l2dy  思考 我之前是发送到 macports-mgr@lists.macports.org 的，这个地址对吗？

**Comment by l2dy** [comment]
> macports-mgr@lists.macports.org

地址是对的。虽然我不是 portmgr 组成员，但把我加到抄送（CC）里的话我可以尝试从其他渠道联系他们。

**Comment by PhotonQuantum** [comment]
@l2dy 感觉再发一遍邮件列表不太合适? 我之后把原邮件 forward 给你吧

**Comment by l2dy** [comment]
@PhotonQuantum MacPorts 管理团队授权我来跟进新增官方镜像站的事情了，请问 SJTUG 镜像站这边还有意愿加入成为官方镜像吗？
