### ISSUE TITLE
OpenWrt 第三方软件源

### ISSUE THREAD

**Issue by hmsjy2017** [sjtug/mirror-requests#151]
镜像名:OpenWrt 第三方软件源

上游路径: https://op.supes.top/

镜像简介: OpenWrt 第三方源和第三方编译镜像仓库，作为官方源的补充，收录了市面上大部分主流第三方插件

国内其他镜像源同步情况:无

同步方法:支持opkg，其他方式未知

镜像大小:未知

状态追踪:

- [ ] 同意同步
- [ ] 同步脚本
- [ ] 部署到镜像源
- [ ] 首次同步成功
- [ ] 测试脚本
- [ ] 使用文档
- [ ] 添加到官方源

**Comment by skyzh** [comment]
如果不提供 rsync 的话同步会比较麻烦。另外需要帮忙确认一下这个源是否存在潜在的版权问题。

**Comment by hmsjy2017** [comment]
rsync 暂时没有，正在协商中
源内的插件均搜集于GitHub，从源码编译，应该不会有版权问题

**Comment by hmsjy2017** [comment]
已支持rsync
rsync://op.supes.top/packages

**Comment by skyzh** [comment]
镜像这个源的潜在风险已经在 https://github.com/garypang13/OpenWrt/issues/266 答复。望理解。
