### ISSUE TITLE
GIMP镜像请求

### ISSUE THREAD

**Issue by zhaoguobin** [sjtug/mirror-requests#152]
镜像名:
GIMP
上游路径:
https://mirrors.ukfast.co.uk/sites/gimp.org/pub/gimp/

具体请参见 https://www.gimp.org/downloads/#mirrors

镜像简介:
GIMP是类似于Photoshop的开源图像编辑软件，国外镜像速度极其缓慢。

国内其他镜像源同步情况:
无
同步方法:

镜像大小:

状态追踪:

- [x] 同意同步
- [x] 同步脚本
- [x] 部署到镜像源 https://github.com/sjtug/mirror-docker-unified/pull/220
- [x] 首次同步成功
- [ ] 测试脚本
- [ ] 使用文档
- [ ] 添加到官方源

**Comment by skyzh** [comment]
GIMP 在各大发行版中都有，是否有必要再同步一遍？

**Comment by taoky** [comment]
> 国内其他镜像源同步情况:
> 无

https://mirrors.ustc.edu.cn/gimp/

虽然没有添加到列表里，我找个时间发邮件问问 hhh

**Comment by athrunsun** [comment]
@skyzh 至少windows的很有必要同步一下。

**Comment by skyzh** [comment]
已上线 https://mirror.sjtu.edu.cn/gimp/
