### ISSUE TITLE
Gradle镜像请求

### ISSUE THREAD

**Issue by Raw-Paradox** [sjtug/mirror-requests#154]
镜像名:
gradle distrubutions
上游路径:
https://services.gradle.org/distributions/
镜像简介:
gradle历史版本

国内其他镜像源同步情况:
无
同步方法:

镜像大小:

状态追踪:

- [x] 同意同步
- [x] 同步脚本 https://github.com/sjtug/mirror-intel/pull/51 https://github.com/sjtug/mirror-clone/pull/44
- [x] 部署到镜像源 https://github.com/sjtug/mirror-docker-unified/pull/157
- [x] 首次同步成功
- [ ] 测试脚本
- [ ] 使用文档
- [ ] 添加到官方源

**Comment by skyzh** [comment]
Related issues: https://github.com/tuna/issues/issues/955 https://github.com/ustclug/mirrorrequest/issues/279

**Comment by skyzh** [comment]
可以在 https://mirror.sjtu.edu.cn/gradle/distributions/?mirror_intel_list 浏览所有同步的版本。使用方法是将 https://services.gradle.org/distributions/ 替换为 https://mirror.sjtu.edu.cn/gradle/distributions/ 。欢迎帮助我们在 https://github.com/sjtug/portal/tree/master/content/post/mirror-help 完善使用文档。
