### ISSUE TITLE
请求添加 FreeBSD

### ISSUE THREAD

**Issue by fundon** [sjtug/mirror-requests#159]
镜像名:

上游路径:

镜像简介:

国内其他镜像源同步情况:

同步方法:

https://docs.freebsd.org/en/articles/freebsd-update-server/

镜像大小:

状态追踪:

- [ ] 同意同步
- [ ] 同步脚本
- [ ] 部署到镜像源
- [ ] 首次同步成功
- [ ] 测试脚本
- [ ] 使用文档
- [ ] 添加到官方源

**Comment by skyzh** [comment]
Related issue: https://github.com/tuna/issues/issues/16 https://github.com/ustclug/mirrorrequest/issues/2

根据其他镜像站的反馈，FreeBSD 已经不接受新的镜像服务器同步。您提供的文档要求使用 FreeBSD 系统建立 update server，似乎也不太可行。
