### ISSUE TITLE
openSUSE源同步不正常

### ISSUE THREAD

**Issue by wang1zhen** [sjtug/mirror-requests#160]
openSUSE源自昨天(2021-02-18)起就一直处于正在同步状态,无法正常更新.

**Comment by skyzh** [comment]
正在调查，感谢反馈。

**Comment by skyzh** [comment]
看起来最近有大版本的相关更新 https://en.opensuse.org/openSUSE:Roadmap ，openSUSE 的同步程序也一直在写盘，所以还需要一段时间和上游保持同步。

**Comment by skyzh** [comment]
同步了两天终于完成了🎉
