### ISSUE TITLE
openEuler官方镜像源

### ISSUE THREAD

**Issue by zhang-jian-jun** [sjtug/mirror-requests#162]
镜像名:
openEuler官方镜像源
上游路径:
rsync -av --partial --progress rsync://root@121.36.97.194/openeuler
秘钥信息: root:openeuler@1234 (只读账户)
镜像简介:
openEuler旨在通过社区合作，打造创新平台，构建支持多处理架构、统一和开放的操作系统，推动软硬件应用生态繁荣发展，官网链接：https://openeuler.org/zh/

国内其他镜像源同步情况:
清华镜像源已支持，其他还在沟通中
同步方法:
参考上游路径
镜像大小:
多个版本共600G
状态追踪:

- [x] 同意同步
- [x] 同步脚本
- [x] 部署到镜像源 https://github.com/sjtug/mirror-docker-unified/pull/178
- [x] 首次同步成功
- [ ] 测试脚本
- [ ] 使用文档
- [ ] 添加到官方源

**Comment by skyzh** [comment]
首次同步已开始。

**Comment by skyzh** [comment]
openEuler 是否有使用类似 mirrorbrain / Fedora mirror manager 的计划？我们可以提供一个专用于文件扫描的 rsync 服务来支持这一类 mirror redirector 的使用。

**Comment by skyzh** [comment]
镜像站服务器到华为云的链路质量比较差，可能需要较长的时间才能同步完成。

**Comment by TommyLike** [comment]
> openEuler 是否有使用类似 mirrorbrain / Fedora mirror manager 的计划？我们可以提供一个专用于文件扫描的 rsync 服务来支持这一类 mirror redirector 的使用。

我们有在研究mirrorbits用来监控下游的mirror状态和跳转，他支持ftp和rsync 你说的是这类服务吗？如果有那就太好了。

**Comment by skyzh** [comment]
目前已经同步了 223G，速度略微有些慢，可能还要三天左右才能完成。

另外刚刚发现 openeuler 整个目录内权限的设置似乎有些混乱。openeuler 根目录权限为 777，大部分目录为 755，还有诸如 `openeuler/openEuler-20.03-LTS/virtual_machine_img` 的目录是 700。请问我们这边是否需要原样镜像目录权限呢？

**Comment by TommyLike** [comment]
> 目前已经同步了 223G，速度略微有些慢，可能还要三天左右才能完成。
> 
> 另外刚刚发现 openeuler 整个目录内权限的设置似乎有些混乱。openeuler 根目录权限为 777，大部分目录为 755，还有诸如 `openeuler/openEuler-20.03-LTS/virtual_machine_img` 的目录是 700，可能导致 Web 服务器无法正常提供目录文件列表。请问我们这边是否需要原样镜像目录权限呢？

嗯嗯，我们已经调整了出口带宽，现在速度会快些，关于目录权限的问题，我们会尽快修复，多谢

**Comment by skyzh** [comment]
同步已完成。可以在 https://mirror.sjtu.edu.cn/openeuler/ 访问。

同时，您可以帮助我们完善相关使用文档。 https://github.com/sjtug/portal/tree/master/content/post/mirror-help

**Comment by zhang-jian-jun** [comment]
好的，会在近期完成，非常感谢！

**Comment by zhang-jian-jun** [comment]
@skyzh 非常感谢对openEuler的认可，帮助文档已提交pr: https://github.com/sjtug/portal/pull/60,麻烦处理一下，谢谢！

**Comment by zhang-jian-jun** [comment]
@skyzh 咨询openEuler镜像源限制的下载带宽是多少kb？我们这边做一个统计信息，谢谢哈

**Comment by skyzh** [comment]
> @skyzh 咨询openEuler镜像源限制的下载带宽是多少kb？我们这边做一个统计信息，谢谢哈

HTTP/HTTPS 1Gbps, Rsync 10MB/s

**Comment by zhang-jian-jun** [comment]
好的，谢谢哈

**Comment by zhang-jian-jun** [comment]
@skyzh， 咨询一下，镜像站点，有没有提供我们这边统计openEuler镜像源资源下载量的接口或者数据导出功能？

**Comment by skyzh** [comment]
> @skyzh， 咨询一下，镜像站点，有没有提供我们这边统计openEuler镜像源资源下载量的接口或者数据导出功能？

可以由镜像站管理员手动统计。邮件联系 sjtug-mirror-maintainers@googlegroups.com 即可。

**Comment by zhang-jian-jun** [comment]
好的，感谢哈

**Comment by zhang-jian-jun** [comment]
@skyzh 
非常感谢使用我们openEuler镜像源，镜像源的同步指令，不再需要用户名和密码，
直接输入：
rsync -av --partial --progress rsync://root@121.36.97.194/openeuler
即可完成镜像源的同步，
谢谢！

**Comment by skyzh** [comment]
Infra 代码已经更新，预计今天可以上线。https://github.com/sjtug/mirror-docker-unified/pull/259

**Comment by zhang-jian-jun** [comment]
好的，非常感谢哈！
