### ISSUE TITLE
请求建立 Void Linux 的镜像

### ISSUE THREAD

**Issue by ixnij** [sjtug/mirror-requests#163]
镜像名: voidlinux

上游路径: http://alpha.de.repo.voidlinux.org/ 或 http://alpha.us.repo.voidlinux.org/

镜像简介: Void 是基于 Linux 内核独立开发的通用操作系统。其特色在于一份二进制/源代码混合式包管理系统，这使得用户能快速安装、更新、移除软件，或者是借助 XBPS 源代码集合从源码直接生成软件。该发行的其他特性包括对 Raspberry Pi 单板计算机（armv6 和 armv7）的支持，每日更新的滚动式开发模式，可以选择 glibc 和 musl 作为 C 库，以及名为 runit 的原生 BSD 风格 init 系统。

国内其他镜像源同步情况: https://mirrors.tuna.tsinghua.edu.cn/voidlinux 、https://mirrors.cnnic.cn/voidlinux/ 、https://mirrors.hushan.tech:44300/voidlinux 和 https://mirrors.bfsu.edu.cn/voidlinux 。

同步方法: 通过 Rsync 。详细信息请参考: https://docs.voidlinux.org/xbps/repositories/mirrors/index.html

镜像大小:  约 1 TB

状态追踪:

- [x] 同意同步
- [x] 同步脚本 https://github.com/sjtug/mirror-clone/pull/57 https://github.com/sjtug/mirror-intel/pull/53
- [x] 部署到镜像源 https://github.com/sjtug/mirror-docker-unified/pull/194
- [x] 首次同步成功
- [x] 测试脚本 https://github.com/sjtug/mirror-test-scripts/pull/18
- [x] 使用文档 https://github.com/sjtug/portal/pull/61
- [x] 添加到官方源 https://github.com/void-linux/void-docs/pull/557

**Comment by skyzh** [comment]
由于目前镜像站的盘空间不够，我们可能考虑通过 s3 进行存储。相关的开发还在进行中。

**Comment by ixnij** [comment]
> 由于目前镜像站的盘空间不够，我们可能考虑通过 s3 进行存储。相关的开发还在进行中。

好的。请问大概要到何时可以完成？

**Comment by skyzh** [comment]
> > 由于目前镜像站的盘空间不够，我们可能考虑通过 s3 进行存储。相关的开发还在进行中。
> 
> 好的。请问大概要到何时可以完成？

今年或许可以？（逃

**Comment by ixnij** [comment]
> > > 由于目前镜像站的盘空间不够，我们可能考虑通过 s3 进行存储。相关的开发还在进行中。
> > 
> > 好的。请问大概要到何时可以完成？
> 
> 今年或许可以？（逃

知道了。谢谢。

**Comment by skyzh** [comment]
voidlinux 已经在 https://mirror.sjtu.edu.cn/voidlinux/ 上线。使用时会自动重定向到 SJTU s3。在测试一段时间后将会正式上线。

**Comment by ixnij** [comment]
> voidlinux 已经在 https://mirror.sjtu.edu.cn/voidlinux/ 上线。使用时会自动重定向到 SJTU s3。在测试一段时间后将会正式上线。

**Comment by ixnij** [comment]
> voidlinux 已经在 https://mirror.sjtu.edu.cn/voidlinux/ 上线。使用时会自动重定向到 SJTU s3。在测试一段时间后将会正式上线。

现在我可以添加镜像的用户使用方法了吗？

**Comment by skyzh** [comment]
> > voidlinux 已经在 https://mirror.sjtu.edu.cn/voidlinux/ 上线。使用时会自动重定向到 SJTU s3。在测试一段时间后将会正式上线。
> 
> 
> 
> 现在我可以添加镜像的用户使用方法了吗？

可以，欢迎发 PR 到 https://github.com/sjtug/portal/tree/master/content/post/mirror-help ，感谢～
