### ISSUE TITLE
pwsh, 7.1.3的镜像只有linux x64被同步过来了

### ISSUE THREAD

**Issue by athrunsun** [sjtug/mirror-requests#166]
截图时间：2021/3/13 16:50

如图，[7.1.3](https://mirrors.sjtug.sjtu.edu.cn/github-release/PowerShell/PowerShell/releases/download/v7.1.3/?mirror_intel_list)的只有一个文件同步成功：
![image](https://user-images.githubusercontent.com/1920454/111024903-0f905500-841c-11eb-84a8-4c918070aacf.png)

[7.1.2](https://mirrors.sjtug.sjtu.edu.cn/github-release/PowerShell/PowerShell/releases/download/v7.1.2/?mirror_intel_list)及其它版本都是正常的：
![image](https://user-images.githubusercontent.com/1920454/111024931-3484c800-841c-11eb-8a23-54532d577622.png)

这是同步出错了？

**Comment by skyzh** [comment]
镜像站到 GitHub 的连接不畅，导致 GitHub 上的内容实际上没有下载下来。后续我们会正确将同步状态显示在前端。

**Comment by skyzh** [comment]
目前已同步完成。
