### ISSUE TITLE
vscodium

### ISSUE THREAD

**Issue by athrunsun** [sjtug/mirror-requests#168]
镜像名: vscodium

上游路径: https://github.com/VSCodium/vscodium

镜像简介: https://www.oschina.net/p/vscodium

> VSCodium 是 Visual Studio Code 编辑器的一个分支。它与 VS Code 完全相同，唯一不同的是，VSCodium 不跟踪你的使用数据。这解决了你想在去掉 Microsoft 的专有代码的情况下使用 VS Code ，而你又不习惯从源代码构建它的问题。

国内其他镜像源同步情况: 暂时只找到TUNA一家：https://mirrors.tuna.tsinghua.edu.cn/github-release/VSCodium/vscodium/ ，但是访问速度堪忧。总的来说我这里TUNA镜像的访问速度比sjtu镜像慢一大截。

同步方法: 和本镜像站其它github-release下面的repo镜像一样

镜像大小:

状态追踪:

- [x] 同意同步
- [x] 同步脚本
- [x] 部署到镜像源 https://github.com/sjtug/mirror-docker-unified/compare/add-vscode
- [ ] 首次同步成功
- [ ] 测试脚本
- [ ] 使用文档
- [ ] 添加到官方源

**Comment by skyzh** [comment]
首次同步已经开始，预计明天可以访问。如果您的物理位置距离北京比较近，也可以考虑使用 BFSU 镜像。

**Comment by athrunsun** [comment]
@skyzh 好的，非常感谢！

BFSU是不是TUNA的镜像？感觉外观都一样。不过确实比TUNA快了10多ms（我在成都）。

**Comment by skyzh** [comment]
> @skyzh 好的，非常感谢！
> 
> BFSU是不是TUNA的镜像？感觉外观都一样。不过ping确实比TUNA快了10多ms（我在成都）。

是 TUNA 运营的。

**Comment by skyzh** [comment]
已上线。
