### ISSUE TITLE
AlmaLinux

### ISSUE THREAD

**Issue by hmsjy2017** [sjtug/mirror-requests#174]
镜像名: AlmaLinux

上游路径: rsync://rsync.repo.almalinux.org/almalinux/

镜像简介: AlmaLinux 是作为 CentOS 的替代品而创建的开源企业级 Linux 发行版

国内其他镜像源同步情况: 国内无镜像

同步方法: https://wiki.almalinux.org/Mirrors.html

镜像大小: 至少需要 150 GB空间，推荐 250 GB

状态追踪:

- [x] 同意同步
- [x] 同步脚本
- [x] 部署到镜像源 https://github.com/sjtug/mirror-docker-unified/pull/227
- [x] 首次同步成功
- [ ] 测试脚本
- [ ] 使用文档
- [x] 添加到官方源

**Comment by skyzh** [comment]
我们将会在近期添加该镜像。

**Comment by skyzh** [comment]
镜像源已正式上线，欢迎帮助我们添加帮助文档 https://github.com/sjtug/portal/tree/master/content/post/mirror-help

近期我们将联系将镜像加入官方源，issue 将会在添加到官方源后关闭。

**Comment by PhotonQuantum** [comment]
Added to upstream mirror list. Issue closed.
