### ISSUE TITLE
Update Homebrew bottles upstream

### ISSUE THREAD

**Issue by skyzh** [sjtug/mirror-requests#177]
https://github.com/Homebrew/brew/pull/11070

看起来 Homebrew 开始使用 GitHub Container Registry 分发 bottles 了。

**Comment by skyzh** [comment]
Deploy: https://github.com/sjtug/mirror-docker-unified/pull/231
Docs: https://github.com/sjtug/portal/commit/f9cd39cecd7944f26ed3881fae2d84ff05e579e1

**Comment by gaoyifan** [comment]
linuxbrew-bottles 可能也需要迁移

**Comment by skyzh** [comment]
> linuxbrew-bottles 可能也需要迁移

下周一定 😭😭😭😭

**Comment by skyzh** [comment]
mirror-clone 的 homebrew 部分已经重写。现在我们的 homebrew/linuxbrew bottles 都是直接从上游拉包。
