### ISSUE TITLE
archlinux 同步一致性

### ISSUE THREAD

**Issue by sticnarf** [sjtug/mirror-requests#181]
使用的源为 `mirrors.sjtug.sjtu.edu.cn`，执行 `pacman -Syyu`：

```
错误：无法从 mirrors.sjtug.sjtu.edu.cn : The requested URL returned error: 404 获取文件 'dbus-glib-0.112-1-x86_64.pkg.tar.zst'
警告：无法获取某些文件
错误：无法从 mirrors.sjtug.sjtu.edu.cn : The requested URL returned error: 404 获取文件 'libteam-1.31-3-x86_64.pkg.tar.zst'
警告：无法获取某些文件
错误：无法从 mirrors.sjtug.sjtu.edu.cn : The requested URL returned error: 404 获取文件 'sddm-0.19.0-5-x86_64.pkg.tar.zst'
警告：无法获取某些文件
错误：无法提交处理 (无法获取某些文件)
```
网站上显示同步正常：
![image](https://user-images.githubusercontent.com/17217495/115576093-c0302500-a2f5-11eb-880a-a765dbb976b6.png)

**Comment by skyzh** [comment]
已知悉，正在处理中。

**Comment by skyzh** [comment]
可能是同步时先同步了 Package index，而后再同步包导致的问题。

**Comment by skyzh** [comment]
暂时没有找到比较好的解决方案，只能祈求同步的时候上游正好 consistent :(

**Comment by sticnarf** [comment]
原来上游也是不一致的吗…

**Comment by skyzh** [comment]
> 原来上游也是不一致的吗…

在同步的过程中上游发生变动，导致最后我们这边不一致（

**Comment by skyzh** [comment]
我们会尽快切换上游，如果依然碰到问题，欢迎 reopen issue。

**Comment by sticnarf** [comment]
```
错误：无法从 mirror.sjtu.edu.cn : The requested URL returned error: 404 获取文件 'libdvdread-6.1.2-1-x86_64.pkg.tar.zst'
```

今天又遇到了问题，但现象和上一次不太一样。

在 https://mirror.sjtu.edu.cn/archlinux/extra/os/x86_64/ 展现的列表里是看得到 `libdvdread-6.1.2-1-x86_64.pkg.tar.zst` 文件的，但实际访问 404 了。列表中显示的大小也与正确的大小不符。

TUNA 源中，网页的文件列表中的大小也不正确。（过一段时间后似乎变正确了）

**Comment by skyzh** [comment]
> ```
> 
> 错误：无法从 mirror.sjtu.edu.cn : The requested URL returned error: 404 获取文件 'libdvdread-6.1.2-1-x86_64.pkg.tar.zst'
> 
> ```
> 
> 
> 
> 今天又遇到了问题，但现象和上一次不太一样。
> 
> 
> 
> 在 https://mirror.sjtu.edu.cn/archlinux/extra/os/x86_64/ 展现的列表里是看得到 `libdvdread-6.1.2-1-x86_64.pkg.tar.zst` 文件的，但实际访问 404 了。列表中显示的大小也与正确的大小不符。
> 
> 
> 
> TUNA 源中，网页的文件列表中的大小也不正确。（过一段时间后似乎变正确了）

目前的上游是 TUNA，所以应该是 TUNA 那边同步的问题。我们在考虑申请成为 tier1 镜像，以便直接从官方源同步。
