### ISSUE TITLE
openSUSE Build Service

### ISSUE THREAD

**Issue by hmsjy2017** [sjtug/mirror-requests#189]
镜像名: openSUSE Build Service

上游路径: http://download.opensuse.org/repositories/

镜像简介:  OpenSUSE Build Service (简称OBS) 是一个开放的完整的发行版开发平台，可以用来创建和发布不同硬件架构上的适合 OpenSUSE 或是其他的 Linux 发行版的开源软件。这里存放的是 openSUSE and构建服务生成的软件包和镜像。

国内其他镜像源同步情况: 中国大陆无

同步方法: rsync
方法见：https://zh.opensuse.org/index.php?title=openSUSE:镜像指南

镜像大小: 未知

状态追踪:

- [ ] 同意同步
- [ ] 同步脚本
- [ ] 部署到镜像源
- [ ] 首次同步成功
- [ ] 测试脚本
- [ ] 使用文档
- [ ] 添加到官方源

**Comment by skyzh** [comment]
我印象里这个源大小奇大用的人又不多，所以暂时搁置了。之后盘的空间足够再考虑。

**Comment by skyzh** [comment]
https://github.com/tuna/issues/issues/1111

**Comment by 02w** [comment]
可否考虑排除[`home:`](https://download.opensuse.org/repositories/home:/)目录进行同步，或者选择一部分目录来同步？`home:`下是构建服务生成的，可能不方便同步。但其它目录下包含了官方打包的一些新版本软件包，比如[`editors`](https://download.opensuse.org/repositories/editors/)目录里包含了openSUSE Leap可用的9.0版本的`vim`。

**Comment by PhotonQuantum** [comment]
请问一下这个目录下的文件有什么场景会使用到吗?

**Comment by 02w** [comment]
参见 [Semi official repositories](https://en.opensuse.org/Package_repositories#Semi_official_repositories) 和 [Popular Build Service repositories](https://en.opensuse.org/Additional_package_repositories#Popular_Build_Service_repositories) 。主要是包含了一些官方源里没有或者版本更新的软件包。

**Comment by PhotonQuantum** [comment]
经检查 OBS 即使去除了 home: 的大小仍然大得惊人，现在达到了 7.06T。考虑到 OBS 的用户量并不明确（类比 pypi 大小到达 10T+ 时我们停止了对其的全量镜像），我们决定暂时不进行同步。
