### ISSUE TITLE
Raspbian Addons

### ISSUE THREAD

**Issue by hmsjy2017** [sjtug/mirror-requests#190]
镜像名: Raspbian Addons

上游路径: 
https://osdn.net/projects/raspbian-addons/
rsync://plug-mirror.rcac.purdue.edu/osdn/storage/g/r/ra/raspbian-addons/
（上游已切换至 OSDN）

镜像简介: Raspbian 额外软件包

国内其他镜像源同步情况: TUNA (in OSDN)

同步方法: rsync

镜像大小: ~4.4 GB

状态追踪:

- [x] 同意同步
- [x] 同步脚本
- [x] 部署到镜像源 https://github.com/sjtug/mirror-docker-unified/pull/261
- [x] 首次同步成功
- [ ] 测试脚本
- [ ] 使用文档
- [ ] 添加到官方源

**Comment by hmsjy2017** [comment]
@skyzh 可以在镜像时排除有重分发问题的软件包吗？

**Comment by hmsjy2017** [comment]
https://github.com/chunky-milk/raspbian-addons/issues/5

**Comment by hmsjy2017** [comment]
@skyzh 重分发问题应该已经解决了
https://github.com/chunky-milk/raspbian-addons/issues/5#issuecomment-838766546

**Comment by hmsjy2017** [comment]
@skyzh 目前看来仓库里没有任何有重分发问题的软件。都是开源可分发的。

**Comment by skyzh** [comment]
> @skyzh 目前看来仓库里没有任何有重分发问题的软件，都是开源可分发的。

观望.png

**Comment by skyzh** [comment]
我觉得 ok，这两天加上
