### ISSUE TITLE
codesandbox.io的代理mirror

### ISSUE THREAD

**Issue by alenandry** [sjtug/mirror-requests#192]
镜像名:
codesandbox.io
上游路径:
codesandbox.io
镜像简介:
国内访问 很慢

国内其他镜像源同步情况:

同步方法:

镜像大小:

状态追踪:

- [ ] 同意同步
- [ ] 同步脚本
- [ ] 部署到镜像源
- [ ] 首次同步成功
- [ ] 测试脚本
- [ ] 使用文档
- [ ] 添加到官方源

**Comment by skyzh** [comment]
快速看了一下，codesandbox 应该不属于软件源的范畴。如有问题，可以重新打开 issue。

**Comment by alenandry** [comment]
就是在线写代码，很方便的工具 自动加载库，代码可以托管到github上
