### ISSUE TITLE
请求增加 conda 镜像 dglteam channel

### ISSUE THREAD

**Issue by specter119** [sjtug/mirror-requests#198]
镜像名:
conda dglteam channel

上游路径:
https://conda.anaconda.org/dglteam

镜像简介:
当前图神经网络应用最广泛的数据框架，有pytorch/tensorflow/mxnet的接口。

国内其他镜像源同步情况:

[tuna dglteam](https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/dglteam/)

同步方法:

镜像大小:

状态追踪:

- [x] 同意同步
- [x] 同步脚本 https://github.com/sjtug/mirror-docker-unified/pull/268
- [x] 部署到镜像源
- [x] 首次同步成功
- [x] 测试脚本
- [x] 使用文档
- [ ] 添加到官方源

**Comment by skyzh** [comment]
本周应该可以加上。

**Comment by specter119** [comment]
感谢

**Comment by skyzh** [comment]
同步已经完成，现在应该可以正常使用了。

**Comment by specter119** [comment]
@skyzh 感谢，已用上。
