### ISSUE TITLE
请求添加OpenBSD源

### ISSUE THREAD

**Issue by walkingstart** [sjtug/mirror-requests#199]
镜像名:OpenBSD

上游路径:https://cdn.openbsd.org/pub/OpenBSD/

镜像简介:OpenBSD镜像

国内其他镜像源同步情况:

同步方法:

镜像大小:

状态追踪:

- [x] 同意同步
- [x] 同步脚本
- [x] 部署到镜像源 https://github.com/sjtug/mirror-docker-unified/pull/269
- [x] 首次同步成功
- [ ] 测试脚本
- [ ] 使用文档
- [ ] 添加到官方源

**Comment by skyzh** [comment]
我们会在近期加上。

**Comment by skyzh** [comment]
https://mirror.sjtu.edu.cn/OpenBSD/ 已经可以访问，欢迎帮我们添加使用文档。
