### ISSUE TITLE
建议新增 Homebrew 镜像

### ISSUE THREAD

**Issue by AlexaraWu** [sjtug/mirror-requests#20]
**类别**：新增镜像

**镜像名**：`homebrew-core.git` `homebrew-bottles` `homebrew-cask.git`

**上游路径**：
  * `https://github.com/Homebrew/homebrew-core.git`
  * `https://homebrew.bintray.com/`
  * `https://github.com/Homebrew/homebrew-cask.git`

**镜像简介**：[Homebrew](https://brew.sh/) 是一个 macOS 上的包管理软件。
  * `homebrew-core.git` Homebrew 软件包描述文件；
  * `homebrew-bottles` 预编译的 Homebrew 软件包；
  * `homebrew-cask.git` Homebrew Cask 描述文件，提供 macOS 应用和大型二进制文件。

**Comment by htfy96** [comment]
这项工作需要搭建git service

**Comment by htfy96** [comment]
已添加，欢迎测试

更换homebrew-core源：
```
cd "$(brew --repo)/Library/Taps/homebrew/homebrew-core"
git remote set-url origin https://mirrors.sjtug.sjtu.edu.cn/git/homebrew-core.git
```

更换homebrew-cask源：
```
cd "$(brew --repo)"/Library/Taps/caskroom/homebrew-cask
git remote set-url origin https://mirrors.sjtug.sjtu.edu.cn/git/homebrew-cask.git
```

更换brew-bottles源：
```
export HOMEBREW_BOTTLE_DOMAIN=https://mirrors.sjtug.sjtu.edu.cn/homebrew-bottles
```

之后运行：
```
brew update
```
第一次update可能较慢，之后会快很多

**Comment by htfy96** [comment]
应该可用了……只是不知道为啥有点慢……clone的时候会`git-upload-pack -> git pack-objects --revs --thin --stdout --progress --delta-base-offset`卡10s左右，100% CPU占用 + 0 disk I/O。如果有知道的dalao欢迎告诉一声怎么解决……

**Comment by htfy96** [comment]
利用[Git的bitmap特性](http://www.ruanyifeng.com/blog/2015/09/git-bitmap.html)加速了git clone，目前可以做到秒出branch了

**Comment by htfy96** [comment]
请问可以正常使用了吗？如果可以我就关闭这个issue了

**Comment by AlexaraWu** [comment]
可以用了～

**Comment by AlexaraWu** [comment]
漏了一个 Homebrew 自身的仓库，请求添加。

**镜像名**：`brew.git`

**上游路径**：
* `https://github.com/Homebrew/brew.git`

**镜像简介**：
* Homebrew 源代码仓库。

**Comment by htfy96** [comment]
已添加，等待1～2小时后同步……

**Comment by htfy96** [comment]
同步完成，应该可以使用了

**Comment by AlexaraWu** [comment]
请求添加 Homebrew 安装脚本仓库。

**镜像名**：`Homebrew/install`

**上游路径**：
* `https://github.com/Homebrew/install.git`

**镜像简介**：
* Homebrew (un)installer

**Comment by skyzh** [comment]
近几天会添加。

**Comment by skyzh** [comment]
Available at https://mirror.sjtu.edu.cn/git/homebrew-install.git/
