### ISSUE TITLE
ClearLinux

### ISSUE THREAD

**Issue by liu-zw** [sjtug/mirror-requests#202]
镜像名:
ClearLinux镜像
上游路径:
https://update.clearlinux.org/
镜像简介:
ClearLinux 是 intel 构建的轻量快速滚动更新的 Linux 发行版，特别为 Intel 平台优化

国内其他镜像源同步情况:

同步方法:

镜像大小:

状态追踪:

- [ ] 同意同步
- [ ] 同步脚本
- [ ] 部署到镜像源
- [ ] 首次同步成功
- [ ] 测试脚本
- [ ] 使用文档
- [ ] 添加到官方源

**Comment by skyzh** [comment]
Hi, 你提供的网址似乎无法打开。

**Comment by liu-zw** [comment]
抱歉，它的中文文档过期了
现在的上游路径是https://cdn.download.clearlinux.org/
(⊙o⊙)

**Comment by PhotonQuantum** [comment]
由于上游明确不支持镜像，我们无法提供服务

https://community.clearlinux.org/t/how-to-build-my-own-mirror-sever/1996/8
