### ISSUE TITLE
部分文件大小的显示有误

### ISSUE THREAD

**Issue by snow10k** [sjtug/mirror-requests#207]
少数页面比如 [ubuntu](https://mirror.sjtu.edu.cn/ubuntu-cd/20.04/) 的文件大小有误：
![2](https://user-images.githubusercontent.com/86308328/129047402-ee49d5a8-bb3e-4ecb-b3e2-59cc03eedd8e.png)

但是部分页面比如 [kali-image](https://mirrors.sjtug.sjtu.edu.cn/kali-images/kali-weekly/) 的显示并没有问题：
![1](https://user-images.githubusercontent.com/86308328/129047811-43ebce19-5058-4129-9240-696bbe523654.png)

**Comment by skyzh** [comment]
Hi, 这是因为 Caddy Web Server 处理符号链接时只显示符号链接本身的大小。我们应该不会主动修复这个 bug。如有需求，可以和 Caddy 上游反映。

**Comment by snow10k** [comment]
感谢！
