### ISSUE TITLE
Debian Ports

### ISSUE THREAD

**Issue by hmsjy2017** [sjtug/mirror-requests#209]
镜像名: Debian Ports

上游路径: https://www.ports.debian.org/

镜像简介: Debian 非官方支持架构的软件源，包含的架构有alpha、hurd-i386、hppa、ia64、kfreebsd-amd64、kfreebsd-i386、m68k、ppc64、powerpc、riscv64、sh4sparc64、x32

国内其他镜像源同步情况: 腾讯

同步方法:
rsync://ftp.de.debian.org/debian-ports/
rsync://ftp.kr.debian.org/debian-ports/
详见：https://www.ports.debian.org/mirrors

镜像大小: 未知，软件包较少，估计不太大

状态追踪:

- [x] 同意同步
- [x] 同步脚本
- [x] 部署到镜像源 https://github.com/sjtug/mirror-docker-unified/pull/281
- [x] 首次同步成功
- [ ] 测试脚本
- [ ] 使用文档
- [ ] 添加到官方源

**Comment by skyzh** [comment]
Hi, 我们将会在近期加上。

**Comment by skyzh** [comment]
看了一眼，似乎现在镜像并不是太多…… Debian ports 在什么情况下会被使用呢？

**Comment by hmsjy2017** [comment]
@skyzh 比如我要在 riscv64开发版上编译软件，就会用到riscv64的源。

**Comment by skyzh** [comment]
先从上游拉了一下文件列表，看起来一点也不小，有一个 T……

```
Number of files: 1,154,374 (reg: 958,926, dir: 195,439, link: 9)
Number of created files: 0
Number of deleted files: 0
Number of regular files transferred: 0
Total file size: 1,677,871,878,228 bytes
Total transferred file size: 0 bytes
Literal data: 0 bytes
Matched data: 0 bytes
File list size: 29,892,072
File list generation time: 0.001 seconds
File list transfer time: 0.000 seconds
Total bytes sent: 225,142
Total bytes received: 45,195,478
```

**Comment by hmsjy2017** [comment]
所以...服务器空间够吗？

**Comment by skyzh** [comment]
> 所以...服务器空间够吗？

够的，但感觉同步了以后利用率不会高 😂😂

**Comment by hmsjy2017** [comment]
所以...可以部分同步吗？比如只同步 riscv64 的源

**Comment by skyzh** [comment]
> 所以...可以部分同步吗？比如只同步 riscv64 的源

可以帮忙提供一个 rsync 需要过滤的文件列表吗？类似 `--exclude "xxxx"` 的参数形式。

**Comment by hmsjy2017** [comment]
--exclude "pool-alpha" --exclude "pool-hppa" --exclude "pool-hurd-i386" --exclude "pool-ia64" --exclude "pool-kfreebsd-amd64" --exclude "pool-kfreebsd-i386" --exclude "pool-m68k" --exclude "pool-powerpc" --exclude "pool-ppc64" --exclude "pool-sh4" --exclude "pool-sparc64" --exclude "pool-x32"

**Comment by hmsjy2017** [comment]
dists 目录似乎不太好过滤🤣

**Comment by skyzh** [comment]
在同步了，预计一两天可以完成。

**Comment by hmsjy2017** [comment]
写好了，列表很长

**Comment by skyzh** [comment]
> 等等，dists目录下的也要过滤呢，刚写完

那个很小，已经同步完了

**Comment by hmsjy2017** [comment]
> 那个很小，已经同步完了

什么时候上线？

**Comment by skyzh** [comment]
明天一定！

**Comment by skyzh** [comment]
debian-ports 已经可以在 https://mirror.sjtu.edu.cn/debian-ports/ 访问，欢迎帮助我们添加 mirror-help 文档。
