### ISSUE TITLE
bioconductor镜像无法使用

### ISSUE THREAD

**Issue by huangliang0828** [sjtug/mirror-requests#214]
根据options(BioC_mirror="https://mirrors.sjtug.sjtu.edu.cn/bioconductor")设置了启动项，但是使用安装时，还是提示错误
Warning: unable to access index for repository https://mirrors.sjtug.sjtu.edu.cn/bioconductor/packages/3.12/bioc/src/contrib:
  cannot open URL 'https://mirrors.sjtug.sjtu.edu.cn/bioconductor/packages/3.12/bioc/src/contrib/PACKAGES'
在网页中确实打不开该网址 https://mirrors.sjtug.sjtu.edu.cn/bioconductor/packages，
This XML file does not appear to have any style information associated with it. The document tree is shown below.
<Error>
<Code>AccessDenied</Code>
<BucketName>899a892efef34b1b944a19981040f55b-oss01</BucketName>
<RequestId>tx00000000000000aefdee9-0061270c1a-41d101b-zone-00864d</RequestId>
<HostId>41d101b-zone-00864d-zg-00864d</HostId>
</Error>

**Comment by PhotonQuantum** [comment]
现在我们应该可以通过 rsync-sjtug 正确地支持同步到对象存储，近期会修复
