### ISSUE TITLE
emacs-elpa failed to sync

### ISSUE THREAD

**Issue by lyjdwh** [sjtug/mirror-requests#216]
目前上游 [emacs-china](https://elpa.emacs-china.org/) 已经不再提供 rsync 同步方式，且将镜像迁移到了新的服务器，见 https://github.com/d12frosted/elpa-mirror

相关内容讨论见 https://github.com/emacs-china/elpa/issues/58

**Comment by skyzh** [comment]
Thanks! 正在和 emacs-china 沟通，看看能不能提供 rsync。不行的话可能要比较长时间才能恢复服务了（

https://github.com/emacs-china/elpa/issues/59

**Comment by zilongshanren** [comment]
目前我重新设置了一下，看看是否ok了？

**Comment by zilongshanren** [comment]
不过新的镜像是一个git仓库，在同步的时候需要添加下 exclude=.git

**Comment by skyzh** [comment]
> 目前我重新设置了一下，看看是否ok了？

服务器上的配置似乎有点问题，我还在调查中 :(

**Comment by skyzh** [comment]
> 目前我重新设置了一下，看看是否ok了？

镜像站上似乎依然没法同步（虽然我本地可以正常连接），正在调查中 :(

**Comment by skyzh** [comment]
感谢各位，现在已经可以同步了。
