### ISSUE TITLE
anaconda channel: deepmodeling

### ISSUE THREAD

**Issue by njzjz** [sjtug/mirror-requests#218]
镜像名: Deep Modeling

上游路径:
http://conda.anaconda.org/deepmodeling/

镜像简介: 
我们（@amcadmus、我以及[Deep Modeling](https://github.com/deepmodeling)其他成员）是总部位于北京的开源社区，致力于将机器学习、物理建模和高性能计算平台等工具结合起来，重新定义科学计算的未来。我们通过anaconda channel分发编译好的[DeePMD-kit](https://github.com/deepmodeling/deepmd-kit)程序，国内几乎所有顶尖高校都有使用我们软件的课题组。

我们希望上海交大镜像能加入deepmodeling channel。

国内其他镜像源同步情况:
清华镜像已收录： https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/deepmodeling

同步方法: 同anaconda的其它镜像

镜像大小: 由于anaconda的限制，同一时间不会超过3GB，如果即将超过会删掉旧的package

状态追踪:

- [x] 同意同步
- [ ] 同步脚本
- [ ] 部署到镜像源
- [ ] 首次同步成功
- [ ] 测试脚本
- [ ] 使用文档
- [ ] 添加到官方源

**Comment by skyzh** [comment]
Hi, 我们将在近期添加。
