### ISSUE TITLE
请求增加 MongoDB 官方源镜像

### ISSUE THREAD

**Issue by specter119** [sjtug/mirror-requests#22]
**类别**：新增镜像

**镜像名**：MongoDB

**上游路径**：https://repo.mongodb.org/

**镜像简介**：广泛应用的非关系型数据库，但是官方源访问经常出问题。

[清华](https://mirror.tuna.tsinghua.edu.cn/help/mongodb/), [上大](https://mirrors.shuosc.org/mongodb/) 已有镜像。

**Comment by SkyZH** [comment]
同时有一个 llvm.git，可以顺便一起做了。

**Comment by specter119** [comment]
@SkyZH 等下，MongoDB 的 upstream 不是 git 啊，是编译好的包。

**Comment by SkyZH** [comment]
ok，之前看错了。。。这个月应该可以上线（

**Comment by specter119** [comment]
感觉最近硬盘很够啊，快顺手加了 Mongo。

**Comment by skyzh** [comment]
好好好 行行行 主要是没有 yum / apt 的同步脚本（

**Comment by PhotonQuantum** [comment]
> 好好好 行行行 主要是没有 yum / apt 的同步脚本（

快搓 pr 别摸了 (催促

**Comment by skyzh** [comment]
这个 repo 可以直接用 aws tools 同步。预计一周可以上线。

**Comment by skyzh** [comment]
我们进行了第一次同步，目前文件应该是完整的，但是还有一点问题需要解决。地址是 `https://mirrors.sjtug.sjtu.edu.cn/mongodb/`

**Comment by specter119** [comment]
泪目，我没啥需求了。(有需求的接着上
