### ISSUE TITLE
termux

### ISSUE THREAD

**Issue by proItheus** [sjtug/mirror-requests#223]
镜像名:termux

上游路径: http://apt.termux.com

镜像简介:一个android上的终端模拟器，无需root，有apt包管理，可以用python,nodejs等，非常强大。
~~这样Android用户就有理由上镜像站了~~

国内其他镜像源同步情况:TUNA USTC

同步方法:ipfs? [tuna/issues#1207](https://github.com/tuna/issues/issues/1207) [termux/termux-packages#6348](https://github.com/termux/termux-packages/issues/6348)

镜像大小:

状态追踪:

- [ ] 同意同步
- [ ] 同步脚本
- [ ] 部署到镜像源
- [ ] 首次同步成功
- [ ] 测试脚本
- [ ] 使用文档
- [ ] 添加到官方源

**Comment by skyzh** [comment]
虽然很想加，但下次一定！

**Comment by Spz2022** [comment]
不不不，必须一定

**Comment by PhotonQuantum** [comment]
已经开始初期同步，在完成同步后可能需要通知上游收录
