### ISSUE TITLE
GHCup 的安装脚本执行返回 403

### ISSUE THREAD

**Issue by muji0701** [sjtug/mirror-requests#225]
按照` https://mirror.sjtu.edu.cn/docs/ghcup `提供的步骤，安装GHCup 
执行 `curl --proto '=https' --tlsv1.2 -LsSf https://mirror.sjtu.edu.cn/ghcup/script/install.sh | sh `后
```
curl: (22) The requested URL returned error: 403 Forbidden
"curl -Lf https://mirror.sjtu.edu.cn/ghcup/packages/~ghcup/0.1.17.2/x86_64-linux-ghcup-0.1.17.2" failed!
```
排查后发现，镜像站上没有version=0.1.17.2，更改脚本中的 `ghver="0.1.17.2"` => `ghver="0.1.17.1"`  解决问题

**Comment by skyzh** [comment]
s3 存储如果发现文件不存在，默认返回 403 而非 404。ghcup 更新较快，可能无法同步最新版本。

cc @PhotonQuantum

**Comment by PhotonQuantum** [comment]
Seems like a bug. I'll look into it later.
