### ISSUE TITLE
2021.10.21 conda pytorch channel 疑似同步不正常

### ISSUE THREAD

**Issue by specter119** [sjtug/mirror-requests#227]
OS: win10 pro

现象:
镜像站显示同步失败
更新包含 pytorch channel 的环境时，pytorch channel 内某些包，无法完整下载，以致 md5sum 校验失败。
所涉及的文件至少包含：

```
pytorch-mutex-1.0-cuda.tar.bz2
pytorch-1.10.0-py3.8_cuda11.3_cudnn8_0.tar.bz2
pytorch-1.10.0-py3.9_cuda11.3_cudnn8_0.tar.bz2
```

P.S.: conda-forge channel 应未受影响，main 不确定，现在不用了。

**Comment by skyzh** [comment]
Thanks for report; 我们会尽快修复。

**Comment by specter119** [comment]
同步已经正常，感谢。
