### ISSUE TITLE
Arch好像也没加入官方源列表？

### ISSUE THREAD

**Issue by specter119** [sjtug/mirror-requests#23]
**类别**：Bug

Arch 未加入官方源列表

**Comment by htfy96** [comment]
加入了，在 https://www.archlinux.org/mirrors/status/ 搜索 mirrors.sjtug 可以看到。如果本地没找到的话可以看下`/etc/pacman.d/mirrorlist.pacnew`

**Comment by specter119** [comment]
我打开包看了下，是有的，但是不给我本地的 /etc/pacman.d/mirrorlist 更新，而且我的 mirrorlist 里面很乱，生成的时间是iso镜像的时间，觉得应该是arch的坑。
