### ISSUE TITLE
fedora-ostree 镜像源无法使用

### ISSUE THREAD

**Issue by lumingzh** [sjtug/mirror-requests#231]
运行环境：在 vbox 中安装的 fedora silverblue 34
网络环境：河南地区的中国移动宽带
已手动编辑 /etc/ostree/remotes.d/fedora.conf 文件，开始的一段时间（大概9月份）可以正常使用，但是最近一段时间基本与断网状态没有区别，最严重的时候连检查更新都做不到，好一点的情况下载速度也只有几个KB，完全无法使用。

![2021-10-28 20-13-14 的屏幕截图](https://user-images.githubusercontent.com/89230850/139253128-0503aae9-98f0-4b4d-9f7b-314b3c93b24d.png)

**Comment by skyzh** [comment]
ostree 镜像源是智能缓存，如果请求的文件没有其他用户下载过，慢是正常的。之后可以看看有没有更好的解决方案。

**Comment by lumingzh** [comment]
> ostree 镜像源是智能缓存，如果请求的文件没有其他用户下载过，慢是正常的。之后可以看看有没有更好的解决方案。

我看默认配置文件里contenturl这一行的链接打开是个镜像源网址列表，但是列表只有一项，不知道具体是个什么原理，和传统镜像源有何区别。

**Comment by skyzh** [comment]
> > ostree 镜像源是智能缓存，如果请求的文件没有其他用户下载过，慢是正常的。之后可以看看有没有更好的解决方案。
> 
> 
> 
> 我看默认配置文件里contenturl这一行的链接打开是个镜像源网址列表，但是列表只有一项，不知道具体是个什么原理，和传统镜像源有何区别。

SJTUG 没有把 Fedora ostree 上所有的内容同步下来，而是按需缓存资源。可以理解成一个高级的反向代理。

**Comment by lumingzh** [comment]
> > > ostree 镜像源是智能缓存，如果请求的文件没有其他用户下载过，慢是正常的。之后可以看看有没有更好的解决方案。
> > 
> > 
> > 我看默认配置文件里contenturl这一行的链接打开是个镜像源网址列表，但是列表只有一项，不知道具体是个什么原理，和传统镜像源有何区别。
> 
> SJTUG 没有把 Fedora ostree 上所有的内容同步下来，而是按需缓存资源。可以理解成一个高级的反向代理。

最近使用没有再遇到这个问题，不知道是否是你们做了什么改动，还是有其它原因？

**Comment by skyzh** [comment]
没有。可能是其他人在你使用之前已经下载了需要的数据。

**Comment by lumingzh** [comment]
囧，看来第一个人总是受害者，哈哈。
