### ISSUE TITLE
about the mirrors synchronize

### ISSUE THREAD

**Issue by dongzhe1208** [sjtug/mirror-requests#234]
Good afternoon!Our company is a IDC Service provider in Beijing.We want to synchronize some mirrors with high user frequency to my station. Can I provide a list of the top ten mirrors in the higher frequency of your station?

**Comment by skyzh** [comment]
Qt, Fedora, CentOS, CTAN, manjaro, openeuler, archlinux, linuxmint-cd, zorinos-isos, CRAN.

Please email us for personal inqueries next time. This repo is for bug reports, not for discussions.
