### ISSUE TITLE
 申请添加 packman 镜像

### ISSUE THREAD

**Issue by douglarek** [sjtug/mirror-requests#236]
镜像名: packman （多媒体编解码源）

上游路径: https://ftp.gwdg.de/pub/linux/misc/packman

镜像简介:

国内其他镜像源同步情况:

国内：https://zh.opensuse.org/Packman/%E9%95%9C%E5%83%8F%E5%88%97%E8%A1%A8
希望 sjtu 添加是因为 sjtu 作为现代镜像服务非常快速稳定，非常吼，作为北方联通用户依然能感受到。

同步方法:

上面的 gwdg 是德国主站不确定是否可以 rsync（优先用这个吧），如果不能请尝试：
rsync://mirror.karneval.cz/packman/

<br class="Apple-interchange-newline">

镜像大小: 150G

状态追踪:

- [x] 同意同步
- [x] 同步脚本
- [x] 部署到镜像源
- [x] 首次同步成功
- [ ] 测试脚本
- [ ] 使用文档
- [x] 添加到官方源

**Comment by PhotonQuantum** [comment]
镜像已经上线

**Comment by douglarek** [comment]
> 镜像已经上线

多谢迟来的同步，已转战 manjaro。
