### ISSUE TITLE
julia-releases failed to sync

### ISSUE THREAD

**Issue by skyzh** [sjtug/mirror-requests#238]
```
Stderr: download failed: s3://julialang2/juliaup/RELEASECHANNELVERSION to ../mnt/julia-releases/juliaup/RELEASECHANNELVERSION An error occurred (AccessDenied) when calling the GetObject operation: Access Denied
download failed: s3://julialang2/juliaup/RELEASEPREVIEWCHANNELVERSION to ../mnt/julia-releases/juliaup/RELEASEPREVIEWCHANNELVERSION An error occurred (AccessDenied) when calling the GetObject operation: Access Denied
```

cc @johnnychen94 would you please take a look? Thanks!

**Comment by johnnychen94** [comment]
Unsure of this, maybe @davidanthoff knows more detail here. Ping @staticfloat for a permission fix

**Comment by davidanthoff** [comment]
What is the context here?

**Comment by skyzh** [comment]
> What is the context here? 

We are running an open-source software mirror that accelerates downloads of Julia lang in China. And it seems that some misconfiguration on Julia binary's s3 bucket made us unable to sync data to our server any more.

**Comment by davidanthoff** [comment]
I think you probably want to ignore everything in `julialang2/juliaup`, that is stuff I'm using for `juliaup` that won't make any sense in a replication setting.

**Comment by johnnychen94** [comment]
From the status in https://mirrors.sjtug.sjtu.edu.cn/ this issue seems to be fixed already

**Comment by johnnychen94** [comment]
I think we still need to fix this permission issue if we want to use the mirror sites as the juliaup server. Currently, because the version record files are out of sync, it would downgrade juliaup to a "broken" version:

```console
$ JULIAUP_SERVER=https://mirrors.bfsu.edu.cn/julia-releases juliaup self update
Checking for self-updates
Found new version 1.5.30 on channel release.
Updated Juliaup to version 1.5.30.
```

As the time of writing, the latest version is `1.5.38`

```julia
$ curl -fsSL https://julialang-s3.julialang.org/juliaup/RELEASECHANNELVERSION
1.5.38
```

@skyzh I see USTC mirror keeps the latest record, and SJTUG and BFSU don't. Is this because the `s3 sync` excludes these files?

**Comment by skyzh** [comment]
I'll take a look this weekend...
