### ISSUE TITLE
建議新增Parrot镜像

### ISSUE THREAD

**Issue by Franklyzzm** [sjtug/mirror-requests#24]
**类别**：
新增镜像

**镜像名**：
Parrot
**上游路径**：
rsync://archive.parrotsec.org:/parrot
參考頁面：https://docs.parrotsec.org/mirrors-list
**镜像简介**：
The Parrot System
Parrot is a GNU/Linux distribution based on Debian Testing and designed with Security, Development and Privacy in mind.
It includes a full portable laboratory for security and digital forensics experts, but it also includes all you need to develop your own software or protect your privacy while surfing the net.

**Comment by htfy96** [comment]
done
