### ISSUE TITLE
git/brew.git mirror didn't sync tags

### ISSUE THREAD

**Issue by soliujing** [sjtug/mirror-requests#242]
Not in sync with tags from github upstream, which resulted no update via 'brew update', it check tags as version control.

**Comment by skyzh** [comment]
From the GitLab page https://git.sjtu.edu.cn/sjtug/brew/, all tags seem to be available?

**Comment by skyzh** [comment]
I see, new tags are not synchronized. I'll propose a fix soon.

**Comment by soliujing** [comment]
@skyzh You bet.   
Now https://github.com/Homebrew/brew/tags listed 200+ with latest 3.3.6.
https://git.sjtu.edu.cn/sjtug/brew/-/tags got stuck at 2.6.2.

**Comment by skyzh** [comment]
I have manually added the tags, so the tags are up-to-date for now. We will fix the sync script later.

**Comment by skyzh** [comment]
Should be fixed in https://github.com/sjtug/mirror-docker-unified/pull/312, thanks for your patience!
