### ISSUE TITLE
[flatpak] 可以再帮助文档上提上一句导入gpg 的说明

### ISSUE THREAD

**Issue by q962** [sjtug/mirror-requests#243]
只使用 `sudo flatpak remote-modify flathub --url=https://mirror.sjtu.edu.cn/flathub` 并不能工作，提示GPG public key not found

~~在 deepin 的 1.2.5 中没有问题~~
~~在 arch 的1.12.2 上有问题~~
> 事实上都有问题

可以多给点提示
```
wget https://mirror.sjtu.edu.cn/flathub/flathub.gpg
flatpak remote-modify --gpg-import=flathub.gpg flathub
```

**Comment by skyzh** [comment]
Thanks! 方便发个 PR 吗？

https://github.com/sjtug/portal/tree/master/content/post/mirror-help

**Comment by q962** [comment]
好，我试试

**Comment by skyzh** [comment]
Thanks!
