### ISSUE TITLE
下载 RPM 源码包时提示元数据下载失败 

### ISSUE THREAD

**Issue by inoton** [sjtug/mirror-requests#244]
## OS
Fedora Linux 35 x86_64

## 执行的命令
比如，
```
dnf download gedit --source
```

## 错误提示
```
enabling fedora-source repository
enabling updates-source repository
Fedora 35 - Updates Source                  0.0  B/s |   0  B     00:00    
Errors during downloading metadata for repository 'updates-source':
  - Status code: 404 for https://mirror.sjtu.edu.cn/fedora/linux/updates/35/Everything/SRPMS/repodata/repomd.xml (IP: 111.186.58.212)
Error: Failed to download metadata for repo 'updates-source': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried
```

看到交大镜像是[存在 SRPM 源的](https://mirror.sjtu.edu.cn/fedora/linux/updates/35/Everything/source/tree/Packages/)，另外已经查看过 Fedora 交大源已经完成全部更新；造成这个错误目前不知道是什么原因。

## 一处针对 fedora 文档的建议
避免类似下面链接地址中间的 `metalink` 部分被替换，
```
metalink=https://mirrors.fedoraproject.org/metalink?repo=fedora-$releasever&arch=$basearch

```

说明档中 https://mirror.sjtu.edu.cn/docs/fedora/linux 使用下面的代码效果更佳：
```
sed -e 's/^metalink=/#metalink=/g' -e 's|^#baseurl=http://download.example/pub/|baseurl=https://mirror.sjtu.edu.cn/|g' -i.bak /etc/yum.repos.d/<需要替换的文件>
```

原来的代码：
```
sed -e 's/metalink/#metalink/g' -e 's|#baseurl=http://download.example/pub/|baseurl=https://mirror.sjtu.edu.cn/|g' -i.bak /etc/yum.repos.d/<需要替换的文件>
```

**Comment by skyzh** [comment]
Thanks! 方便帮我们更新一下文档吗？https://github.com/sjtug/portal/tree/master/content/post/mirror-help

**Comment by inoton** [comment]
> Thanks! 方便帮我们更新一下文档吗？

更新文档不会弄，git 的操作目前不熟悉（ 或者意思是说 issue 复制到 mirror-help 中？先行复制过去 ;P

#### 原因找到了：
repo 中的内容是这样：
```
baseurl=https://mirror.sjtu.edu.cn/fedora/linux/updates/$releasever/Everything/SRPMS/
```
正常访问的地址是：
```
baseurl=https://mirror.sjtu.edu.cn/fedora/linux/updates/$releasever/Everything/source/tree/Packages/
```
可能需要创建一个软链接

**Comment by skyzh** [comment]
我们是从上游 1v1 同步的，上游没有的内容我们应该也没有，所以怀疑我们现在用的上游没有做 symbolic link（

**Comment by skyzh** [comment]
> 更新文档不会弄，git 的操作目前不熟悉（ 或者意思是说 issue 复制到 mirror-help 中？先行复制过去 ;P

直接在 fedora.md 里面点击编辑按钮发 PR 就可以了 🤣 实在不行我也可以来改

**Comment by inoton** [comment]
> > 更新文档不会弄，git 的操作目前不熟悉（ 或者意思是说 issue 复制到 mirror-help 中？先行复制过去 ;P
> 
> 直接在 fedora.md 里面点击编辑按钮发 PR 就可以了 rofl 实在不行我也可以来改

好，已经操作过了
