### ISSUE TITLE
Kali 以及 Kali-images 已经连续几天同步异常

### ISSUE THREAD

**Issue by okrc** [sjtug/mirror-requests#245]
> ![image](https://user-images.githubusercontent.com/29057533/145571553-ed2c5c1d-85e3-49ef-ba9e-d890ee79cfe6.png)

网页连续几天显示正在同步，没有提示成功或者失败。
> ![image](https://user-images.githubusercontent.com/29057533/145571832-62636f2e-f7f5-4fc1-80cf-97d89f954c2d.png)

望解决 🐛

**Comment by skyzh** [comment]
Hi, 我们已经切换了上游，稍后应该就能完成同步。如有问题，请重开 issue。感谢～
