### ISSUE TITLE
pypi meteva包版本异常

### ISSUE THREAD

**Issue by wohenbushuang** [sjtug/mirror-requests#246]
你好，我今天重装conda环境并配置全局sjtug源，安装了`meteva`包，尝试包文档里的函数时一直报错不存在，后来才发现安装的版本落后了很多：

```shell
C:\Users\admin>pip install meteva
Looking in indexes: https://mirror.sjtu.edu.cn/pypi/web/simple
Requirement already satisfied: meteva in s:\programdata\miniconda3\envs\sci\lib\site-packages (1.1.4.0)
...

C:\Users\admin>pip show meteva
Name: meteva
Version: 1.1.4.0
Summary: A collections of functions for meteorological verification.
Home-page: UNKNOWN
Author: liucouhua,daikan,wangbaoli
Author-email: liucouhua@163.com
License: GPL3
Location: s:\programdata\miniconda3\envs\sci\lib\site-packages
Requires: pandas, scipy, pyshp, httplib2, matplotlib, scikit-learn, xarray, ipywidgets, protobuf, numpy, netCDF4, seaborn
Required-by:

```

但是`meteva`已经更新到1.6+
tuna：https://pypi.tuna.tsinghua.edu.cn/simple/meteva/
pypi：https://pypi.org/project/meteva/#history

请问是同步出了问题吗？另外，https://mirrors.sjtug.sjtu.edu.cn/docs/pypi/web/simple 和 https://mirrors.sjtug.sjtu.edu.cn/docs/pypi-packages 页面中提供的指令都是`pip config set global.index-url https://mirror.sjtu.edu.cn/pypi/web/simple`，和这个问题有关吗？

**Comment by skyzh** [comment]
似乎是因为你本地已经有老版本了？尝试 uninstall 再 install 试试？

**Comment by skyzh** [comment]
也有可能是其他包的限制，可以开一个 virtualenv 新环境安装。

**Comment by skyzh** [comment]
https://mirror.sjtu.edu.cn/pypi/web/simple/meteva/ 同样也有最新版本

**Comment by wohenbushuang** [comment]
> https://mirror.sjtu.edu.cn/pypi/web/simple/meteva/ 同样也有最新版本

@skyzh 嗯看来同步没有问题。我是重装conda安装的，现在尝试uninstall再install还是如此。好像是包/安装环境有问题，这次安装时候仔细看它日志，拉取了1.6的包，在setup时候失败，然后自己就下载1.5 1.4 1.3……版本，直到这个1.1版本安装上了
