### ISSUE TITLE
the mirror of spdk is not work

### ISSUE THREAD

**Issue by pengkh** [sjtug/mirror-requests#248]
access the address https://mirror.sjtu.edu.cn/git/spdk.git/ and returned with 404

**Comment by skyzh** [comment]
Thanks for reporting! We will fix it soon.

By the way, spdk has many sub modules. Our mirror might not help for downloading such dependencies.

**Comment by skyzh** [comment]
Hi @pengkh, thanks for your patience. We have fixed this in https://github.com/sjtug/mirror-docker-unified/pull/312.
