### ISSUE TITLE
Arch 源出错

### ISSUE THREAD

**Issue by specter119** [sjtug/mirror-requests#25]
**类别**：Bug

arch 源缺文件。

```sh
错误：无法从 mirrors.sjtug.sjtu.edu.cn : The requested URL returned error: 404 获取文件 'aspell-0.60.7rc1-1-x86_64.pkg.tar.xz'
警告：无法获取某些文件
错误：无法从 mirrors.sjtug.sjtu.edu.cn : The requested URL returned error: 404 获取文件 'xapian-core-1:1.4.8-1-x86_64.pkg.tar.xz'
警告：无法获取某些文件
错误：无法从 mirrors.sjtug.sjtu.edu.cn : The requested URL returned error: 404 获取文件 'lib32-libgcrypt-1.8.4-1-x86_64.pkg.tar.xz'
警告：无法获取某些文件
错误：无法提交处理 (未预期的错误)
发生错误，没有软件包被更新。
```

**Comment by htfy96** [comment]
Arch源backend是ftp.sjtu.edu.cn。

由于arch源没有一致性保护的原因，很有可能上游的index file会先更新，但package在一次rsync同步中仍然是老版本。在下一次同步中应该会自动恢复。暂时先等12个小时如果还没有恢复再分析问题。

**Comment by htfy96** [comment]
`aspell-0.60.7rc1-1-x86_64.pkg.tar.xz `等文件现在应该已经同步完成了。如果完全按照上游要求的的12小时同步，这类问题会经常出现，其他软件源现在往往都增加了同步频率。如果再次出现之类问题请重新open这个issue

**Comment by wimmerX** [comment]
failed retrieving file 'maven-3.8.4-1-any.pkg.tar.zst' from mirrors.sjtug.sjtu.edu.cn : The requested URL returned error: 404
