### ISSUE TITLE
Termux 镜像源请求

### ISSUE THREAD

**Issue by blleng** [sjtug/mirror-requests#250]
镜像名: Termux APT  镜像源

上游路径: https://packages.termux.org/

镜像简介: 
Termux is a terminal emulator application for Android OS which can be extended by packages of ported common GNU/Linux utilities.

国内其他镜像源同步情况:

清华大学: https://mirrors.tuna.tsinghua.edu.cn/termux/

中科大: http://mirrors.ustc.edu.cn/termux/

南京大学: http://mirrors.nju.edu.cn/termux/

同步方法:

镜像大小:

状态追踪:

- [ ] 同意同步
- [ ] 同步脚本
- [ ] 部署到镜像源
- [ ] 首次同步成功
- [ ] 测试脚本
- [ ] 使用文档
- [ ] 添加到官方源

**Comment by skyzh** [comment]
Dup w/ https://github.com/sjtug/mirror-requests/issues/223
