### ISSUE TITLE
AUR镜像请求

### ISSUE THREAD

**Issue by hongchengni** [sjtug/mirror-requests#253]
镜像名: AUR

上游路径: https://aur.archlinux.org

镜像简介: Arch Linux 用户软件库

国内其他镜像源同步情况: 清华大学 https://aur.tuna.tsinghua.edu.cn （非常慢，不好用，期待给力的交大！）

同步方法:

镜像大小:

状态追踪:

- [ ] 同意同步
- [ ] 同步脚本
- [ ] 部署到镜像源
- [ ] 首次同步成功
- [ ] 测试脚本
- [ ] 使用文档
- [ ] 添加到官方源

**Comment by skyzh** [comment]
dup w/ https://github.com/sjtug/mirror-requests/issues/80?
