### ISSUE TITLE
[ELPA] melpa-stable的文档和路径不一致

### ISSUE THREAD

**Issue by bzEq** [sjtug/mirror-requests#255]
https://mirror.sjtu.edu.cn/docs/emacs-elpa 写的是
> https://mirrors.sjtug.sjtu.edu.cn/emacs-elpa/melpa-stable/

实际地址为https://mirrors.sjtug.sjtu.edu.cn/emacs-elpa/stable-melpa/

**Comment by skyzh** [comment]
感谢～我们将上游切换到 TUNA 之后目录结构发生了比较大的变化。可否帮忙发 PR 更新一下 https://github.com/sjtug/portal/blob/master/content/post/mirror-help/emacs-elpa.md ，顺便把已经不同步的目录从帮助文档中删去？

**Comment by bzEq** [comment]
Fix merged.

**Comment by skyzh** [comment]
更新大概需要半天时间更新到网站上 🥰
