### ISSUE TITLE
crates.io unexpected http status code: 504

### ISSUE THREAD

**Issue by h3fang** [sjtug/mirror-requests#259]
最近经常这样
![screenshot-2022-02-16T16:04:21+08:00](https://user-images.githubusercontent.com/1715589/154221822-7848ba04-c2bc-43ee-8827-65917ae5fb30.png)
换回官方源没问题

**Comment by skyzh** [comment]
Hi, 您的配置文件和系统分别是啥？

**Comment by h3fang** [comment]
系统是Arch

配置 `~/.local/share/cargo/config`
```
[source]

#[source.mirror]
#registry = "https://mirrors.sjtug.sjtu.edu.cn/git/crates.io-index/"

#[source.crates-io]
#replace-with = "mirror"

[target]

[target.x86_64-unknown-linux-gnu]
linker = "/usr/bin/clang"
rustflags = [
    "-C", "link-arg=-fuse-ld=lld",
]

```

**Comment by h3fang** [comment]
会不会和这个有关
https://blog.rust-lang.org/2022/02/14/crates-io-snapshot-branches.html

**Comment by skyzh** [comment]
刚刚在本地试了一下，是可以的，只是拉下来花了比较长的时间，可能是服务器的资源不太够。之后我们会考虑加一些 SSD 来 host 这种大型 git repo。

您可以考虑使用 https://git.sjtu.edu.cn/sjtug/crates.io-index 作为替代（但我们不保证它的可用性）。

**Comment by h3fang** [comment]
好的，谢谢
