### ISSUE TITLE
將 Alpine 鏡像添加到官方文檔中

### ISSUE THREAD

**Issue by FranklinYu** [sjtug/mirror-requests#26]
**类别**：N/A

**镜像名**：Alpine

希望能將 [Alpine 鏡像](https://mirrors.sjtug.sjtu.edu.cn/alpine/)列入[官方列表](https://mirrors.alpinelinux.org/)中。根據說明，需要鏡像管理員給 Alpine 寫郵件。

**Comment by htfy96** [comment]
alpine镜像的问题是：Alpine由于比较小所以默认没有带ca-certificates包的，因此要求软件源必须支持http，不能跳转。但之前有一段时间设置过了全站HSTS，所以客户端还有记忆的话会依旧自动跳转。总之先发封邮件问一下管理员吧

**Comment by htfy96** [comment]
sent

**Comment by htfy96** [comment]
> duniel pls | duniel pls | 9:36 PM (3 minutes ago) |   |  
I have added the mirror, and you should start seeing some traffic towards it soon enough.
>
> Thanks!
