### ISSUE TITLE
rustup 镜像过期

### ISSUE THREAD

**Issue by SamLukeYes** [sjtug/mirror-requests#261]
此前一直设置了环境变量 `RUSTUP_DIST_SERVER=https://mirrors.sjtug.sjtu.edu.cn/rust-static/`，最近偶然发现 rust 的更新停留在了去年十月。

```fish
$ rustup update
info: syncing channel updates for 'stable-x86_64-unknown-linux-gnu'
info: syncing channel updates for 'nightly-x86_64-unknown-linux-gnu'

   stable-x86_64-unknown-linux-gnu unchanged - rustc 1.56.0 (09c42c458 2021-10-18)
  nightly-x86_64-unknown-linux-gnu unchanged - rustc 1.58.0-nightly (00d5e42e7 2021-10-24)

info: cleaning up downloads & tmp directories
```

浏览该镜像的文件时，发现 dist 目录下最新的文件夹为 2021-10-24：

![图片](https://user-images.githubusercontent.com/12882091/154809911-49ee3c46-dbeb-4809-a30a-eb506320e576.png)

镜像首页仍然显示同步成功：

![图片](https://user-images.githubusercontent.com/12882091/154809881-2186779d-a92e-4e47-b10c-7e1553b12114.png)

**Comment by skyzh** [comment]
列表里显示到 10 月是因为这个索引页面一直没跟更新。具体为啥 rustup 更新不到最新版我们晚点调查一下。

如果想安装最新版，可以直接 install nightly-2022-02-19，应该可以直接使用。

**Comment by skyzh** [comment]
确认是缓存规则配置错误导致的，已经使用新规则同步，今天应该可以恢复。
