### ISSUE TITLE
mirrors.sjtug.sjtu.edu.cn 未来会废弃吗？

### ISSUE THREAD

**Issue by abcfy2** [sjtug/mirror-requests#265]
我发现目前似乎所有请求 mirrors.sjtug.sjtu.edu.cn 都会跳转到 mirror.sjtu.edu.cn，我想问下是否未来会全部统一到 mirror.sjtu.edu.cn，而废弃掉 mirrors.sjtug.sjtu.edu.cn ？

**Comment by skyzh** [comment]
不会。mirrors.sjtug.sjtu.edu.cn 依然保存了一半的数据。两个服务器之间只是做了自动跳转。

可以参考 https://github.com/sjtug/mirror-docker-unified/wiki
