### ISSUE TITLE
Debian CD

### ISSUE THREAD

**Issue by hmsjy2017** [sjtug/mirror-requests#266]
镜像名:debian-cd

上游路径: rsync://cdimage.debian.org/debian-cd/
（或rsync://ftp.hk.debian.org/debian-cd/）

镜像简介: Debian 的安装镜像

国内其他镜像源同步情况: TUNA（华东较慢）、USTC（无法wget）等

同步方法: rsync

镜像大小: 约220G

状态追踪:

- [ ] 同意同步
- [ ] 同步脚本
- [ ] 部署到镜像源
- [ ] 首次同步成功
- [ ] 测试脚本
- [ ] 使用文档
- [ ] 添加到官方源

**Comment by skyzh** [comment]
这个镜像由于前几天被恶意攻击，暂时下线重定向到其他镜像站啦。数据其实一直在的。我们检查一下最近的访问 log，如果没有异常，预计下周恢复。
