### ISSUE TITLE
"/ubuntu-cd/" 重定向到 "https://repo.huaweicloud.com/ubuntu-cdimage//"

### ISSUE THREAD

**Issue by pzhlkj6612** [sjtug/mirror-requests#267]
你好！

URL: https://mirrors.sjtug.sjtu.edu.cn/ubuntu-cd/

## 现象

```console
$ curl -IL 'https://mirrors.sjtug.sjtu.edu.cn/ubuntu-cd/'
HTTP/1.1 302 Found
Location: https://mirror.sjtu.edu.cn/ubuntu-cd/
Server: Caddy
X-Sjtug-Mirror-Id: zhiyuan
Date: Tue, 01 Mar 2022 02:26:22 GMT

HTTP/1.1 302 Found
Location: https://repo.huaweicloud.com/ubuntu-cdimage//
Server: Caddy
X-Sjtug-Mirror-Id: siyuan
Date: Tue, 01 Mar 2022 02:26:22 GMT

HTTP/1.1 200 OK
Date: Tue, 01 Mar 2022 02:26:22 GMT
...
```

但 "https://repo.huaweicloud.com/ubuntu-cdimage//" 似乎不包含 amd64 架构的 Ubuntu Server 的镜像文件（如 ubuntu-21.10-live-server-amd64.iso ）。要找到这样的镜像文件，需要去 "https://repo.huaweicloud.com/ubuntu-releases/" 。

## 期望

- "/ubuntu-cd/" 包含如 "https://repo.huaweicloud.com/ubuntu-releases/" 中的文件和文件夹。或者，
- "/ubuntu-cd/" 重定向到 "https://repo.huaweicloud.com/ubuntu-releases/" 。

## 为什么不使用模板

本提案可能同时包含了“ [BUG 反馈](https://github.com/sjtug/mirror-requests/labels/bug)”和“[新镜像请求](https://github.com/sjtug/mirror-requests/labels/new-mirror)”，因此没有使用模板。

**Comment by skyzh** [comment]
Hi, 感谢你的信息。这个镜像源由于受到攻击，近期暂时下线。我们会尽快恢复。
