### ISSUE TITLE
Termux

### ISSUE THREAD

**Issue by hmsjy2017** [sjtug/mirror-requests#270]
镜像名: Termux

上游路径: 
- Android 7 及更高版本：https://packages.termux.org/
- Android 5/6 存档：https://archive.org/download/termux-package-sources-legacy-24.12.2019.tar

镜像简介: 
> Termux 是一个 Android 下一个高级的终端模拟器，开源且不需要 root，支持 apt 管理软件包，十分方便安装软件包，完美支持 Python、 PHP、 Ruby、 Nodejs、 MySQL等。

国内其他镜像源同步情况: 华东有 USTC 和 NJU

同步方法: [aptly](https://www.aptly.info/doc/aptly/mirror/) 或 [apt-mirror.pl](https://github.com/kimmel/apt-mirror-fork)，暂不提供 rsync

镜像大小: 约 14G

状态追踪:

- [ ] 同意同步
- [ ] 同步脚本
- [ ] 部署到镜像源
- [ ] 首次同步成功
- [ ] 测试脚本
- [ ] 使用文档
- [ ] 添加到官方源

**Comment by PhotonQuantum** [comment]
已经同步
