### ISSUE TITLE
packagist镜像的根json文件损坏

### ISSUE THREAD

**Issue by oldwatch** [sjtug/mirror-requests#272]
https://packagist.mirrors.sjtug.sjtu.edu.cn/packages.json

文件内容异常，原本文本文件变成了二进制文件
检查发现文件系正确packages.json的gzip压缩包

烦请检查webservice配置

**Comment by skyzh** [comment]
经检查是同步工具的问题。同步工具直接下载了一个 gz 并存放到 packages.json 位置上。可能要等待上游修复；如果上游已经修复，等待我们更新一下同步工具版本。

**Comment by tourze** [comment]
请问现在解决了吗。。。

**Comment by PhotonQuantum** [comment]
https://github.com/webysther/packagist-mirror/issues/4#issuecomment-407570417
上游要求我们在镜像站上按需解压（nginx gzip-static + gunzip），但是我们使用的 caddy server 似乎没有替代品
cc @skyzh 有什么看法？

**Comment by skyzh** [comment]
每次同步完以后手动解压？🤪

**Comment by skyzh** [comment]
或者强制加一个 encoding gz 的 header 也可以

**Comment by PhotonQuantum** [comment]
> 或者强制加一个 encoding gz 的 header 也可以

`precompressed gzip` 似乎可以。但是现有的 caddy-gen 似乎没法加自定义的 directive?
