### ISSUE TITLE
[Mirror Request]: Golang download

### ISSUE THREAD

**Issue by wohenbushuang** [sjtug/mirror-requests#275]
### 软件源名称

Golang

### 上游路径

https://go.dev/dl/
Domestic version: https://golang.google.cn/dl/

### 国内其他镜像源同步情况

https://golang.google.cn/dl/
https://mirrors.ustc.edu.cn/golang/

### 注意事项

- [X] 我已确认这个镜像源从未在 https://github.com/sjtug/mirror-requests/issues 讨论过，也没有在 https://mirror.sjtu.edu.cn 上线。

**Comment by Bisstocuz** [comment]
https://golang.google.cn/dl/ 这就是官方源

**Comment by PhotonQuantum** [comment]
作为一个 google 的商业项目，且有国内站，google 理应提供了良好的 cdn 支持。请问有没有比较充分的需要进行镜像的理由呢?

**Comment by wohenbushuang** [comment]
> google 理应提供了良好的 cdn 支持

时过境迁，当时下载很慢只有几KBps，应该是没有cdn。现在速度能上MBps了（但也有可能是学校WiFi做了加速？

**Comment by PhotonQuantum** [comment]
由于上游已经在国内提供了良好的速度，且是有成熟服务的商业公司，我站将不进行同步
