### ISSUE TITLE
Arco Linux

### ISSUE THREAD

**Issue by Molyuu** [sjtug/mirror-requests#277]
镜像名:
Arco Linux

上游路径:
https://ant.seedhost.eu/arcolinux/
https://ftp.belnet.be/arcolinux/

镜像简介:
包含了Arco Linux团队配置过的桌面环境，软件等，以及大量预编译的来自AUR的软件包。

另外，此发行版国内外用户都较少，镜像站也较少，且源内的包与archlinuxcn，arch4edu高度重合；同时源内包含大量商业软件，版权问题也需要考虑。

国内其他镜像源同步情况:
尚无。但能找到如下信息：
https://github.com/ustclug/mirrorrequest/issues/298

同步方法:
ftp.belnet.be 源提供多种同步方式：
- HTTP http://ftp.belnet.be/ (IPv4 + IPv6)
- FTP ftp://ftp.belnet.be (IPv4 + IPv6)
- RSYNC rsync://rsync.belnet.be (IPv4)

镜像大小:未知。目测在20GiB到100GiB间

状态追踪:

- [ ] 同意同步
- [ ] 同步脚本
- [ ] 部署到镜像源
- [ ] 首次同步成功
- [ ] 测试脚本
- [ ] 使用文档
- [ ] 添加到官方源

**Comment by PhotonQuantum** [comment]
由于 Arco 仓库中存在一些具有版权争议的包 (见 https://github.com/tuna/issues/issues/1499 )，恕我们无法对其进行同步。
