### ISSUE TITLE
qt新的目录同步

### ISSUE THREAD

**Issue by CharlesLiaoO** [sjtug/mirror-requests#278]
qt官方下载站已经将部分版本的目录从archive移动到new_archive目录，但镜像站并没有new_archive，qt官方下载站速度慢甚至速度为0。请问是否可以同步new_archive目录，便于国内下载

**Comment by PhotonQuantum** [comment]
new_archive 里的 qt 版本应该都是 EOL 的版本。如果没有特别的理由，我们一般不对 EOL 内容提供特殊的支持。
