### ISSUE TITLE
endeavouros mirror

### ISSUE THREAD

**Issue by zinla** [sjtug/mirror-requests#279]
镜像名:endeavouros mirror

上游路径:http://mirror.alpix.eu/endeavouros/

镜像简介:

国内其他镜像源同步情况:

同步方法:

镜像大小:

状态追踪:

- [x] 同意同步
- [x] 同步脚本
- [x] 部署到镜像源
- [x] 首次同步成功
- [ ] 测试脚本
- [ ] 使用文档
- [ ] 添加到官方源

**Comment by abcfy2** [comment]
补充官方的sync方案以及如何提交官方镜像列表： https://github.com/endeavouros-team/mirrors/blob/master/how-to-add-mirror.md

rsync地址: `alpix.eu.rsync.endeavouros.com::endeavouros`

**Comment by PhotonQuantum** [comment]
已经同步完成且向上游提交请求，欢迎向我们贡献镜像使用帮助！
