### ISSUE TITLE
TLS 1.3 support

### ISSUE THREAD

**Issue by htfy96** [sjtug/mirror-requests#28]
考虑给镜像站提供TLS 1.3 0-RTT支持。

上游情况：
- Go的patch已经被merge：https://github.com/golang/go/issues/9671
- Caddy目前需要小幅patch：https://github.com/mholt/caddy/issues/2080

目前情况：等待Caddy上游支持。预期时间 19年2月。

**Comment by linquize** [comment]
TLS 1.3 merged, let's close issue

**Comment by htfy96** [comment]
@linquize waiting for caddy release

**Comment by htfy96** [comment]
Fixed with caddy 0.11.5.

Tested with `time curl -v --http2 -s https://mirrors.sjtug.sjtu.edu.cn/debian/dists/jessie-updates/InRelease > /dev/null`
