### ISSUE TITLE
镜像站挂了？

### ISSUE THREAD

**Issue by abcfy2** [sjtug/mirror-requests#280]
镜像站无法访问了

**Comment by skyzh** [comment]
接学校通知，为不断提升校园网性能，按计划，将对学校校园主干网络进行优化。期间（6月2日-6月6日）学校部分业务系统需要通过VPN的方式进行访问。

因此，镜像站在这段时间内暂停校外访问。

感谢您的理解和支持。

Best regards,
Chi

**Comment by abcfy2** [comment]
好吧，这个时间…… emmmm 秒懂

**Comment by kde-yyds** [comment]
现在（6/5）已经又能用了
