### ISSUE TITLE
crates.io镜像的链接需要更新？

### ISSUE THREAD

**Issue by wangtianxia-sjtu** [sjtug/mirror-requests#284]
https://mirror.sjtu.edu.cn/docs/crates.io
这个crates源的链接似乎已经无法使用，应该换成
```
[source]

[source.mirror]
registry = "https://git.sjtu.edu.cn/sjtug/crates.io-index"

[source.crates-io]
replace-with = "mirror"
```

**Comment by skyzh** [comment]
由于盘比较慢，可能会有卡住的情况。我们还是推荐用户设置 `https://mirrors.sjtug.sjtu.edu.cn/git/crates.io-index/`, 而非 `https://git.sjtu.edu.cn/sjtug/crates.io-index`。

**Comment by wangtianxia-sjtu** [comment]
好吧，刚刚试了一下，`https://mirrors.sjtug.sjtu.edu.cn/git/crates.io-index/`也可使用。但是速度比`https://git.sjtu.edu.cn/sjtug/crates.io-index`要慢很多。
而且，直接访问这个网址`https://mirrors.sjtug.sjtu.edu.cn/git/crates.io-index`会直接404，不知道这个是不是正常现象

**Comment by skyzh** [comment]
404 是正常现象，git repo serving 的时候正常是不会显示任何内容的；直接访问 git.sjtu.edu.cn 会快也是正常的，因为 git.sjtu.edu.cn 的数据放在 SSD 上。
