### ISSUE TITLE
镜像站在GitHub action 中无法访问

### ISSUE THREAD

**Issue by fengkx** [sjtug/mirror-requests#285]
从 2022 年 7 月 14 日开始无法访问
其中一次运行： https://github.com/fengkx/dotfiles/runs/7355523917?check_suite_focus=true#step:7:216

<img width="1556" alt="image" src="https://user-images.githubusercontent.com/16515468/179197226-6f232c31-4478-462d-91dd-14cc03e6375b.png">
13 号是可以的

**Comment by PhotonQuantum** [comment]
Seems like a network related problem. cc @skyzh

**Comment by skyzh** [comment]
We do not expect connections from outside China mainland.

**Comment by PhotonQuantum** [comment]
Okay so I'm closing this issue for now. Feel free to reopen it if you have any more questions.
