### ISSUE TITLE
镜像站貌似全站无法访问

### ISSUE THREAD

**Issue by specter119** [sjtug/mirror-requests#29]
**类别**：Bug

貌似 整个 镜像站 又挂了，<https://mirrors.sjtug.sjtu.edu.cn/> 无法访问。
已经关注 tg，但是tg上说今天中午11点就好了么。

**Comment by htfy96** [comment]
是的，目前已经修复。主要原因是升级后4.19内核panic了

**Comment by htfy96** [comment]
https://github.com/sjtug/mirror-requests/issues/30
