### ISSUE TITLE
请求添加Clear Linux源

### ISSUE THREAD

**Issue by mioli104** [sjtug/mirror-requests#292]
镜像名: Clear Linux

上游路径: http://cdn.download.clearlinux.org/

镜像简介: 一个英特尔开发的高性能Linux发行版

- [ ] 同意同步
- [ ] 同步脚本
- [ ] 部署到镜像源
- [ ] 首次同步成功
- [ ] 测试脚本
- [ ] 使用文档
- [ ] 添加到官方源

**Comment by PhotonQuantum** [comment]
根据上游信息，该发行版无法被镜像

https://community.clearlinux.org/t/how-to-build-my-own-mirror-sever/1996/8
