### ISSUE TITLE
"msys2/msys/x86_64/gcc-9.3.0-1-x86_64.pkg.tar.xz" 404错误

### ISSUE THREAD

**Issue by Seng-Jik** [sjtug/mirror-requests#293]
访问`https://mirrors.sjtug.sjtu.edu.cn/msys2/msys/x86_64/gcc-9.3.0-1-x86_64.pkg.tar.xz`时出现404错误

**Comment by Seng-Jik** [comment]
关联项目：https://github.com/Strrationalism/CPyMO/runs/8073828280?check_suite_focus=true

**Comment by abcfy2** [comment]
https://repo.msys2.org/msys/x86_64/ 即使官方仓库也没有这个文件，这个版本已经被上游移除了
