### ISSUE TITLE
Nginx镜像请求

### ISSUE THREAD

**Issue by yishengyu** [sjtug/mirror-requests#295]
镜像名:
nginx:1.23.1
上游路径:
[library/nginx](https://hub.docker.com/_/nginx/tags)
镜像简介:
Nginx

国内其他镜像源同步情况:

同步方法:

镜像大小:

状态追踪:

- [ ] 同意同步
- [ ] 同步脚本
- [ ] 部署到镜像源
- [ ] 首次同步成功
- [ ] 测试脚本
- [ ] 使用文档
- [ ] 添加到官方源

**Comment by Arnie97** [comment]
不明白这个请求是什么意思，交大已经有 Docker Hub 反代了：https://mirrors.sjtug.sjtu.edu.cn/docs/docker-registry

**Comment by PhotonQuantum** [comment]
上游只提供了 http，除直接暴力扫 listing html 以外的同步方式不明。我们暂时不对此类仓库进行镜像。
