### ISSUE TITLE
Manjaro镜像已经落后100小时

### ISSUE THREAD

**Issue by abcfy2** [sjtug/mirror-requests#297]
按照manjaro镜像列表页面显示： https://repo.manjaro.org/

sjtug的镜像已经落后了100小时:

![image](https://user-images.githubusercontent.com/5327677/198286520-d48f6761-6d00-4d0f-a297-7063eb0b622d.png)

有趣是的阿里云镜像也是落后这么多，不知道是不是因为sjtug上游镜像设置的是aliyun？

希望将上游切换至manjaro官方镜像同步 https://wiki.manjaro.org/index.php?title=Manjaro_Mirrors#How_is_the_mirror_synchronized.3F

**Comment by abcfy2** [comment]
PS: 可能`yandex.ru`在国内的同步速度会更快？ `rsync://mirror.yandex.ru/mirrors/manjaro/`

![image](https://user-images.githubusercontent.com/5327677/198288368-51b42636-0fa7-4aad-b75b-4e06f6be6e07.png)

**Comment by PhotonQuantum** [comment]
经排查，由于服务器的同步管理器出现故障，一台服务器上的大批镜像在近几日内出现失去同步的问题。现在该同步管理器已经重启，出现延迟的镜像正在逐渐重新同步，您可以在 mirror.sjtu.edu.cn 上查看再同步进度。

另我们的上游是伯克利，根据 manjaro 镜像列表显示这个源的同步速度是及时的，但仍感谢您的提醒！

待镜像再同步成功后将会关闭这个 issue。感谢您的报告！

**Comment by PhotonQuantum** [comment]
manjaro 镜像已经恢复同步
