### ISSUE TITLE
域名mirror加不加s

### ISSUE THREAD

**Issue by Firestar-Reimu** [sjtug/mirror-requests#300]
我发现主站的域名是不加s的：https://mirror.sjtug.sjtu.edu.cn

但是一些站点的域名必须加s才能访问：https://mirrors.sjtug.sjtu.edu.cn/ctan/systems/texlive/

测试：

https://mirrors.sjtug.sjtu.edu.cn

（打不打得开随缘，好像新建标签页就打不开）

![image](https://user-images.githubusercontent.com/65082432/200636360-3c2b4817-dbe8-4012-b91f-2f472b4388f1.png)

https://mirror.sjtug.sjtu.edu.cn/ctan/systems/texlive/

**Comment by Arnie97** [comment]
> 我发现主站的域名是不加s的

并没有你说的主站域名 :)

https://mirror.sjtu.edu.cn
https://mirrors.sjtug.sjtu.edu.cn

**Comment by Firestar-Reimu** [comment]
那么如果两个站都提供的服务（比如archlinux）域名可以混用吗
