### ISSUE TITLE
flathub镜像源无法使用

### ISSUE THREAD

**Issue by yeenjie123456** [sjtug/mirror-requests#301]
---
## 当我更换为上海交大的flathub镜像源以后，我尝试通过flatpak安装软件，但它提示*Unable to load summary from remote flathub: Server returned status 308: Unknown Error*。而当我换回flathub官方源时，可正常使用。请问这是怎么回事，谢谢！

**Comment by kenneth104** [comment]
同样情况，由于没有备份，找了一会才看到原来的repo地址是什么

**Comment by cnjswwxbtcc** [comment]
同样，我在阿里云服务器上切换镜像之后，也是报这个错误
`Warning: Could not update extra metadata for 'flathub': Server returned status 308: Unknown Error`

```
$ sudo flatpak remote-ls flathub
error: Server returned status 308: Unknown Error
```

**Comment by lingjiamian** [comment]
一样，怎么换回官方源

**Comment by lingjiamian** [comment]
我的steamdeck换了交大源，discover就装不了软件了，真是服气，官方源dl.flathub.org

**Comment by wurenny** [comment]
308未知错误，看起来到现在为止仍然没有解决

**Comment by skyzh** [comment]
https://developer.mozilla.org/zh-CN/docs/Web/HTTP/Status/308

**Comment by iopq** [comment]
I tried it and it timed out for me

**Comment by lovenemesis** [comment]
同样网络环境，该问题仅发生在 CentOS7 上，使用 flatpak 为 1.0.9。而使用较新版本 flatpak 1.15.4 的 Fedora 系统则没有此问题。

**Comment by PhotonQuantum** [comment]
HTTP 308 状态码，指的是永久跳转。由于我们的缓存架构设计，在请求时会向客户端发起跳转请求，指向最新的文件版本。
新版本的包管理器已经支持跟随这样的跳转指令，而在部分旧版本 OS 上会出现这样的问题。如果碰到这种情况，请更新您的包管理器版本，或是尝试使用其他源
