### ISSUE TITLE
flathub 308 error

### ISSUE THREAD

**Issue by xueye9** [sjtug/mirror-requests#302]
报错信息如下
`$ flatpak install Sjtu org.remmina.Remmina`
`error: Unable to load summary from remote Sjtu: Server returned status 308: Unknown Error`

repo配置文件(/var/lib/flatpak/repo/config)相关配置节如下：
`[remote "Sjtu"]`
`gpg-verify=false`
`gpg-verify-summary=true`
`url=https://mirror.sjtu.edu.cn/flathub`
`url-is-set=true`
`xa.title=Flathub`

使用如下命令导入了 gpk
`wget https://mirror.sjtu.edu.cn/flathub/flathub.gpg`
`sudo flatpak remote-modify --gpg-import=flathub.gpg Sjtu`

**Comment by skyzh** [comment]
308 报错通常是因为 flatpak 版本太老。308 不是错误，是 HTTP redirect 的状态码。

**Comment by BaldStrong** [comment]
> 308 报错通常是因为 flatpak 版本太老。308 不是错误，是 HTTP redirect 的状态码。

我升级到最新的1.14.4版本，在安装过程中还是出现了308错误：
![image](https://user-images.githubusercontent.com/37842039/227968611-51a115f2-de51-41fa-91f4-36a8144c39bb.png)
