### ISSUE TITLE
Git 镜像源完全无法使用

### ISSUE THREAD

**Issue by taumasyang** [sjtug/mirror-requests#304]
<img width="842" alt="image" src="https://user-images.githubusercontent.com/39393816/220243172-f22f6f08-9506-466c-b0c9-3ae7e2e09769.png">
如图，Homebrew 无法更新，504 好久了；`tlmgr` 能用但很慢。

**Comment by PhotonQuantum** [comment]
经检查是磁盘负荷过高造成的问题，已经做了调整，请问问题现在是否解决了?

**Comment by taumasyang** [comment]
最近没有出现类似情况了，感谢！
