### ISSUE TITLE
Debian cloud images

### ISSUE THREAD

**Issue by Jimmy-Z** [sjtug/mirror-requests#307]
镜像名: Debian cloud images

上游路径:
https://cloud.debian.org/images/cloud/
https://cdimage.debian.org/cdimage/cloud/

镜像简介: 除了用在云上，本地用在kvm/qemu上也比cd镜像方便

国内其他镜像源同步情况:
科大和南大镜像站有收录
http://mirrors.ustc.edu.cn/debian-cdimage/cloud/
http://mirror.nju.edu.cn/debian-cdimage/cloud/

同步方法:
未调查，猜测应与 debian-cd 相似

镜像大小:
未知

状态追踪:

- [x] 同意同步
- [x] 同步脚本
- [x] 部署到镜像源
- [x] 首次同步成功
- [ ] 测试脚本
- [ ] 使用文档
- [ ] 添加到官方源

**Comment by PhotonQuantum** [comment]
经简单估算，这个仓库内大概有两百万以上个文件，大小超过 1.8T。由于磁盘空间紧张，以及 S3 架构的局限性，暂时不考虑镜像。等暑假进行 S3 架构更新后会重新进行评估。

**Comment by PhotonQuantum** [comment]
似乎可以只同步其中一小部分文件

**Comment by PhotonQuantum** [comment]
已经同步。如果愿意的话欢迎向我们的帮助文件贡献使用说明：https://github.com/sjtug/portal
