### ISSUE TITLE
GitLab is not responding

### ISSUE THREAD

**Issue by liyishuai** [sjtug/mirror-requests#308]
Mirror: [ohmyzsh](https://mirrors.sjtug.sjtu.edu.cn/docs/git/ohmyzsh.git)
> Updating Oh My Zsh
remote: GitLab is not responding
fatal: unable to access 'https://git.sjtu.edu.cn/sjtug/ohmyzsh.git/': The requested URL returned error: 502
There was an error updating. Try again later?

**Comment by PhotonQuantum** [comment]
git.sjtu.edu.cn is not maintained by SJTUG. They have already resolved the issues and the error should no longer persist.
