### ISSUE TITLE
增加 mirrors.sjtu.edu.cn 域名 CNAME

### ISSUE THREAD

**Issue by happyaron** [sjtug/mirror-requests#309]
如题，当前仅有 mirror.sjtu.edu.cn，希望条件允许增加一个CNAME记录，可以算是 https://github.com/sjtug/mirror-requests/issues/300 的一个后续建议

**Comment by PhotonQuantum** [comment]
和网信老师询问了一下，新解析域名可能需要走学校流程审批，比较困难，短期内暂不实施🙈
