### ISSUE TITLE
fedora 的各个镜像请注册到 fedora mirrormanager

### ISSUE THREAD

**Issue by pugaizai** [sjtug/mirror-requests#310]
Fedora 具有 mirrorlist 机制，只有注册到 fedora mirrormanager https://admin.fedoraproject.org/mirrormanager ，才会解析要具体的镜像站。目前fedora beta和rawhide只有本站有镜像，如果加入到mirrorlist会给用户带来巨大方便。
目前中国已有一些镜像站注册了，但 sjtu 镜像没有：
https://admin.fedoraproject.org/mirrormanager/mirrors/Fedora/38/x86_64

**Comment by skyzh** [comment]
很早以前就注册了，但是 mirror manager 没有显示出来。

**Comment by pugaizai** [comment]
感觉是不是要给他们工作人员发工单了
