### ISSUE TITLE
docker-registry not pull latest images from docker hub

### ISSUE THREAD

**Issue by haobibo** [sjtug/mirror-requests#311]
After configuring docker hub mirror by following instructions from : https://mirrors.sjtug.sjtu.edu.cn/docs/docker-registry
I found the image pulled from the mirror is older than the ones from DockerHub.

E.g.: After pull `docker pull docker.mirrors.sjtug.sjtu.edu.cn/library/ubuntu`, using docker inspect shows that this image is created at "Created": "2022-12-09T01:20:31.321639501Z". While the image on DockerHub is created within two weeks: https://hub.docker.com/_/ubuntu/tags

**Comment by haobibo** [comment]
The following command outputs image does not exists: `docker pull docker.mirrors.sjtug.sjtu.edu.cn/library/ubuntu:lunar-20220314`

While the image `docker.io/library/ubuntu:lunar-20220314` can be pulled.

**Comment by haobibo** [comment]
@skyzh  could you please confirm if this is a bug?

**Comment by skyzh** [comment]
cc @PhotonQuantum thanks for investigation!

**Comment by PhotonQuantum** [comment]
~Our IP address is blocked upstream, and now our registry is serving offline (no new images available).~

It appears that there is a misconfiguration in our network that is unrelated to the issue you're reporting. However, we've identified a potential cause of this issue and are working on a fix.

**Comment by PhotonQuantum** [comment]
Now `docker pull docker.mirrors.sjtug.sjtu.edu.cn/library/ubuntu:lunar-20230314` works as expected, and `ubuntu:latest` is up-to-date (`2023-03-08T04:32:41.063980445Z`).

**Comment by haobibo** [comment]
Thank you @PhotonQuantum !
Yes, it now works as expected.

**Comment by haobibo** [comment]
@PhotonQuantum  It seems that the bug occurred again.
`docker pull qpod/py-data:2023.0322.1117` works fine.
`docker pull docker.mirrors.sjtug.sjtu.edu.cn/qpod/py-data:2023.0322.1117` returns no images.

Ref: https://hub.docker.com/r/qpod/py-data/tags

**Comment by PhotonQuantum** [comment]
I'm sorry for any trouble caused. Unfortunately, it appears that we're experiencing a recurrence of the network issue. We are working to address the problem on the upcoming weekday.

**Comment by haobibo** [comment]
no worry~ take your time.
Thanks for your efforts in advance @PhotonQuantum !

**Comment by PhotonQuantum** [comment]
The problem has been resolved. If you have any other concerns, please don't hesitate to let us know!
