### ISSUE TITLE
【镜像申请】openKylin申请加入上海交通大学开源镜像站

### ISSUE THREAD

**Issue by fenshezhuiyi** [sjtug/mirror-requests#316]
openKylin 社区是在开源、自愿、平等和协作的基础上，由基础软硬件企业、非营利性组织、社团组织、高等院校、科研机构和个人开发者共同创立的一个开源社区，致力于通过开源、开放的社区合作，构建桌面操作系统开源社区，推动Linux开源技术及其软硬件生态繁荣发展。 ​
官方源仓库网址：https://archive.openkylin.top/ 
官方镜像库网址：https://releases.openkylin.top/  
openKylin软件仓库和镜像库对外提供同步服务，主要配置如下：
仓库（源）同步命令:
rsync -av openkylin@archive.openkylin.top::openkylin /本地目录/openkylin

镜像库同步命令:
rsync -av openkylin@releases.openkylin.top::releases /本地目录/openkylin-cdimage/
注：同步命令密码可邮件至contact@openkylin.top

**Comment by PhotonQuantum** [comment]
您好，我们已经开始对您的仓库进行初期同步。在同步完成后，将会正式合并开始服务。
https://github.com/sjtug/mirror-docker-unified/pull/385
