### ISSUE TITLE
nix-cache-info请求超时

### ISSUE THREAD

**Issue by yangsengui** [sjtug/mirror-requests#318]
![image](https://user-images.githubusercontent.com/59313293/236830080-1e4ebf1d-2041-4fba-a4e0-0c0beeb0b210.png)
在请求找个链接时会跳转到原镜像地址https://cache.nixos.org/nix-cache-info

**Comment by PhotonQuantum** [comment]
这个问题我们已经观察一段时间了，之后可能会将这个路径加入反代解决
