### ISSUE TITLE
请求添加 ImmortalWrt 镜像

### ISSUE THREAD

**Issue by douglarek** [sjtug/mirror-requests#319]
镜像名:

ImmortalWrt

上游路径:

https://downloads.immortalwrt.org

镜像简介:

ImmortalWrt 是 OpenWrt 的一个第三方分支，主要针对国人用户开发，提供更多的本地化软件包和设备支持。

项目地址： https://github.com/immortalwrt

国内其他镜像源同步情况:

同步方法:

```
env RSYNC_PASSWORD="immortalwrt-org" rsync -4ahv --delete-delay "rsync://firmwarepublic@rsync-mirror.infra.immortalwrt.org/firmware-public/" "immortalwrt/"
```

镜像大小:
~930 GB.
状态追踪:

- [x] 同意同步
- [x] 同步脚本
- [x] 部署到镜像源
- [x] 首次同步成功
- [ ] 测试脚本
- [ ] 使用文档
- [ ] 添加到官方源

**Comment by PhotonQuantum** [comment]
根据 https://github.com/JLULUG/issues/issues/8 的讨论，我们将使用 `--exclude '/snapshots/' --exclude '/releases/*18.06*'` 参数进行同步。近期将进行初次同步。

**Comment by PhotonQuantum** [comment]
初次同步已经完成，且已经部署到站点上，见 https://mirror.sjtu.edu.cn/immortalwrt 。
由于近日镜像站维护，待维护结束后可以在站点上看到看到相关镜像。
欢迎您向 https://github.com/sjtug/portal 及 https://github.com/mirrorz-org/mirrorz-help 贡献供下游用户查看的配置教程，也欢迎您在您的官方网站上注明本镜像站源。

**Comment by 1715173329** [comment]
感谢您的支持，我会在最近两天发起 PR 增加配置说明
