### ISSUE TITLE
希望新增node镜像

### ISSUE THREAD

**Issue by Rainy99** [sjtug/mirror-requests#32]
**类别**：新增镜像

**镜像名**：node

**上游路径**：https://nodejs.org/dist/

**镜像简介**：Node.js 是一个基于 Chrome V8 引擎的 JavaScript 运行环境

**Comment by htfy96** [comment]
rsync上游：rsync://unencrypted.nodejs.org/nodejs/release/

```
Number of files: 50,763 (reg: 47,726, dir: 2,951, link: 86)
Number of created files: 50,762 (reg: 47,726, dir: 2,950, link: 86)
Number of deleted files: 0
Number of regular files transferred: 47,726
Total file size: 108,561,118,760 bytes
Total transferred file size: 108,561,116,702 bytes
Literal data: 0 bytes
Matched data: 0 bytes
File list size: 401,406
File list generation time: 0.005 seconds
File list transfer time: 0.000 seconds
Total bytes sent: 155,913
Total bytes received: 1,279,356

sent 155,913 bytes  received 1,279,356 bytes  410,076.86 bytes/sec
total size is 108,561,118,760  speedup is 75,638.17 (DRY RUN
```

**Comment by htfy96** [comment]
暂时新增了反代，配合`n`使用的话可以`export NODE_MIRROR=https://mirrors.sjtug.sjtu.edu.cn/nodejs-release/`

**Comment by Rainy99** [comment]
> 暂时新增了反代。
> 
> 配合`n`使用的话可以`export NODE_MIRROR=https://mirrors.sjtug.sjtu.edu.cn/nodejs-release/`
> 
> 配合`nvm`的话可以`export NVM_NODEJS_ORG_MIRROR=https://mirrors.sjtug.sjtu.edu.cn/nodejs-release`

感谢!
