### ISSUE TITLE
镜像站是否挂了？

### ISSUE THREAD

**Issue by PHSix** [sjtug/mirror-requests#320]
如题，镜像站的网站访问不了

**Comment by zhuwjin** [comment]
> 由于上游校园主干网络临时维护，SJTUG 软件源镜像站 (mirror.sjtu.edu.cn 及 mirrors.sjtug.sjtu.edu.cn) 目前公网服务中断。
> 
> 本次服务中断的影响范围是 mirror.sjtu.edu.cn 及 mirrors.sjtug.sjtu.edu.cn 上存储的所有软件源。
> 
> 本次维护的服务不可用时间窗口预计如下。
> 
> * 2023年6月3日 (周六) 至 2023年6月5日（周一）：上游校园主干网络维护


在维护呢

**Comment by PhotonQuantum** [comment]
本次服务中断是预期内的维护内容，暂时关闭该 issue 了。如有其他问题欢迎新开 issue。
