### ISSUE TITLE
flathub 中 texlive 运行时的安装问题

### ISSUE THREAD

**Issue by lumingzh** [sjtug/mirror-requests#323]
请问镜像站对 flatpak 运行时（比如 `org.freedesktop.Platform` 或 `org.freedesktop.Sdk` 之类）是怎样的缓存机制，还是直接忽略对运行时的缓存？

最近安装 `org.freedesktop.Sdk.Extension.texlive//22.08` 发现下载速度非常慢，报错时显示的拉取地址是 dl.flathub.org 而不是镜像站，这个有办法解决吗？还是说存在其它问题？

**Comment by lumingzh** [comment]
大清早又试了一下竟然以相当快的速度下载安装完成了，不知道这是怎么回事，为什么早上可以晚上就不行……

**Comment by PhotonQuantum** [comment]
这应该是因为我们的仓库是使用缓存机制同步的，可能第一次下载的时候回源了，而第二次下载的时候因为第一次请求触发同步，从而命中了缓存。
