### ISSUE TITLE
leopard.sh

### ISSUE THREAD

**Issue by basiczombie-47** [sjtug/mirror-requests#324]
镜像名: leopard.sh

上游路径: https://leopard.sh

镜像简介: 一个给powerpc mac老电脑用的包管理器，提供了许多常用软件包，解决了老电脑用macports安装软件编译过慢的问题

国内其他镜像源同步情况: 无

同步方法: rsync://leopard.sh::html

镜像大小: 约25G

状态追踪:

- [x] 同意同步
- [x] 同步脚本
- [x] 部署到镜像源
- [x] 首次同步成功
- [ ] 测试脚本
- [ ] 使用文档
- [ ] 添加到官方源

**Comment by PhotonQuantum** [comment]
现在似乎没有国内镜像站同步这一仓库？您估计这个仓库的用户量大概会有多大呢

**Comment by basiczombie-47** [comment]
国内应该最多几百个吧

**Comment by PhotonQuantum** [comment]
作为新同步工具的测试，该仓库已经同步并上线。如果感兴趣的话欢迎给我们编写帮助文档！https://github.com/sjtug/portal
