### ISSUE TITLE
docker-ce 文件 hash sum mismatch

### ISSUE THREAD

**Issue by PhotonQuantum** [sjtug/mirror-requests#325]
tuna issue: https://github.com/tuna/issues/issues/1819

由于我们的上游是 TUNA，所以也受到影响。问题的根本原因是上游提供了错误的 metadata，在原地修改完文件后没有更新文件的修改时间，导致同步脚本错误地跳过了更新后的文件。

**Comment by PhotonQuantum** [comment]
本次暂时等待 tuna 更新，之后会将同步上游切换到 download.docker.com 并使用发行版自身的 apt-mirror 同步，应该可以避免这类问题

Update: 上游仓库不完全是一个 apt repo，还有一些 yum repo 以及不受包管理控制的静态文件，所以不能使用 apt-mirror 同步🤡

**Comment by truc0** [comment]
目前 https://mirror.sjtu.edu.cn/docker-ce 已重定向到 https://ftp.sjtu.edu.cn/docker-ce ，清华上游的相关 issue 也已经 fixed。
因此先 Close 该 issue，后续如果有使用问题可以重新开启。
