### ISSUE TITLE
debian cloud-image lastest link return 404

### ISSUE THREAD

**Issue by iamwrm** [sjtug/mirror-requests#327]
For debian, they provide links to download cloud-image via 
https://cloud.debian.org/images/cloud/bookworm/latest/debian-12-generic-amd64.qcow2

However, the mirror site returns 404 for https://mirror.sjtu.edu.cn/debian-cdimage/cloud/bookworm/latest

We can only download images from https://mirror.sjtu.edu.cn/debian-cdimage/cloud/bookworm/20231013-1532/debian-12-generic-amd64-20231013-1532.qcow2, which needs to update from time to time and is bad for scripts.

**Comment by PhotonQuantum** [comment]
Debug trace:

```
"" / "cloud": followed directory
"cloud" / "bookworm": followed directory
"cloud/bookworm" / "latest": following symlink -> "20231013-1532/.latest"
"cloud/bookworm" / "20231013-1532": followed directory
"cloud/bookworm/20231013-1532" / ".latest": not found, abort
```

We have identified the problem: a symlink points to a hidden file, but our sync rule omits hidden files. I'll make sure to fix it when I'm available.
