### ISSUE TITLE
好像qt不管用了，不知道是为什么

### ISSUE THREAD

**Issue by huhuang03** [sjtug/mirror-requests#328]
我换阿里云的，能够安装

 C:\Users\name\Downloads\qt-unified-windows-x64-4.6.1-online.exe --mirror https://mirrors.aliyun.com/qt

但是如果使用交大的

C:\Users\name\Downloads\qt-unified-windows-x64-4.6.1-online.exe --mirror https://mirrors.sjtug.sjtu.edu.cn/qt

会出现如下报错
<img width="713" alt="3e07950d63472ff959022c9cb682358" src="https://github.com/sjtug/mirror-requests/assets/4716706/93b22eeb-0a3b-4d4d-845f-e61ae33e0a6c">

我没有使用代理

 我也没有详细查原因

**Comment by PhotonQuantum** [comment]
会不会是网络波动原因？之后重试能恢复吗？另外能不能提供一个文字版报错方便复现（主要是图上那个下载文件的 url）

**Comment by huhuang03** [comment]
太久了，先关掉哦。下次出现再打开
