### ISSUE TITLE
请求 给conda源 增加频道 viscid-hub

### ISSUE THREAD

**Issue by specter119** [sjtug/mirror-requests#33]
**类别**：新增

**镜像名**：
conda镜像新增viscid-hub频道

**上游路径**：
https://anaconda.org/viscid-hub

**镜像简介**：
由于conda的问题，python的流行3D包mayavi在各个平台(linux/mac/win)安装使用都有问题。 需要部分包使用pip安装，且需要固定某些包的版本。
viscid-hub频道正式为了解决这个问题，它只维护了4个包，旨在解决mayavi在各个平台的安装使用问题。
评论看到sjtug镜像最近空间吃紧，但是viscid-hub的内容确实不多，希望可以加上，如果没有加上也没关系，谢谢。

**Comment by htfy96** [comment]
已经在同步了

**Comment by htfy96** [comment]
done 有问题可以重新open这个issue

https://mirrors.sjtug.sjtu.edu.cn/anaconda/cloud/viscid-hub/

**Comment by specter119** [comment]
@htfy96 非常感谢
