### ISSUE TITLE
pypi 镜像频繁 504

### ISSUE THREAD

**Issue by akkuman** [sjtug/mirror-requests#331]
```
#26 40.94 Collecting billiard==3.6.4.0
#26 101.9   ERROR: HTTP error 504 while getting https://mirror.sjtu.edu.cn/pypi-packages/2b/89/0c43de91d4e52eaa7bd748771d417f6ac9e51e66b2f61928c2151bf65878/billiard-3.6.4.0-py3-none-any.whl#sha256=87103ea78fa6ab4d5c751c4909bcff74617d985de7fa8b672cf8618afd5a875b (from https://mirror.sjtu.edu.cn/pypi/web/simple/billiard/)
#26 101.9 ERROR: Could not install requirement billiard==3.6.4.0 from https://mirror.sjtu.edu.cn/pypi-packages/2b/89/0c43de91d4e52eaa7bd748771d417f6ac9e51e66b2f61928c2151bf65878/billiard-3.6.4.0-py3-none-any.whl#sha256=87103ea78fa6ab4d5c751c4909bcff74617d985de7fa8b672cf8618afd5a875b (from -r /tmp/deps/requirements.txt (line 7)) because of HTTP error 504 Server Error: Gateway Time-out for url: https://s3.jcloud.sjtu.edu.cn/899a892efef34b1b944a19981040f55b-oss01/pypi-packages/2b/89/0c43de91d4e52eaa7bd748771d417f6ac9e51e66b2f61928c2151bf65878/billiard-3.6.4.0-py3-none-any.whl for URL https://mirror.sjtu.edu.cn/pypi-packages/2b/89/0c43de91d4e52eaa7bd748771d417f6ac9e51e66b2f61928c2151bf65878/billiard-3.6.4.0-py3-none-any.whl#sha256=87103ea78fa6ab4d5c751c4909bcff74617d985de7fa8b672cf8618afd5a875b (from https://mirror.sjtu.edu.cn/pypi/web/simple/billiard/)
```

重新构建Docker再次安装可能又是另一个包报错

**Comment by akkuman** [comment]
#32 91.70 Collecting kombu==5.2.4
#32 151.8   ERROR: HTTP error 504 while getting https://mirror.sjtu.edu.cn/pypi-packages/d9/f3/62d12dd7ebad710319f0877c1c33bca379fc7d28069daae890fa2fa444c8/kombu-5.2.4-py3-none-any.whl#sha256=8b213b24293d3417bcf0d2f5537b7f756079e3ea232a8386dcc89a59fd2361a4 (from https://mirror.sjtu.edu.cn/pypi/web/simple/kombu/) (requires-python:>=3.7)
#32 151.8 ERROR: Could not install requirement kombu==5.2.4 from https://mirror.sjtu.edu.cn/pypi-packages/d9/f3/62d12dd7ebad710319f0877c1c33bca379fc7d28069daae890fa2fa444c8/kombu-5.2.4-py3-none-any.whl#sha256=8b213b24293d3417bcf0d2f5537b7f756079e3ea232a8386dcc89a59fd2361a4 (from -r /tmp/deps/requirements.txt (line 31)) because of HTTP error 504 Server Error: Gateway Time-out for url: https://s3.jcloud.sjtu.edu.cn/899a892efef34b1b944a19981040f55b-oss01/pypi-packages/d9/f3/62d12dd7ebad710319f0877c1c33bca379fc7d28069daae890fa2fa444c8/kombu-5.2.4-py3-none-any.whl for URL https://mirror.sjtu.edu.cn/pypi-packages/d9/f3/62d12dd7ebad710319f0877c1c33bca379fc7d28069daae890fa2fa444c8/kombu-5.2.4-py3-none-any.whl#sha256=8b213b24293d3417bcf0d2f5537b7f756079e3ea232a8386dcc89a59fd2361a4 (from https://mirror.sjtu.edu.cn/pypi/web/simple/kombu/) (requires-python:>=3.7)

**Comment by PhotonQuantum** [comment]
这有可能是网络波动造成的，现在还有这个问题吗？

**Comment by akkuman** [comment]
最近好像正常了
