### ISSUE TITLE
反向代理 Hugging Face

### ISSUE THREAD

**Issue by KYLN24** [sjtug/mirror-requests#332]
镜像名: Hugging Face

上游路径: https://huggingface.co

镜像简介: Hugging Face 的模型与数据集，用户可以通过设置 HF_ENDPOINT 环境变量来使用。

国内其他镜像源同步情况: https://hf-mirror.com, https://aliendao.cn

同步方法: 反向代理

镜像大小: 非常大

状态追踪:

- [ ] 同意同步
- [ ] 同步脚本
- [ ] 部署到镜像源
- [ ] 首次同步成功
- [ ] 测试脚本
- [ ] 使用文档
- [ ] 添加到官方源

**Comment by PhotonQuantum** [comment]
有消息称上游正在筹备官方中国镜像，且现有已知的镜像方法存在困难（我们原则上不进行单纯的反代）。
https://github.com/tuna/issues/issues/937#issuecomment-1520149600

当然上游提出筹备中国镜像已有半年却无进展，若之后官方迟迟无动作，且存在新的镜像方法，我们会再次考虑进行镜像。
这边就先关闭 issue 了，届时欢迎重新打开 issue 回复，我们将再次评估。

**Comment by Lyken17** [comment]
目前看起来，官方迟迟没有没有推进的打算... 

是否考虑采用一些 python scripts 进行同步？HF 包本身提供了很多方便的 API，比如 `snapshot_download` 可以直接下载整个项目，`get_hf_file_metadata` `hf_hub_url` 可以远程获取 meta 信息。复刻一个同结构的 http server 是易操作且可行的。
