### ISSUE TITLE
[Mirror Request]: Office Tool Plus GitHub release

### ISSUE THREAD

**Issue by YerongAI** [sjtug/mirror-requests#334]
### 软件源名称

Office Tool Plus

### 上游路径

该项目在 GitHub 有 repo，虽然并不是 full open source 但是由于应用本身受到广大用户的喜爱因此希望 SJTUG 也可以提供一下同步服务，让更多用户能够享受到更好的下载服务。同时本项目也在贵校的[正版化服务](https://software.sjtu.edu.cn/List/Office/2021)中有提供。

GitHub repo: https://github.com/YerongAI/Office-Tool
Official website: https://otp.landian.vip/

### 国内其他镜像源同步情况

目前仅有 [山东大学镜像站](https://mirrors.sdu.edu.cn/github-release/YerongAI_Office-Tool/) 在同步。

### 同步方法

同步 GitHub Release

### 注意事项

- [X] 我已确认这个镜像源从未在 https://github.com/sjtug/mirror-requests/issues 讨论过，也没有在 https://mirror.sjtu.edu.cn 上线。

**Comment by PhotonQuantum** [comment]
我个人也有使用这款工具，感谢您的贡献！已经完成同步。

**Comment by YerongAI** [comment]
感谢姐姐，可否再请问下 https://s3.jcloud.sjtu.edu.cn/899a892efef34b1b944a19981040f55b-oss01/github-release/YerongAI/Office-Tool/releases/download/ 这个链接会变吗？`/899a892efef34b1b944a19981040f55b-oss01/` 看起来不太像是个常见的固定格式。我想做一些固定跳转所以问一下这个问题（

**Comment by definfo** [comment]
> 感谢姐姐，可否再请问下 https://s3.jcloud.sjtu.edu.cn/899a892efef34b1b944a19981040f55b-oss01/github-release/YerongAI/Office-Tool/releases/download/ 这个链接会变吗？`/899a892efef34b1b944a19981040f55b-oss01/` 看起来不太像是个常见的固定格式。我想做一些固定跳转所以问一下这个问题（

[https://github.com/sjtug/mirror-docker-unified/wiki/Bootstrap-mirror-from-SJTUG](url)
看起来是在 S3 存储上的固定标识
