### ISSUE TITLE
flutter_infra镜像不可用

### ISSUE THREAD

**Issue by foolely** [sjtug/mirror-requests#34]
**bug反馈**：
➜  flutter git:(local-dev) export FLUTTER_STORAGE_BASE_URL=https://mirrors.sjtug.sjtu.edu.cn/flutter_infra
➜  flutter git:(local-dev) flutter doctor
Downloading Dart SDK from Flutter engine 526e0e3afb2c6879a7924246521813790c4deb48...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   262  100   262    0     0    230      0  0:00:01  0:00:01 --:--:--   231
[/xxx/dev-env/flutter/bin/cache/dart-sdk-darwin-x64.zip]
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of /xxx/dev-env/flutter/bin/cache/dart-sdk-darwin-x64.zip or
        /xxx/dev-env/flutter/bin/cache/dart-sdk-darwin-x64.zip.zip, and cannot find /xxx/dev-env/flutter/bin/cache/dart-sdk-darwin-x64.zip.ZIP, period.

It appears that the downloaded file is corrupt; please try the operation again later.
If this problem persists, please report the problem at
https://github.com/flutter/flutter/issues/new?template=ACTIVATION.md

**Comment by htfy96** [comment]
文档没有来得及更新，可以用
```
export FLUTTER_STORAGE_BASE_URL=https://mirrors.sjtug.sjtu.edu.cn
```
正常下载

**Comment by htfy96** [comment]
已更新文档，如果还有问题可以reopen这个issue
