### ISSUE TITLE
疑似flatpak镜像挂了

### ISSUE THREAD

**Issue by morrussa** [sjtug/mirror-requests#340]
morrussa@fedora:~$ flatpak install flathub com.obsproject.Studio
寻找匹配项…
错误： 无法从远程仓库 flathub 加载摘要：While fetching https://mirror.sjtu.edu.cn/flathub/summary.idx: [35] SSL connect error
morrussa@fedora:~$ flatpak install flathub com.obsproject.Studio
寻找匹配项…

错误： 无法从远程仓库 flathub 加载摘要：While fetching https://mirror.sjtu.edu.cn/flathub/summary.idx: [35] SSL connect error
morrussa@fedora:~$ 
morrussa@fedora:~$ 
系统：fedora 39
内核版本：6.6.13-200.fc39.x86_64
桌面：GNoME46

**Comment by PhotonQuantum** [comment]
您好，我们对 flathub 提供的是缓存服务，在访问索引时会回源至上游。请检查您的网络至上游的连通情况。

**Comment by ted423** [comment]
> 您好，我们对 flathub 提供的是缓存服务，在访问索引时会回源至上游。请检查您的网络至上游的连通情况。

虽然不知道在这里说合不合适，目前是直接添加flathub官方源再修改镜像源可以用。
但如果重置环境，直接添加镜像源报错
```
sudo flatpak remote-add --if-not-exists flathub https://mirror.sjtu.edu.cn/flathub
error: Signature made Sat 01 Jun 2024 05:09:15 PM CST using RSA key ID 562702E9E3ED7EE8
Can't check signature: public key not found

```

**Comment by PhotonQuantum** [comment]
@ted423 emm 非相关问题建议新开一个 issue，否则我们跟进处理起来可能会遗漏

**Comment by ted423** [comment]
> sudo flatpak remote-add --if-not-exists flathub https://mirror.sjtu.edu.cn/flathub

了解，因为第一次用，不知道这种状况是不是本身就是正常的

**Comment by PhotonQuantum** [comment]
好的这边讨论就在新的 issue 进行了
