### ISSUE TITLE
gcr.io 拉取问题

### ISSUE THREAD

**Issue by Phynon** [sjtug/mirror-requests#341]
k8s-gcr-io.mirrors.sjtug.sjtu.edu.cn 拉取没有问题，但 gcr-io.mirrors.sjtug.sjtu.edu.cn 报 internal error。问下是否不维护 gcr.io 而只维护 k8s.gcr.io 镜像了？

**Comment by PhotonQuantum** [comment]
您好，我们目前没有维护 gcr.io 的镜像，只提供了 k8s.gcr.io 镜像。
