### ISSUE TITLE
Arch Linux ALHP

### ISSUE THREAD

**Issue by ttc0419** [sjtug/mirror-requests#342]
镜像名: ALHP

上游路径:
项目地址：https://somegit.dev/ALHP/alhp-mirrorlist#how-to-become-a-mirror
仓库地址：rsync://alhp.dev/alhp

镜像简介:
开启LTO和特定CPU优化指令的Arch Linux软件仓库。

国内其他镜像源同步情况:
无？

同步方法:
rsync

镜像大小:
“around 30GB per march (e.g. x86-64-v3) you want to sync.”

状态追踪:

- [x] 同意同步
- [x] 同步脚本
- [x] 部署到镜像源
- [x] 首次同步成功
- [ ] 测试脚本
- [ ] 使用文档
- [x] 添加到官方源

**Comment by PhotonQuantum** [comment]
已经添加至官方源，感谢您的建议！
