### ISSUE TITLE
建议提供部分发行版安装iso

### ISSUE THREAD

**Issue by iamwrm** [sjtug/mirror-requests#35]
目前只有部分发行版对应的repo里有安装镜像下载，希望能像 https://mirrors.ustc.edu.cn/ 在首页做一个“获取发行版映像” 的汇总功能。
![image](https://user-images.githubusercontent.com/22743891/50673134-fa873280-1016-11e9-86c8-780e99b0d3fd.png)
例如ustc mirror里有manjaro的iso，但是https://mirrors.sjtug.sjtu.edu.cn/manjaro/ 里面并没有安装镜像

**Comment by SkyZH** [comment]
加上了筛选含发行版镜像的功能。部分发行版（如 Manjaro）由于镜像没有同步对应发行版源 `manjaro-cd`，所以没有提供 iso 的下载链接。

**Comment by skyzh** [comment]
发行版汇总功能现已部署（咕咕咕了半年多）

Related PR: https://github.com/sjtug/sjtug-mirror-frontend/pull/16
