### ISSUE TITLE
ubuntu源文档问题

### ISSUE THREAD

**Issue by wohenbushuang** [sjtug/mirror-requests#353]
原文：
```
将类似于http://cn.archive.ubuntu.com/ubuntu或http://cn.archive.ubuntu.com/ubuntu的地址改成https://mirror.sjtu.edu.cn/ubuntu
```
两个cn.重复了，应改为：
```
将类似于http://archive.ubuntu.com/ubuntu或http://cn.archive.ubuntu.com/ubuntu的地址改成https://mirror.sjtu.edu.cn/ubuntu
```

同理，下方批量修改命令建议也加上不带cn.的版本：`sudo sed -i 's/http:\/\/archive.ubuntu.com/https:\/\/mirror.sjtu.edu.cn/g' /etc/apt/sources.list`

不带cn.的版本是默认的更常见（如WSL中）

**Comment by PhotonQuantum** [comment]
感谢指正！欢迎前往 https://github.com/sjtug/portal 提交 pr 修改！
