### ISSUE TITLE
docs 网页指令有误

### ISSUE THREAD

**Issue by OhGaGaGaGa** [sjtug/mirror-requests#358]
看起来 https://mirror.sjtu.edu.cn/docs/pypi-packages 使用了与 https://mirror.sjtu.edu.cn/docs/pypi/web/simple 完全一样的指令设置参考。

**Comment by OhGaGaGaGa** [comment]
是否应该替换为 https://mirror.sjtu.edu.cn/pypi-packages/ ？

**Comment by PhotonQuantum** [comment]
应该是没有问题的，pypi/web/simple 是元数据端点，而 pypi-packages 是真正存储数据的仓库。用户将上游设置为 pypi/web/simple 时，返回的元数据会自动将用户重定向至 pypi-packages。
