### ISSUE TITLE
https://mirrors.sjtug.sjtu.edu.cn打不开，服务器挂了

### ISSUE THREAD

**Issue by haohetao** [sjtug/mirror-requests#361]
https://mirrors.sjtug.sjtu.edu.cn打不开，服务器挂了
![图片](https://github.com/sjtug/mirror-requests/assets/4592571/80832179-8a1c-4442-9798-7205963f390f)

**Comment by chenyuanrun** [comment]
我也访问不了

**Comment by siriusa51** [comment]
+1

**Comment by Touch-Night** [comment]
![image](https://github.com/sjtug/mirror-requests/assets/102669562/1dd22f57-3d6a-420a-b149-95afa2d82043)

**Comment by PhotonQuantum** [comment]
由于校园主干网络临时维护，我校镜像源公网服务于 2024年6月3日 至 2024年6月6日 中断，现已恢复正常。感谢您的关注与谅解！
