### ISSUE TITLE
pytorch支持intel新cpu Ultra 系列的python库

### ISSUE THREAD

**Issue by zh7314** [sjtug/mirror-requests#364]
镜像名:
[intel-extension-for-pytorch](https://github.com/Nuullll/intel-extension-for-pytorch)

上游路径:
https://github.com/Nuullll/intel-extension-for-pytorch/releases/download/v2.1.20%2Bmtl%2Boneapi/torch-2.1.0a0%2Bgit7bcf7da-cp310-cp310-win_amd64.whl

镜像简介:
A Python package for extending the official PyTorch that can easily obtain performance on Intel platform

国内其他镜像源同步情况:
目前国内是没有

同步方法:
缓存
镜像大小:

状态追踪:

- [x] 同意同步
- [x] 同步脚本
- [x] 部署到镜像源
- [x] 首次同步成功
- [ ] 测试脚本
- [ ] 使用文档
- [ ] 添加到官方源

**Comment by PhotonQuantum** [comment]
已经上线

**Comment by zh7314** [comment]
> 已经上线

非常感谢，经过测试我的intel Ultra 5 cpu的gpu性能很一般，甚至不如我以前的gtx970M 6G的游戏笔记本，做开发测试不行，哈哈哈哈
