### ISSUE TITLE
homebrew cask的几个子仓库已废弃

### ISSUE THREAD

**Issue by ADSWT518** [sjtug/mirror-requests#367]
如题，这三个子仓库已废弃，其中的包都迁移到了homebrew-cask主仓库。

https://github.com/Homebrew/homebrew-cask-fonts
https://github.com/Homebrew/homebrew-cask-drivers
https://github.com/Homebrew/homebrew-cask-versions

是不是可以考虑把对应的镜像也删除？

![image](https://github.com/sjtug/mirror-requests/assets/58338486/23ca47e1-faaa-49d5-91ba-0f2a3b59d0be)

**Comment by PhotonQuantum** [comment]
这些仓库里似乎有个 migrations 文件，保留是不是有助于兼容性？

**Comment by PhotonQuantum** [comment]
duplicate of #359
