### ISSUE TITLE
Debian jessie-update 的InRelease文件已过期

### ISSUE THREAD

**Issue by maptile** [sjtug/mirror-requests#37]
**类别**： Bug反馈

**镜像名**：

**上游路径**：https://mirrors.sjtug.sjtu.edu.cn/debian/dists/jessie-updates/InRelease

**镜像简介**：
无

**Bug描述**:
apt update时报错https://mirrors.sjtug.sjtu.edu.cn/debian/dists/jessie-updates/InRelease is expired (invalid since 5d 12h 43min 48s). Updates for this repository will not be applied.

经检查，报错信息中所指示的InRelease文件中的Valid-Until值为Tue, 05 Feb 2019 20:25:56 UTC
而当前日期已经是2019/02/11了，所以才有这个错误。

而SJTUG上显示： debian | 同步成功 | 2/11/2019, 5:45:14 PM

**Comment by htfy96** [comment]
debian源是反代ftp.sjtu.edu.cn的，联系colin老师处理

**Comment by maptile** [comment]
ftp.sjtu.edu.cn上海电信无法访问，另外colin老师是哪位。

**Comment by htfy96** [comment]
请问可以访问 http://ftp.sjtu.edu.cn/ 吗？我们这边已经联系了ftp的负责老师处理

**Comment by maptile** [comment]
可以访问ftp.sjtu.edu.cn了。估计是我网络问题。
另外不止交大的源有问题，科大也有问题。清华目前是正常的。

**Comment by htfy96** [comment]
科大源是系统盘炸了 交大这边5个监控点的连通性最近应该都是好的。ftp是在另一台机子上跑的老脚本，可能出了问题

**Comment by htfy96** [comment]
ftp.sjtu.edu.cn准备切换debian的上游，似乎是上游稳定性不行

**Comment by htfy96** [comment]
Fixed.
```
➜  ~ curl http://ftp.sjtu.edu.cn/debian/dists/jessie-updates/InRelease 2>/dev/null | grep -i valid
Valid-Until: Wed, 20 Feb 2019 08:36:07 UTC
```

有问题可以重新open

**Comment by maptile** [comment]
看到了，已经解决了。非常感谢
