### ISSUE TITLE
pop-os 镜像缺少最新的 24.04 版本的仓库资源

### ISSUE THREAD

**Issue by abcfy2** [sjtug/mirror-requests#379]
https://mirror.sjtu.edu.cn/pop-os/ 此目录下的子目录均缺少 `noble` 目录，而上游是存在的: https://apt.pop-os.org/

例如: https://apt.pop-os.org/release/dists/noble/

https://apt.pop-os.org/proprietary/dists/noble/

**Comment by truc0** [comment]
fixed by https://github.com/sjtug/mirror-docker-unified/pull/498
