### ISSUE TITLE
建议新增ubuntu-ports镜像

### ISSUE THREAD

**Issue by Akane195** [sjtug/mirror-requests#38]
**类别**：新增镜像

**镜像名**：ubuntu-ports

**上游路径**：http://ports.ubuntu.com/ubuntu-ports/

**镜像简介**：arm64, armhf, PowerPC, ppc64el, s390x架构的ubuntu软件源

**Comment by htfy96** [comment]
可能在ftp.sjtu.edu.cn上新增比较合适。我先问一下那边的情况

**Comment by skyzh** [comment]
由于 ubuntu-ports 比较大，需要 1TB 空间，我们可能在短期内不会新增这一镜像。（虽然已经写好了同步脚本）

**Comment by skyzh** [comment]
Will be available next month on ftp.sjtu.edu.cn
