### ISSUE TITLE
Flathub 更新错误：Invalid checksum for indexed summary

### ISSUE THREAD

**Issue by FortiterInRe** [sjtug/mirror-requests#384]
- 问题：
无法正常更新flatpak,所有相关软件已升级为最新，已尝试过`flatpak repair` `--no-static-deltas` 
`
wget https://mirror.sjtu.edu.cn/flathub/flathub.gpg
sudo flatpak remote-modify --gpg-import=flathub.gpg flathub
`均无效
-  错误：
```
flatpak -v update
F: No installations directory in /etc/flatpak/installations.d. Skipping
F: Opening system flatpak installation at path /var/lib/flatpak
F: Opening user flatpak installation at path /home/arch/.local/share/flatpak
Looking for updates…
F: Fetching summary index file for remote ‘flathub’
F: Loading https://mirror.sjtu.edu.cn/flathub/summary.idx using curl
F: Received 10001 bytes
F: Fetching indexed summary file 99945f74c5812f1063a2ef2fe84bb9c044304fb83591c53054f9dac350186467.gz for remote ‘flathub’
F: Loading https://mirror.sjtu.edu.cn/flathub/summaries/99945f74c5812f1063a2ef2fe84bb9c044304fb83591c53054f9dac350186467.gz using curl
F: Received 1324400 bytes
error: Invalid checksum for indexed summary 99945f74c5812f1063a2ef2fe84bb9c044304fb83591c53054f9dac350186467 for remote 'flathub'

``` 
- 环境：
Flatpak 1.15.10
OS: Arch Linux x86_64
Kernel: Linux 6.11.5-zen1-1.1-zen

**Comment by xe5700** [comment]
同样的问题

**Comment by jiangqingyuan** [comment]
同样的问题

**Comment by EdgyHammer** [comment]
我也遇到了

**Comment by bro-sin** [comment]
遇到了加一，但是感觉是临时抽风，过了一段时间，我再试又好了。看起来只能让时间抚平error

**Comment by FortiterInRe** [comment]
> 遇到了加一，但是感觉是临时抽风，过了一段时间，我再试又好了。看起来只能让时间抚平error

请问现在你那边正常吗，我这边就没成功过一次

**Comment by jiangqingyuan** [comment]
> > 遇到了加一，但是感觉是临时抽风，过了一段时间，我再试又好了。看起来只能让时间抚平error
> 
> 请问现在你那边正常吗，我这边就没成功过一次

我之前把东西全删了也只成功了一次，再也没成功。

**Comment by bro-sin** [comment]
> > 遇到了加一，但是感觉是临时抽风，过了一段时间，我再试又好了。看起来只能让时间抚平error
> 
> 请问现在你那边正常吗，我这边就没成功过一次

截至发布回复这会儿，我尝试了，还是失败，

**Comment by bro-sin** [comment]
> > > 遇到了加一，但是感觉是临时抽风，过了一段时间，我再试又好了。看起来只能让时间抚平error
> > 
> > 
> > 请问现在你那边正常吗，我这边就没成功过一次
> 
> 我之前把东西全删了也只成功了一次，再也没成功。

据说这个成功与否是与自身网络环境有关的，就是你的网络直接连接flathub没问题的话，就不会出这个问题，删东西应该没用，只能等你所在区域网络恢复到能直接连接flathub

**Comment by yatian-liu** [comment]
> > > > 遇到了加一，但是感觉是临时抽风，过了一段时间，我再试又好了。看起来只能让时间抚平error
> > > 
> > > 
> > > 请问现在你那边正常吗，我这边就没成功过一次
> > 
> > 
> > 我之前把东西全删了也只成功了一次，再也没成功。
> 
> 据说这个成功与否是与自身网络环境有关的，就是你的网络直接连接flathub没问题的话，就不会出这个问题，删东西应该没用，只能等你所在区域网络恢复到能直接连接flathub

也遇到了相同问题，但感觉你的解释有一点不合理，用sjtug的国内代理不就应该是不需要网络环境可以直接连flathub吗...

**Comment by yatian-liu** [comment]
> > > > 遇到了加一，但是感觉是临时抽风，过了一段时间，我再试又好了。看起来只能让时间抚平error
> > > 
> > > 
> > > 请问现在你那边正常吗，我这边就没成功过一次
> > 
> > 
> > 我之前把东西全删了也只成功了一次，再也没成功。
> 
> 据说这个成功与否是与自身网络环境有关的，就是你的网络直接连接flathub没问题的话，就不会出这个问题，删东西应该没用，只能等你所在区域网络恢复到能直接连接flathub

也遇到了相同问题，但感觉你的解释有一点不合理，用sjtug的国内代理不就应该是不需要网络环境可以直接连flathub吗...

**Comment by senseab** [comment]
好像 flatpak 从镜像站下载的 summary 文件会比从官方下载的多了几个字节……

```
F: Loading https://mirror.sjtu.edu.cn/flathub/summaries/cf3f0b108f7342f24378203f534a17329480681ce5a876afcc04c7de69c0326f.gz using curl
F: Received 1338918 bytes
```
这个文件的实际字节数是 1335766 字节

`99945f74c5812f1063a2ef2fe84bb9c044304fb83591c53054f9dac350186467.gz` 这个文件实际只有 1321455 字节

**Comment by 1nj0k** [comment]
https://github.com/curl/curl/issues/15509

应该是 curl 的问题，今天更新 curl 8.11.1 后好了

**Comment by FortiterInRe** [comment]
确实是curl的问题，更新后升级正常
