### ISSUE TITLE
debian-cdimage 错误跳转

### ISSUE THREAD

**Issue by bin456789** [sjtug/mirror-requests#386]
https://mirror.sjtu.edu.cn/debian-cdimage/ 跳转到了
https://ftp.sjtu.edu.cn/debian-cd/

**Comment by truc0** [comment]
已确认，今晚修复

**Comment by RevySR** [comment]
似乎是相同问题

https://mirror.sjtu.edu.cn/debian 直接重定向到 https://ftp.sjtu.edu.cn/debian/ 就不可访问了

**Comment by truc0** [comment]
> 似乎是相同问题
> 
> https://mirror.sjtu.edu.cn/debian 直接重定向到 https://ftp.sjtu.edu.cn/debian/ 就不可访问了

有具体的日志或截图吗？我这边显示正常

**Comment by truc0** [comment]
目前的问题均已修复，如果仍显示错误可以重新评论。
