### ISSUE TITLE
请求新增Kubernetes镜像

### ISSUE THREAD

**Issue by Rainy99** [sjtug/mirror-requests#39]
**类别**：新增镜像

**镜像名**：Kubernetes

**上游路径**：https://packages.cloud.google.com

**镜像简介**：Kubernetes是用于自动部署、扩展和管理容器化应用程序的开源系统。该系统由Google设计并捐赠给Cloud Native Computing Foundation来使用。 它旨在提供“跨主机集群的自动部署、扩展以及运行应用程序容器的平台”。 它支持一系列容器工具, 包括Docker等。

**Comment by skyzh** [comment]
k8s-gcr-io.mirrors.sjtug.sjtu.edu.cn will be available next month.
