### ISSUE TITLE
Promethus 监控

### ISSUE THREAD

**Issue by htfy96** [sjtug/mirror-requests#40]
现在的镜像暴露出了promethus监控地址
- Caddy： https://metrics.mirrors.sjtug.sjtu.edu.cn/ 
- node: http://mirrors.sjtug.sjtu.edu.cn:9190/metrics

之前的dashboard挂了，需要找一台机子来监控情况

**Comment by htfy96** [comment]
promethus + grafana which fetches mirrors.sjtug.sjtu.edu.cn/.....

**Comment by htfy96** [comment]
add grafana -> telegram bot

**Comment by skyzh** [comment]
Will be solved in tomorrow's update.
