### ISSUE TITLE
请求增加gentoo rsync mirror

### ISSUE THREAD

**Issue by aceforeverd** [sjtug/mirror-requests#41]
**类别**：新增镜像

**镜像名**：gentoo-portage

**上游路径**：rsync://rsync.gentoo.org/gentoo-portage

**镜像简介**：Gentoo ebuilds repository
+ [gentoo rync mirror](https://gentoo.org/support/rsync-mirrors/), tuna gentoo-portage is in the official list
 + Setup: [Infrastructure/Mirrors/Rsync](https://wiki.gentoo.org/wiki/Project:Infrastructure/Mirrors/Rsync)

**Comment by htfy96** [comment]
rsync mirror需要跑rsyncd

**Comment by aceforeverd** [comment]
所以支持rsync还差了什么？

**Comment by htfy96** [comment]
需要额外起一个容器跑rsyncd

**Comment by aceforeverd** [comment]
> 需要额外起一个容器跑rsyncd

那我有空学习一波

**Comment by aceforeverd** [comment]
https://mirrors.sjtug.sjtu.edu.cn/gentoo 已经是 ebuilds mirror, 好像加个 rsyncd 就可以？
