### ISSUE TITLE
2019.03.31 镜像站无法访问

### ISSUE THREAD

**Issue by specter119** [sjtug/mirror-requests#43]
**类别**：Bug

<https://mirrors.sjtug.sjtu.edu.cn> 无法访问，Arch源报错连接超时。

**Comment by SkyZH** [comment]
正在处理中

**Comment by SkyZH** [comment]
疑似 Caddy 卡住

**Comment by htfy96** [comment]
enp2s0网口挂了，正在维修

**Comment by htfy96** [comment]
已经修复。之后有条件最好能够上一台备用机设置成304 redirect所有流量，出了问题直接把DNS指过去
