### ISSUE TITLE
Archlinux CentOS 等反代源根目录超链接错误

### ISSUE THREAD

**Issue by SkyZH** [sjtug/mirror-requests#45]
**类别**：Bug 反馈

https://mirrors.sjtug.sjtu.edu.cn/archlinux

点击 `iso` 文件夹跳转到 https://mirrors.sjtug.sjtu.edu.cn/iso

**Comment by htfy96** [comment]
没问题……因为正确的地址是 https://mirrors.sjtug.sjtu.edu.cn/archlinux/ 而不是 https://mirrors.sjtug.sjtu.edu.cn/archlinux 。也许可以配一下自动canonicalize url...

**Comment by SkyZH** [comment]
duplicate of #49
