### ISSUE TITLE
限制 Anaconda 镜像访问

### ISSUE THREAD

**Issue by skyzh** [sjtug/mirror-requests#47]
**类别**：Bug 反馈

For legal reasons, we may restrict access to Anaconda only to SJTU users.

- [x] acquire SJTU CIDR
- [ ] Caddy config
- [ ] Test and deploy

**Comment by htfy96** [comment]
Also need to update anaconda help file at https://github.com/sjtug/portal/blob/master/content/post/mirror-help/anaconda.md

**Comment by SkyZH** [comment]
- [ ] Update anaconda help and update frontend

**Comment by njzjz** [comment]
I hope that ECNU users can access it. ❤

**Comment by SkyZH** [comment]
@njzjz You may provide CIDR of ENCU.

**Comment by njzjz** [comment]
@SkyZH 
202.120.80.0 - 202.120.95.255 CERNET
219.228.56.1 - 219.228.63.255 CERNET
59.78.176.1 - 59.78.199.255 CERNET
222.66.117.0 - 222.66.117.255 China Telecom
2001:0DA8:8005:0000:: - 2001:0DA8:8005:FFFF:: CERNET2

Thank you!

**Comment by SkyZH** [comment]
Shanghai Jiao Tong University CIDR: https://bbs.sjtu.edu.cn/bbscon,board,SJTUnet,file,M.1025875031.A.html

**Comment by genggui001** [comment]
ECUST的同学同求帮助

**Comment by xiaolinpan** [comment]
i'am also a ecnuer, please help me too 
219.228.135.0-219.228.135.255
219.228.63.0-219.228.63.255
58.198.182.0-58.198.182.255

thank you!!!

**Comment by Gin-Wang** [comment]
交大附属医院好像不在里面，惨

**Comment by qzchenwl** [comment]
交大的源也要下了....，看来必须自己搭私服了，请问conda源镜像怎么搭呢？

**Comment by SkyZH** [comment]
@qzchenwl https://github.com/sjtug/mirror-docker/tree/v2/lug/worker-script
