### ISSUE TITLE
anaconda 404故障

### ISSUE THREAD

**Issue by busbyjrj** [sjtug/mirror-requests#49]
**类别**：Bug反馈

anaconda源，所有的官方help内容，直接复制均为404，例如：
pkgs/free: conda config --add channels https://mirrors.sjtug.sjtu.edu.cn/anaconda/pkgs/free
直接访问、anaconda更新时，均会跳转到https://mirrors.sjtug.sjtu.edu.cn/pkgs/free/，该链接会返回404，须在软件库的名称后添加“/”才能正常访问。
但，即使添加了“/”，在anaconda中使用，仍然会默认回到不带有“/”的域名，返回404故障。

**Comment by SkyZH** [comment]
今天中午在添加 packagist 镜像的时候似乎出了一点意外。正在处理中。

**Comment by SkyZH** [comment]
另外由于 #47，我们在后面几周可能限制 anaconda 源的访问（

**Comment by htfy96** [comment]
https://github.com/mholt/caddy/issues/2555

**Comment by busbyjrj** [comment]
我也是因为tuna的原因才找到了隔壁的源，虽然不是很了解最近发生了什么情况，但希望能够继续使用你们的镜像，祝你们顺利

**Comment by SkyZH** [comment]
「直接访问跳转到根目录」是预期行为，应该只会对直接浏览的人产生影响。

这边测试下来 conda 是可以下载包的，建议你清理一下 conda 的缓存。

![image](https://user-images.githubusercontent.com/4198311/56434568-b2f78e80-6307-11e9-813b-ad8134d57f28.png)

**Comment by SkyZH** [comment]
404 可以附一下 log。

**Comment by busbyjrj** [comment]
```
raise UnavailableInvalidChannel(Channel(dirname(url)), status_code)
conda.exceptions.UnavailableInvalidChannel: The channel is not accessible or is invalid.
  channel name: anaconda/pkgs/msys2
  channel url: https://mirrors.sjtug.sjtu.edu.cn/anaconda/pkgs/msys2
  error code: 404
```

```
default_python: None
ssl_verify: True
channels:
  - https://mirrors.sjtug.sjtu.edu.cn/anaconda/pkgs/msys2
  - https://mirrors.sjtug.sjtu.edu.cn/anaconda/pkgs/mro
  - https://mirrors.sjtug.sjtu.edu.cn/anaconda/pkgs/main
  - https://mirrors.sjtug.sjtu.edu.cn/anaconda/pkgs/free
  - defaults
show_channel_urls: True
```
我清除conda缓存后仍然是404的问题。

**Comment by SkyZH** [comment]
已复现。看起来 Caddy 发了 301 进行了重定向，的确是 Caddy 的问题……
