### ISSUE TITLE
请求为 conda 源增加 atztogo 频道

### ISSUE THREAD

**Issue by specter119** [sjtug/mirror-requests#50]
**类别**：
新增镜像

**镜像名**：
conda 源 atztogo 频道
**上游路径**：
https://anaconda.org/atztogo
**镜像简介**：
atztogo 是 phonopy和phono3py的作者，他的2个包在声子计算方面的应用非常广泛，里面只有3个包，不会有多大。

同时，viscid-hub 那个频道方便申请删除了么，mayavi 通过 viscid-hub频道安装也很搞到能work的环境，我还是自己确定好解决方案再申请添加合适的仓库吧。

**Comment by SkyZH** [comment]
发了 PR，可能过几天上线吧（

**Comment by specter119** [comment]
@SkyZH 好的，谢谢。

**Comment by SkyZH** [comment]
已经上线了，欢迎测试 @specter119
