### ISSUE TITLE
flutter_infra 404 Not Found

### ISSUE THREAD

**Issue by 1170337548** [sjtug/mirror-requests#54]
**类别**：Bug反馈

**镜像名**：

**上游路径**：

**镜像简介**：

Download failed.
URL: https://mirrors.sjtug.sjtu.edu.cn//flutter_infra/flutter/52c7a1e849a170be4b2b2fe34142ca2c0a6fea1f/android-arm-profile/windows-x64.zip
Error: 404 Not Found

**Comment by htfy96** [comment]
#34 。请问在：
```
export FLUTTER_STORAGE_BASE_URL=https://mirrors.sjtug.sjtu.edu.cn
```
之后可以正常下载吗？

**Comment by 1170337548** [comment]
之前环境变量一直是这个，今天出现这个问题，试了几次还是失败的。后面我把变量删除 flutter doctor处理之后再换回该镜像源，最终问题解决了
