### ISSUE TITLE
debian-security 未完全同步 部分文件缺失

### ISSUE THREAD

**Issue by asdf12303116** [sjtug/mirror-requests#58]
**类别**：Bug反馈

E: Failed to fetch https://mirrors.sjtug.sjtu.edu.cn/debian-security/dists/buster/updates/main/i18n/by-hash/SHA256/38e4f47a3363ed07b57800e4eefc272b9c63e08bb92a1e8f4776856e8086c567
404  Not Found

**Comment by skyzh** [comment]
SJTUG 镜像源的 debian-security 直接反代了 SJTU 网络中心的镜像源 (http://ftp.sjtu.edu.cn/)。我们需要等待上游修复。
