### ISSUE TITLE
使用帮助由于同源政策无法在部分浏览器上正常显示

### ISSUE THREAD

**Issue by YRainbbbb** [sjtug/mirror-requests#59]
**类别**：
Bug

**镜像名**：

**上游路径**：

**镜像简介**：

**Comment by skyzh** [comment]
实测可以点进去，并且可以加载出内容。如果使用帮助无法打开的话，是浏览器的同源政策原因，用 Chrome 即可解决。

**Comment by YRainbbbb** [comment]
static.crates.io   rust-static   crates.io这三个都进不去，前两个进去之后是xml的一个页面，而且换了Firefox浏览器也是这样，第三个进去是一个容器的跳转页面。。。

**Comment by skyzh** [comment]
crates.io 反向代理了 https://crates.io/api , rust-static 和 static.crates.io 的原站根目录返回值就是 xml。经检查这三个镜像和预期结果是一样的。所以需要解决的就是帮助在非 Chrome 浏览器显示不出来的问题。我更改了 issue 的标题。

**Comment by skyzh** [comment]
Duplicated: #69 . Close an earlier issue as #69 provides more information.
