### ISSUE TITLE
疑似数据泄露

### ISSUE THREAD

**Issue by wangqr** [sjtug/mirror-requests#61]
**类别**：Bug 反馈

https://twitter.com/isukkaw/status/1181989528069795841

> 某高校镜像站将 Log 全部交给第三方 Log 处理平台处理，页面甚至没有任何鉴权。。
通过日志可以发现，该高校镜像站的 PyPi 甚至使用了 V2Ray 反代。
dig 一下甚至能发现这所高校的 LUG 架设的另外两台 V2Ray 服务器。。。

**Comment by skyzh** [comment]
感谢您的反馈。

**Comment by htfy96** [comment]
Log key revoked

**Comment by htfy96** [comment]
使用V2ray服务器的设计已经写在了[开源版本的配置文件中](https://github.com/sjtug/mirror-docker)。之前推主能够得到服务器地址是因为服务器的子域名由于log泄漏而被人发现

**Comment by htfy96** [comment]
在发布公告后再Close这个issue，还需要做的事情有：
- 更换所有使用的v2ray服务器的IP和域名
- 向日志服务商获取使用Access token访问的人员及内容
- 发布公告

**Comment by htfy96** [comment]
https://sjtug.org/post/mirror-news/2019-10-10-data-leak/
