### ISSUE TITLE
2019.10.14 整个镜像站无法访问

### ISSUE THREAD

**Issue by specter119** [sjtug/mirror-requests#62]
**类别**：
bug

**镜像名**：

**上游路径**：

**镜像简介**：

**Comment by htfy96** [comment]
#36. 

这个问题在插件最新版已经修复。但由于Caddy升级到1.x后 一些需要的别的插件无法Build，所以暂时跑的还是0.11版本的旧Build Caddy。

有几个解决方向：
- 解决自动重启不生效的问题
- 试图把caddy新版不build的问题[报告上游](https://caddy.community/t/failed-to-download-prebuilt-binary/6368)
- 试图Build 0.11版本 w/ new plugin
