### ISSUE TITLE
请求增加Cargo的镜像

### ISSUE THREAD

**Issue by INFCode** [sjtug/mirror-requests#63]
**类别**：新增镜像

**镜像名**：cargo

**上游路径**：https://crates.io/

**镜像简介**：cargo是rust社区推荐使用的第三方包管理器，它同时提供了rust的工作流程管理，极大地方便了rust用户的使用，对于rust开发非常重要。

**Comment by skyzh** [comment]
https://mirrors.sjtug.sjtu.edu.cn/static.crates.io/

**Comment by skyzh** [comment]
https://mirrors.sjtug.sjtu.edu.cn/crates.io/
