### ISSUE TITLE
建议新增anaconda.cloud中的ngsolve镜像

### ISSUE THREAD

**Issue by liubenyuan** [sjtug/mirror-requests#65]
**类别**：新增anaconda.cloud中的ngsolve镜像

**镜像名**：ngsolve

**上游路径**：https://anaconda.org/ngsolve

**镜像简介**：ngsolve和netgen是有限元数值计算及网格剖分的库，拥有较好的Python接口，可以用于日常的科学计算及工程。

**Comment by specter119** [comment]
@liubenyuan 大约，好像，自己改下 https://github.com/sjtug/mirror-docker/blob/v2/lug/config.example.yaml 再 pr 就可以？

**Comment by liubenyuan** [comment]
好，我试一试哈。。。

**Comment by specter119** [comment]
@liubenyuan 你似乎 PR 给了自己。。。

**Comment by liubenyuan** [comment]
不好意思哈~~
