### ISSUE TITLE
js.map文件未清除

### ISSUE THREAD

**Issue by qinghon** [sjtug/mirror-requests#66]
**类别**：Bug反馈

网页的*.js.map文件未过滤,
虽然也不影响什么

**Comment by skyzh** [comment]
好的，我们下次部署的时候去掉 .map（

**Comment by skyzh** [comment]
@htfy96 的建议:

1. 现在有sentry自动group前端的error，依赖于sourcemap
2. 前端代码本来就是开源的
3. 浏览器在打开devtool的时候才会加载sourcemap

所以我刚刚把 PR revert 了（
