### ISSUE TITLE
Maven仓库需要https连接

### ISSUE THREAD

**Issue by liuzhilong** [sjtug/mirror-requests#68]
**类别**：Bug反馈
目前使用<https://mirrors.sjtug.sjtu.edu.cn/maven-central/>，会报如下错误：
>501 HTTPS Required. 
Use https://repo.maven.apache.org/maven2/
More information at https://links.sonatype.com/central/501-https-required

[这里](https://support.sonatype.com/hc/en-us/articles/360041287334)是sonatype关于这个问题的说明，是从2020.01.15开始要求https的

**Comment by skyzh** [comment]
谢谢！我们已经修复了这个 bug，在下一次部署中就会生效。

**Comment by liuzhilong** [comment]
好的谢谢
