### ISSUE TITLE
镜像站主页在 Firefox 和 Edge 浏览器下无法显示帮助选项

### ISSUE THREAD

**Issue by gmg137** [sjtug/mirror-requests#69]
Bug 反馈:
如图，在firefox 浏览器下所有帮助选项会一直显示为加载状态。
![2020-04-28 17-18-26 的屏幕截图](https://user-images.githubusercontent.com/6460323/80470474-a4a96d00-8974-11ea-8265-3f9bf8808db4.png)

**Comment by skyzh** [comment]
这是一个已知 issue，Safari 也用同样的问题。主要是 CDN 的同源限制导致的。之前有试着调过，但似乎没折腾成功（

**Comment by gmg137** [comment]
很抱歉，因为是通过镜像站首页直接跳转到这里，没有看到之前已经有人提了。

话说不能把帮助信息直接写到静态页面里吗?

**Comment by skyzh** [comment]
（说的好有道理啊……之后可以考虑在 travis ci build 的时候就把帮助打包进去。

**Comment by skyzh** [comment]
已修复。
