### ISSUE TITLE
网站备案

### ISSUE THREAD

**Issue by htfy96** [sjtug/mirror-requests#7]
**类别**：Bug反馈

接到网络信息中心反馈，mirrors.sjtug.org需要备案。

由于镜像源本身的特性，个人单独在sjtug.org下备案难度较大。因此选择将域名切换到mirrors.sjtu.edu.cn，在校内利用二级域名备案，规则见https://net.sjtu.edu.cn/wlfw/ym.htm。原来的mirrors.sjtug.org 301到新的域名。

之后需要与赖老师发封邮件讨论一下这件事情怎么做，会抄送给 @Evensgn 之后负责

**Comment by htfy96** [comment]
目前mirrors.sjtug.org暂时关闭解析，待备案完成后重新开启

**Comment by specter119** [comment]
@htfy96 有啥换域名的update不？

**Comment by htfy96** [comment]
暂时没有，我问下Colin老师2018年4月28日 下午11:42，KeLiu <notifications@github.com>写道：@htfy96 有啥换域名的update不？

**Comment by htfy96** [comment]
备案完成。现在可以在https://mirrors.sjtug.sjtu.edu.cn访问！
