### ISSUE TITLE
镜像更新Bug

### ISSUE THREAD

**Issue by h3fang** [sjtug/mirror-requests#71]
**类别**：Bug

网页显示镜像正常更新
<img width="360" alt="screenshot_2020-06-30_09-07-01" src="https://user-images.githubusercontent.com/1715589/86071231-55390780-bab1-11ea-85bf-c7b98c8d17f6.png">

但实际上镜像已经好几天没有更新了
<img width="390" alt="screenshot_2020-06-30_09-07-39" src="https://user-images.githubusercontent.com/1715589/86071275-6f72e580-bab1-11ea-9f0b-7e67399ce210.png">

`sudo pacman -Syu` 也没有获取到更新

**Comment by skyzh** [comment]
已经确认这个问题。由于 archlinux 源是反代我校网络中心的 http://ftp.sjtu.edu.cn/archlinux/ ，我们已经向学校反映。

**Comment by skyzh** [comment]
网络中心选择的上游 mirrors.kernel.org 自 6/25 起就没有更新了，因此导致了这个问题。

**Comment by h3fang** [comment]
那我先用别的源顶上吧
