### ISSUE TITLE
openSUSE 镜像从网页端访问 404 Not Found

### ISSUE THREAD

**Issue by IceNature** [sjtug/mirror-requests#73]
**类别**：
bug

openSUSE 镜像网页端连接指向 
https://mirrors.sjtug.sjtu.edu.cn/opensuse/
无论是直接访问此地址还是点击镜像站网页连接访问，都会跳转至
https://mirrors.sjtug.sjtu.edu.cn/opensuse/mirrors.sjtug.sjtu.edu.cn/opensuse/
显示 404 Not Found
Firefox 和 Microsoft Edge 均出现此问题

**镜像名**：

**上游路径**：

**镜像简介**：

**Comment by htfy96** [comment]
重定向的bug，我们会尽快修复

**Comment by htfy96** [comment]
应该已经修复了，[清除一下浏览器301重定向缓存](https://stackoverflow.com/questions/9130422/how-long-do-browsers-cache-http-301s)即可
