### ISSUE TITLE
Pop!_OS

### ISSUE THREAD

**Issue by PENGBLACKLEGS** [sjtug/mirror-requests#79]
**类别**：新增镜像

**镜像名**：Pop!_OS

**上游路径**：https://pop.system76.com/

**镜像简介**：Pop!_OS is an operating system for STEM and creative professionals who use their computer as a tool to discover and create. Unleash your potential on secure, reliable open source software. Based on your exceptional curiosity, we sense you have a lot of it.

**Comment by skyzh** [comment]
感谢您的建议。请问具体的 repo 地址是什么呢？

**Comment by skyzh** [comment]
upstream: https://apt.pop-os.org/ubuntu/

**Comment by winnochan** [comment]
@skyzh 我在#89中备注错了, 上游应该是https://apt.pop-os.org/proprietary/, 这个主页有说明: https://apt.pop-os.org/, 不过我还不清楚怎么同步.

**Comment by istomyang** [comment]
> upstream: https://apt.pop-os.org/ubuntu/

你好，请问是否考虑该源?

**Comment by istomyang** [comment]
> @skyzh 我在#89中备注错了, 上游应该是https://apt.pop-os.org/proprietary/, 这个主页有说明: https://apt.pop-os.org/, 不过我还不清楚怎么同步.

只要提供源地址即可，不需要提供具体怎么同步，这是他们后端的事情。进 /etc/apt  找一找把地址告诉他就行。

**Comment by skyzh** [comment]
@istomyang 

> 不需要提供具体怎么同步

恰恰是因为这个源没有提供 rsync 服务，我们也没有 apt 直接同步的工具，所以可能暂时没法上线。（后面几个月一定？

**Comment by heheda123123** [comment]
不用单独加镜像，pop os 的包都放在launchpad上的, 用sjtug的反代就行了
```
https://launchpad.net/~system76/+archive/ubuntu/pop

```

**Comment by heheda123123** [comment]
能做反代吗

**Comment by heheda123123** [comment]
https://mirrors.tk/help/pop-os/
这里有个pop os的镜像站了，但是是依靠白嫖大厂免费资源建立的开源软件镜像站，速度这些不够稳定
https://github.com/mirrors-tk

**Comment by PhotonQuantum** [comment]
我们一般使用 rsync 来同步 apt 仓库，历史上曾经有尝试用 http 同步导致 IP 被上游封禁的现象。如果上游不提供 rsync 服务，我们同步起来会比较困难。反代的话根据政策原因我们原则上避免。

**Comment by heheda123123** [comment]
> 我们一般使用 rsync 来同步 apt 仓库，历史上曾经有尝试用 http 同步导致 IP 被上游封禁的现象。如果上游不提供 rsync 服务，我们同步起来会比较困难。反代的话根据政策原因我们原则上避免。

或者基于http从mirrors-tk同步可行吗 https://github.com/mirrors-tk/feedback/issues/14

**Comment by heheda123123** [comment]
不过说到这个，mirrors-tk前面也都是用http同步的，运作了很长一段时间了，并没有遇到封禁的情况

**Comment by PhotonQuantum** [comment]
主要有三个问题:
1. 没有很好的同步方法，看 mirrors-tk 是直接用 rclone 走 http 同步的，会有被封的风险
2. 私有软件可能有再分发的风险，除了 nvidia 以外，还有 chrome plex discord 等，不知道会不会有问题
3. 暂时没找到对方仓库维护者的联系方式，无法询问以上事由

**Comment by heheda123123** [comment]
> 

或许可以在popos的github仓库提issue？需要代劳吗？ https://github.com/pop-os/pop

**Comment by PhotonQuantum** [comment]
已经在 chat.pop-os.org 上询问，等待上游回复

**Comment by PhotonQuantum** [comment]
上游回复建议使用 apt-mirror 进行镜像。我们现在暂时没有接入这套工具的基础设施，下次一定😇

**Comment by heheda123123** [comment]
> 上游回复建议使用 apt-mirror 进行镜像。我们现在暂时没有接入这套工具的基础设施，下次一定😇

明年我再来问问（：

**Comment by PhotonQuantum** [comment]
正在进行初期同步
ISO 网传 S3 地址已经失效，找不到别的地址，就不进行镜像了

**Comment by PhotonQuantum** [comment]
镜像已经上线
@heheda123123 方便给我们的帮助文档 https://github.com/sjtug/portal 和 https://github.com/mirrorz-org/mirrorz-help 提交帮助吗？

**Comment by heheda123123** [comment]
> 镜像已经上线 @heheda123123 方便给我们的帮助文档 https://github.com/sjtug/portal 和 https://github.com/mirrorz-org/mirrorz-help 提交帮助吗？

没问题

**Comment by heheda123123** [comment]
同步好像有点问题，我看首页提示同步完成，但是这两个路径下文件夹有些不一样 ，少了 binary-i386 和 source
https://mirror.sjtu.edu.cn/pop-os/release/dists/jammy/main/
https://apt-origin.pop-os.org/release/dists/jammy/main/

source可以不开启，关闭deb-src就行，但是i386的应该是必须的，估计有些32位软件依赖。
应该是arch这里得加上i386
![image](https://github.com/sjtug/mirror-requests/assets/97490782/f305484f-18f1-45d7-b4a6-61e0f3136066)

**Comment by PhotonQuantum** [comment]
思考 确实没有同步 i386，可能因为我看到最近几个版本都没打什么 i386 包，稍后添加

**Comment by heheda123123** [comment]
> 思考 确实没有同步 i386，可能因为我看到最近几个版本都没打什么 i386 包，稍后添加

popos最近更新都不勤，说是投入精力也去搞桌面去了，疯狂造轮子中
“[为开发新版 Rust 桌面环境，Pop!_OS 将跳过 22.10 版本](https://www.oschina.net/news/211791/no-pop-os-22-10)”

**Comment by heheda123123** [comment]
同步还有点问题，这个路径下少了些东西
https://mirror.sjtu.edu.cn/pop-os/release/dists/jammy/main/dep11/
https://apt-origin.pop-os.org/release/dists/jammy/main/dep11/
![image](https://github.com/sjtug/mirror-requests/assets/97490782/b734e3a8-6be9-4bb5-b2ca-80222d04c156)

**Comment by PhotonQuantum** [comment]
确认是上游的问题 https://github.com/apt-mirror/apt-mirror/issues/102
apt-mirror 看上去是没法用了 得想点别的办法

**Comment by heheda123123** [comment]
github上apt-mirror最新的commit也不行嘛？

**Comment by PhotonQuantum** [comment]
已经尝试修复

**Comment by heheda123123** [comment]
> 镜像已经上线 @heheda123123 方便给我们的帮助文档 https://github.com/sjtug/portal 和 https://github.com/mirrorz-org/mirrorz-help 提交帮助吗？

不过给mirrorz-help提交pr我有点没看懂。  
看了下其他的pr，比如openbsd这个，一是mdx中写了描述信息，二是route.json里面写了路由信息，但是我怎么设置有哪些镜像支持这个发行版呢，像现在pop-os只有sjtug支持该怎么写呢？
不用管这个，会自动匹配嘛？
要不老哥你来好了，修改命令我已经pr到sjtug的帮助文件了
![image](https://github.com/sjtug/mirror-requests/assets/97490782/409cc750-d130-4213-afee-0e402c759e2c)

**Comment by taoky** [comment]
> 不过给mirrorz-help提交pr我有点没看懂。 看了下其他的pr，比如openbsd这个，一是mdx中写了描述信息，二是route.json里面写了路由信息，但是我怎么设置有哪些镜像支持这个发行版呢，像现在pop-os只有sjtug支持该怎么写呢？ 不用管这个，会自动匹配嘛？

是。匹配可以在 https://mirrorz.org/list 看，比如说这一项目前对应的是 <https://mirrorz.org/list/pop-os>。

**Comment by heheda123123** [comment]
> > 不过给mirrorz-help提交pr我有点没看懂。 看了下其他的pr，比如openbsd这个，一是mdx中写了描述信息，二是route.json里面写了路由信息，但是我怎么设置有哪些镜像支持这个发行版呢，像现在pop-os只有sjtug支持该怎么写呢？ 不用管这个，会自动匹配嘛？
> 
> 是。匹配可以在 https://mirrorz.org/list 看，比如说这一项目前对应的是 https://mirrorz.org/list/pop-os。

![image](https://github.com/sjtug/mirror-requests/assets/97490782/501d88c4-a42d-4035-a340-6aaf5702230e)
有点问题，比如对于openbsd
{{http_protocol}}{{mirror}}
{{http_protocol}} 对应https://
{{mirror}} 对应mirrors.tuna.tsinghua.edu.cn/OpenBSD/
但是现在对于pop-os而言得下面这样替换
```
sed -i 's@http://apt.pop-os.org/@https://mirror.sjtu.edu.cn/pop-os/@g' /etc/apt/sources.list.d/pop-os-apps.sources
sed -i 's@http://apt.pop-os.org/@https://mirror.sjtu.edu.cn/pop-os/@g' /etc/apt/sources.list.d/pop-os-release.sources
sed -i 's@http://apt.pop-os.org/@https://mirror.sjtu.edu.cn/@g' /etc/apt/sources.list.d/system.sources
```
第三个是没有/pop-os/这个路径的，该怎么写呢？

**Comment by ZenithalHourlyRate** [comment]
> 第三个是没有/pop-os/这个路径的，该怎么写呢？

按我以前对 pop-os 的了解，这是指向 ubuntu 的；这种情况下您可以参考 https://github.com/mirrorz-org/mirrorz-help/blob/master/contents/debian.mdx#openmediavault 这一节

**Comment by heheda123123** [comment]
> > 第三个是没有/pop-os/这个路径的，该怎么写呢？
> 
> 按我以前对 pop-os 的了解，这是指向 ubuntu 的；这种情况下您可以参考 https://github.com/mirrorz-org/mirrorz-help/blob/master/contents/debian.mdx#openmediavault 这一节

是的 http://apt.pop-os.org/ubuntu 就是 popos 官方做的到 ubuntu 的镜像.
参考这个链接好像也没解决这个问题
比如对于 pop-os， {{mirror}} 指向了 mirror.sjtu.edu.cn/pop-os/ ，问题是现在不需要最后的 /pop-os/
有没有伪指令是直接指向 mirror.sjtu.edu.cn 这种域名的呢？

**Comment by ZenithalHourlyRate** [comment]
在 mirrorz-help 中这种涉及多个 repo 的应该写多个文件

在 `pop-os.mdx` 中

```bash
sed -i 's@http://apt.pop-os.org/@{{http_protocol}}{{mirror}}/@g' /etc/apt/sources.list.d/pop-os-apps.sources
sed -i 's@http://apt.pop-os.org/@{{http_protocol}}{{mirror}}/@g' /etc/apt/sources.list.d/pop-os-release.sources
```

然后加上到 ubuntu.mdx 的链接，并在 `ubuntu.mdx` 中单独增加一节

```bash
sed -i 's@http://apt.pop-os.org/ubuntu/@{{http_protocol}}{{mirror}}@g' /etc/apt/sources.list.d/system.sources
```

**Comment by PhotonQuantum** [comment]
由于 popos 镜像已经上线，且已经有初步文档，现关闭这一 issue。关于 mirrorz-help 的讨论请移步上游进行。
