### ISSUE TITLE
建议新增 AUR 镜像

### ISSUE THREAD

**Issue by shrubbroom** [sjtug/mirror-requests#80]
**类别**： 新增镜像

**镜像名**：AUR

**上游路径**：https://aur.archlinux.org/

**镜像简介**：AUR 是 Archlinux 社区用户软件仓库，旨在以社区为主导，在 Arch 用户间分享 PKGBUILD。在大陆地区尽管有 TUNA 镜像，但最近在部分地区出现帮助页面访问问题 [#896](https://github.com/tuna/issues/issues/896) 及镜像连接问题 [#886](https://github.com/tuna/issues/issues/886)，且 TUNA 源本身访问速度也较慢。新增镜像能增强 Arch 用户及 Manjaro 用户访问AUR源的体验，同时分散 TUNA 源压力。

**Comment by skyzh** [comment]
cc @PhotonQuantum PTAL

**Comment by PhotonQuantum** [comment]
由于 AUR 的性质，其并不适合做成镜像，而更适合做成反代。
考虑之后为 aur.archlinux.org 提供反代服务。

**Comment by specter119** [comment]
+1 AUR 还是反代吧。

**Comment by 1900011604** [comment]
清华TUNA源是镜像还是反代呢？

**Comment by skyzh** [comment]
> 清华TUNA源是镜像还是反代呢？

应该是反代

**Comment by specter119** [comment]
> **镜像简介**： ... 在 Arch 用户间分享打好的软件包。...

忽然觉得这句话有~纰漏~软肋，是分享打包的脚本，不是分享打好的包，打好的包是 Archlinux-cn 了。还有 Manjaro 最近已经凉凉了。

**Comment by 1900011604** [comment]
怎么凉了，我用交大单一镜像```sudo pacman -Syyu```照样很好啊

**Comment by specter119** [comment]
@1900011604 论坛挂了一周大概。

**Comment by 1900011604** [comment]
> @1900011604 论坛挂了一周大概。

**昨晚上看到发现好啦，赶紧注册吧，爷青回！**

**Comment by Sicalxy** [comment]
> 下了pkgbuild，里面的tar包下不鸟，还需要解决网的问题。所以反代了应该也不是特别有用的样子。

检查 PKGBUILD 是个好习惯，检查时可以顺便改一下 source 地址的镜像、版本号等

**Comment by PhotonQuantum** [comment]
由于 AUR 源内有大量 ugc，且当前镜像架构对反代不友好，且考虑到 tuna 也因类似原因关闭 aur 反代，我们决定暂不收录 aur 镜像。
