### ISSUE TITLE
flathub.org

### ISSUE THREAD

**Issue by bhuztez** [sjtug/mirror-requests#86]
镜像名: flathub.org

上游路径、镜像简介、国内其他镜像源同步情况、同步方法:

参考 https://github.com/tuna/issues/issues/523 讨论

**Comment by skyzh** [comment]
同步工具没什么问题。看了下 tuna 的讨论，下面两个问题可能还需要解决：
1. 镜像多大？虽然 actively used data 只有 50-70GB，但全量同步可能会比这个大得多。
2. 镜像时，如果需要通过 HTTP 下载大量小文件，可能速度很慢。一次镜像花费时间太长，会导致镜像与上游有比较大的延迟。

**Comment by skyzh** [comment]
- [x] add ostree and flatpak to lug image
- [ ] trigger first sync
- [ ] beta
- [ ] publish

**Comment by skyzh** [comment]
Flathub 测试镜像已上线，可以通过
```
sudo flatpak remote-modify flathub --url=https://mirrors.sjtug.sjtu.edu.cn/flathub
```
测试使用。之后域名还会更换成新服务器，届时会更新文档并同步到 flathub 社区。

**Comment by skyzh** [comment]
related: https://github.com/sjtug/mirror-requests/issues/87

**Comment by skyzh** [comment]
已正式上线。域名换成了 `mirror.sjtu.edu.cn`。

```
sudo flatpak remote-modify flathub --url=https://mirror.sjtu.edu.cn/flathub
```
