### ISSUE TITLE
Fedora SilverBlue

### ISSUE THREAD

**Issue by bhuztez** [sjtug/mirror-requests#87]
镜像名: Fedora SilverBlue

上游路径: https://ostree.fedoraproject.org

镜像简介: https://silverblue.fedoraproject.org/

基于OSTree的发行版安装方式，配合flatpak使用

**Comment by skyzh** [comment]
看起来也是一个 ostree 镜像，会考虑和 https://github.com/sjtug/mirror-requests/issues/86 一起做。

**Comment by skyzh** [comment]
`fedora-ostree` 和 `fedora-int` 测试版已经上线。之后会更换服务器和域名，而后向社区同步。现在可以通过以下方法试用：

```
vim /etc/ostree/remotes.d/fedora.conf
```

```
[remote "fedora"]
url=https://mirrors.sjtug.sjtu.edu.cn/fedora-ostree
gpg-verify=true
gpgkeypath=/etc/pki/rpm-gpg/
# contenturl=mirrorlist=https://ostree.fedoraproject.org/mirrorlist
```

**Comment by skyzh** [comment]
fedora-iot 在测试服务器已上线，预计下个月开放。

**Comment by skyzh** [comment]
看起来 Fedora Silverblue 会出发现服务器的 ratelimit。那么只能等新服务器上线了（

**Comment by skyzh** [comment]
镜像已于 mirror.sjtu.edu.cn 正式上线。

```
[remote "fedora"]
url=https://mirror.sjtu.edu.cn/fedora-ostree
gpg-verify=true
gpgkeypath=/etc/pki/rpm-gpg/
# contenturl=mirrorlist=https://ostree.fedoraproject.org/mirrorlist
```
