### ISSUE TITLE
Pop!_OS

### ISSUE THREAD

**Issue by winnochan** [sjtug/mirror-requests#89]
镜像名: Pop!_OS

上游路径: https://apt.pop-os.org/ubuntu/

镜像简介: 官网: https://pop.system76.com/, Pop!_OS是基于Ubuntu的Linux发行版

国内其他镜像源同步情况: 没找到

同步方法: 没找到

镜像大小: 没找到

**Comment by skyzh** [comment]
请不要重复提交新镜像请求。 https://github.com/sjtug/mirror-requests/issues/79
