### ISSUE TITLE
切换到rsync-huai

### ISSUE THREAD

**Issue by htfy96** [sjtug/mirror-requests#9]
**类别**：Bug反馈

rsync每次都会全盘扫描，给IO带来了很大压力。rsync-huai 不再扫描文件内容，而是用size/mod time来判断文件是否同步。

Ref: https://github.com/ustclug/discussions/issues/37

**Comment by skyzh** [comment]
As IOPS is strictly limited in rsync docker container, this issue could be solved without using rsync-huai.
