### ISSUE TITLE
请求增加Ubuntu Ports

### ISSUE THREAD

**Issue by elnx** [sjtug/mirror-requests#90]
镜像名: ubuntu-ports

上游路径: http://ports.ubuntu.com/ubuntu-ports/

镜像简介: 官方源ports.ubuntu.com支持了ARM、AArch64和PowerPC等架构的设备。

**Comment by skyzh** [comment]
请不要重复提交新镜像请求。 https://github.com/sjtug/mirror-requests/issues/38
