### ISSUE TITLE
请求MSYS2镜像

### ISSUE THREAD

**Issue by ricky136973** [sjtug/mirror-requests#91]
镜像名: MSYS2

上游路径: 

镜像简介: MINGW与MSYS镜像

国内其他镜像源同步情况:
- [清华开源软件镜像站](https://mirrors.tuna.tsinghua.edu.cn/msys2/)
- [中国科技大学开源软件镜像站](https://mirrors.ustc.edu.cn/msys2/)

同步方法:

镜像大小:

**Comment by skyzh** [comment]
We're working on this mirror. It is expected to be available next week.

**Comment by skyzh** [comment]
The synchronization has begun. Please wait patiently until first sync completes.

**Comment by skyzh** [comment]
By the way, would you please send a PR to https://github.com/sjtug/portal/tree/master/content/post/mirror-help for instructing our users how to use this mirror?

**Comment by ricky136973** [comment]
> By the way, would you please send a PR to https://github.com/sjtug/portal/tree/master/content/post/mirror-help for instructing our users how to use this mirror?

Thanks very much for adding this mirror, and I've send a [PR](https://github.com/sjtug/portal/pull/24) to add msys2.md in the directory above.
