### ISSUE TITLE
more prometheus data

### ISSUE THREAD

**Issue by skyzh** [sjtug/mirror-requests#97]
- [x] clash exporter
- [x] lug exporter
- [x] caddy exporter
- [x] http traffic by service

FYI https://github.com/sjtug/mirror-requests/issues/40

**Comment by htfy96** [comment]
Caddy is already exported at https://metrics.mirrors.sjtug.sjtu.edu.cn/
lug: http://mirrors.sjtug.sjtu.edu.cn:8081/metrics
